CliMA/ClimateMachine.jl

src/CLIMA-atmos/Dycore/drivers/rising_thermal_bubble.jl
src/CLIMA-atmos/Dycore/src/CLIMAAtmosDycore.jl
src/CLIMA-atmos/Dycore/src/gpu.jl

In anticipation for using energy as a prognostic variable in the moist
dynamical core we now use the total energy as a prognostic variable.

[AtmosDycore] Use total energy as a prognostic variable

---

src/ParametersType/test/test.jl
src/PlanetParameters/test/test.jl

Adding a couple more checks for the ParametersType package
- testing types of operations
- Adding test of using a function to define a parameter
Changing the PlanetParameters test based on @tapios suggestion in \#18

Updating tests for ParametersType and PlanetParameters

---

docs/CodingConventions.md

Any suggestions for modifying this?
cc/ @tapios @lcw @jkozdon @christophernhill

Added Coding Conventions to a docs folder

---

src/PlanetParameters/test/test.jl

PlanetParameters modifications of \#25 broke the tests. This fixes them.

Fixing PlanetParameters tests

---

src/CLIMA-atmos/Dycore/drivers/isentropic_vortex.jl
src/CLIMA-atmos/Dycore/src/VanillaEuler.jl
src/CLIMA-atmos/Dycore/src/VanillaEuler_cuda.jl

This adds a standard Euler equations reference solution.  For this to work I needed to update the kernels to respect the option to turn gravity off.

[AtmosDycore] Add an isentropic vortex driver

---

src/CLIMA-atmos/Dycore/src/VanillaEuler.jl
src/CLIMA-atmos/Dycore/src/VanillaEuler_cuda.jl

This adds constant viscosity to stabilize the vanilla discontinuous Galerkin discretization.  This implementation matches `nse3d.jl` and `nse2d.jl` from [Canary.jl](https://github.com/climate-machine/Canary.jl).

[AtmosDycore] Add constant viscosity to vanilla

---

src/PlanetParameters/src/PlanetParameters.jl
src/Utilities/Manifest.toml
src/Utilities/src/MoistThermodynamics.jl
src/Utilities/src/RootSolvers.jl
src/Utilities/src/Utilities.jl
src/Utilities/test/runtests.jl

@tapios mentioned that the `Roots.jl` package seemed to have some bugs. I converted the secant method solver in SCAMPy to Julia and included it in `Utilities`. This also has the benefit that it returns a Bool indicating convergence, which may be useful.

Roots -> in-house RootSolvers in Utilities

---

src/ClimaAtmos/Dycore/drivers/isentropic_vortex.jl
src/ClimaAtmos/Dycore/drivers/rising_thermal_bubble.jl
src/ClimaAtmos/Dycore/drivers/tracers_test.jl

[AtmosDycore] Make drivers windows friendly

---

src/ClimaAtmos/Dycore/drivers/isentropic_vortex.jl
src/ClimaAtmos/Dycore/src/Topologies.jl
src/ClimaAtmos/Dycore/test/mpi_connect_stacked.jl
src/ClimaAtmos/Dycore/test/mpi_connect_stacked_3d.jl
src/ClimaAtmos/Dycore/test/runtests.jl
src/ClimaAtmos/Dycore/test/topology.jl

This series of commits adds a `StackedBrickTopology` type that is a drop in replacement for `BrickTopology`.  The stacked topology has elements ordered such that elements in a stack are contiguous.

Stacked Brick Topology

---

src/Utilities/src/MoistThermodynamics.jl
src/Utilities/test/runtests.jl

Added "Phase" type to dispatch sat_vapor_press

---

.gitlab-ci.yml

add gitlab CI

---

Manifest.toml
src/ClimaAtmos/Dycore/src/AtmosStateArrays.jl
src/ClimaAtmos/Dycore/src/Grids.jl
src/ClimaAtmos/Dycore/src/Topologies.jl
src/ClimaAtmos/Dycore/src/vtk.jl
src/ClimaAtmos/Dycore/test/mpi_connect_sphere.jl
src/ClimaAtmos/Dycore/test/runtests.jl

This pull requests adds a `StackedCubedSphereTopology` type.

Adding StackedCubedSphereTopology type

---

src/Utilities/src/MoistThermodynamics.jl
src/Utilities/test/runtests.jl

This is to partially address #119

[MoistThermo] + exner & dry_pottemp, + exports

---

src/ClimaAtmos/Dycore/src/AtmosStateArrays.jl
src/ClimaAtmos/Dycore/src/CLIMAAtmosDycore.jl
src/ClimaAtmos/Dycore/src/GenericCallbacks.jl
src/ClimaAtmos/Dycore/src/Grids.jl
src/ClimaAtmos/Dycore/src/Topologies.jl
src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations.jl

This is not a complete documentation of the Dycore, but just a step in the right
direction. AtmosDycore still needs smoothing, some of which has been indicated
with `!!! todo``` comments in the docs

[AtmosDycore] Adding more (basic) docs to AtmosDycore

---

.gitignore

Added the following lines/extensions to the git ignore:
src/**/*.vtk
src/**/*.vtu
src/**/*.swp
src/**/*.png

[git] Added file extensions to git ignore

---

env/gpu/Manifest.toml
src/ODESolvers/LowStorageRungeKuttaMethod.jl

#146 had a typo for the include statement of `LowStorageRungeKuttaMethod_cuda.jl`. This fixes that and updates the GPU Manifest.

 fix LowStorageRungeKuttaMethod_cuda include

---

.appveyor.yml
.travis.yml
README.md

I've switched appveyor to a joint account
Fixes #161, #162

Update appveyor link, build only on master/staging/trying branches

---

docs/make.jl
docs/src/AcceptableUnicode.md
docs/src/Arrays.md
docs/src/AtmosDycore.md
docs/src/DGmethods.md
docs/src/Mesh.md
docs/src/ODESolvers.md
docs/src/VariableList.md
src/DGmethods/DGBalanceLawDiscretizations.jl
src/ODESolvers/ODESolvers.jl

- Fixing some broken links in the docs
- Exposing constructors for Topologies
- Fixing some formatting inconstistency issues AcceptableUnicode & VariableList
- Adding  docs for DGmethods

Updating website docs

---

docs/src/Mesh.md
src/Mesh/Topologies.jl
src/Mesh/test/topology.jl

For the balance law solver we need functionality to check whether a given topology has a boundary. This adds that functionality by adding a `hasboundary` function to `Topologies`

Query function for whether a topology has a boundary

---

docs/src/Atmos/SurfaceFluxes.md

[docs] Add definition for flux

---

src/DGmethods/DGBalanceLawDiscretizations.jl
src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
src/DGmethods/NumericalFluxes.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone_aux.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone_bc.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone_source.jl
src/DGmethods/test/runtests.jl
src/DGmethods/test/util/grad_test.jl

Duplicate of #187 in the hopes that removing bad branch name gitlab works.

Adding boundary conditions to balance law solver

---

src/Arrays/MPIStateArrays.jl
src/DGmethods/DGBalanceLawDiscretizations.jl

Hoping that this will address issues seen in https://github.com/climate-machine/CLIMA/issues/194#issuecomment-486006248.
@simonbyrne Can you give this a try?
@lcw You think this is reasonable?

Allowing the user to wait on the MPI Isends as well as Irecvs

---

docs/src/Utilities/MoistThermodynamics.md
src/Atmos/Dycore/src/VanillaAtmosDiscretizations.jl
src/Atmos/Dycore/src/VanillaAtmosDiscretizations_kernels.jl
src/Atmos/Dycore/test/rising_thermal_bubble.jl
src/Atmos/Dycore/test/tracers_test.jl
src/Atmos/Parameterizations/SurfaceFluxes/src/SurfaceFluxes.jl
src/Utilities/MoistThermodynamics/src/MoistThermodynamics.jl
src/Utilities/MoistThermodynamics/src/states.jl
src/Utilities/MoistThermodynamics/test/runtests.jl

[MoistThermo] use PhasePartition object

---

docs/src/Atmos/EDMFEquations.md

Fixing typos / adding references.

[TurbConv] polishing docs

---

src/DGmethods/DGBalanceLawDiscretizations.jl
src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
src/DGmethods/NumericalFluxes.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone_aux.jl
src/DGmethods/test/Euler/isentropic_vortex_standalone_bc.jl
src/DGmethods/test/compressible_Navier_Stokes/mms_bc.jl
src/DGmethods/test/runtests.jl

A few minor tweaks to the Balance law framework based on conversations with @lcw and @fxgiraldo

[BL] Minor tweaks/cleanups

---

docs/src/Atmos/EDMFEquations.md

Fixed docs regarding eddy-diffusivity related to momentum/heat

[TurbConv] Fixed docs for Eddy-diffusivity

---

docs/src/Atmos/EDMFEquations.md

- Fixed duplicate label
- Improved clarity of indexes for area fraction equations
- Simplified indexes for other subdomain equations

[TurbConv] EDMF doc updates

---

src/DGmethods/DGBalanceLawDiscretizations.jl
src/ODESolvers/LowStorageRungeKuttaMethod.jl
src/Utilities/MoistThermodynamics/src/MoistThermodynamics.jl

I was trying to load CLIMA.jl from within tests in DG methods from within Julia repl. I was getting errors about Julia not finding certain modules. It helped to change the paths in the using statement like this. Is that correct?

... -> .. ?

---

src/Utilities/MoistThermodynamics/states.jl

The call to the phase partition function was fixed.

[MoistThermo] Fixed LiquidIcePotTempSHumEquil

---

src/DGmethods/DGBalanceLawDiscretizations.jl
src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc.jl

The primary use case for this is to allow the user to process data
before writing out the VTK file

[BL] Add ability to add custom user data arrays

---

src/InputOutput/Vtk/writevtk.jl

Bug fix for vtk in old dycore introduced by #230

Fix VTK for old atmos dycore

---

.slurmci/gpu-init.sh
.slurmci/gpu-test.sh
.slurmci/gpu.sh

Fixes build issue with incompatible cluster images

set Slurm CUDA_PATH

---

docs/src/Atmos/EDMFEquations.md

- Added definitions for coefficients in BCs
- Fixed coefficient in cross-gradient flux source term
- Fixed buoyancy flux name (used to be theta, now b)
- Removed unused source term

[TurbConv] Updated docs

---

test/DGmethods/Euler/isentropic_vortex_standalone.jl
test/DGmethods/Euler/isentropic_vortex_standalone_aux.jl
test/DGmethods/Euler/isentropic_vortex_standalone_bc.jl
test/DGmethods/Euler/isentropic_vortex_standalone_source.jl
test/DGmethods/compressible_Navier_Stokes/dycoms.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc.jl
test/DGmethods/compressible_Navier_Stokes/rtb_visc.jl
test/DGmethods/conservation/sphere.jl
test/DGmethods/sphere/advection_sphere_lsrk.jl
test/DGmethods/sphere/advection_sphere_ssp33.jl
test/DGmethods/sphere/advection_sphere_ssp34.jl
test/DGmethods/util/grad_test.jl
test/DGmethods/util/grad_test_sphere.jl

Realized after discussions with @mwarusz that we should be using `@testset` in the tests and that the first level integration test is probably short enough for our current CI set up (so we can get rid of the random testing)

Rework tests to add @testset and remove random

---

.slurmci/jobs.jl

These have been timing out for non-obvious reasons. I'll disable for now until I can figure this out.

[SlurmCI] Disable runtests_gpu.jl

---

README.md

Removed travis/appveyor badge, added azure pipeline badge

[README] travis/appveyor badge -> azure badge

---

src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
src/Utilities/PlanetParameters/PlanetParameters.jl

@tapios is that what you had in mind?

\rho_liquid -> \rho_cloud_liq, add \rho_cloud_ice

---

src/Atmos/Model/AtmosModel.jl
src/DGmethods/DGmodel.jl

This includes 2 of the fixes from #351.

Communicate aux states, zero out source terms

---

src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/moisture.jl
src/Atmos/Model/orientation.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl

Ideally we would make use of the topology structure here, but I can't think of a good way to do that in the current configuration. This seems like the easiest option for now.

add gravitational potential

---

src/DGmethods/DGmodel_kernels.jl

Based on @charleskawczynski suggestion in https://github.com/climate-machine/CLIMA/pull/383#issuecomment-524007193

Zero out arrays before use fills them

---

src/Atmos/Model/moisture.jl

\rho_SGS_enthalpyflux -> \rhod_h_tot, density scaling fix

varnames patch: total_enthalpy -> h_tot, SGS_enthalpyflux -> \rhod_h_tot

---

src/Mesh/BrickMesh.jl
src/Mesh/Topologies.jl
test/Mesh/BrickMesh.jl
test/Mesh/mpi_connect.jl
test/Mesh/mpi_connect_1d.jl
test/Mesh/mpi_connect_ell.jl
test/Mesh/mpi_connect_stacked.jl
test/Mesh/mpi_connect_stacked_3d.jl
test/Mesh/mpi_partition.jl
test/Mesh/topology.jl

This matches up with the other parameters (ranges, periodicity)

Topology: change boundary argument to use tuple of tuples

---

.slurmci/gpu-init.sh
.slurmci/gpu-test.sh
.slurmci/gpu.sh
.slurmci/jobs.jl
src/Arrays/MPIStateArrays.jl
test/Arrays/basics.jl
test/Arrays/broadcasting.jl
test/Arrays/reductions.jl
test/Arrays/runtests.jl
test/runtests_gpu.jl
test/testhelpers.jl

This is a revamp of #406 (I didn't want to force-push to that branch). Instead of defining new functions, this just adds a keyword `dims` argument to `norm`

Add dims argument to norm

---

src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/turbulence.jl
src/Utilities/VariableTemplates/VariableTemplates.jl
src/Utilities/VariableTemplates/var_names.jl
test/Utilities/VariableTemplates/runtests.jl

It turns out this was already in StaticArrays

use SHermitianCompact for symmetric tensors

---

src/Atmos/Model/turbulence.jl

Remove `Float64` hard coding from `ConstantViscosityWithDivergence`

Fix type in ConstantViscosityWithDivergence

---

src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/moisture.jl
src/DGmethods/DGmodel_kernels.jl

This pull request:
- brings back `volumerhs!` performance-improving loop reorderings that accidentally got lost when moving to the new framework
- adds further minor changes that should improve the performance

Performance improvements

---

src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/boundaryconditions.jl
src/DGmethods/DGmodel_kernels.jl
src/DGmethods/NumericalFluxes.jl
src/DGmethods/balancelaw.jl
src/Utilities/VariableTemplates/VariableTemplates.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl
test/DGmethods/compressible_Navier_Stokes/mms_model.jl
test/DGmethods/integral_test.jl
test/DGmethods/integral_test_sphere.jl

Make the BC interfaces more general

Update boundary conditions interface

---

src/Atmos/Model/AtmosModel.jl
src/DGmethods/DGmodel.jl
src/DGmethods/balancelaw.jl
src/Mesh/Topologies.jl
test/DGmethods/integral_test.jl
test/DGmethods/integral_test_sphere.jl

- Cleans up the reverse_indefinite_stack_integral!
- fix typo in Topologies
- Allow generation of Q without initialization
- allow custom ode_params for a balance law

cleanup and interface exposure

---

examples/DGmethods/ex_001_dycoms.jl
src/Mesh/Topologies.jl
test/DGmethods/integral_test_sphere.jl
test/DGmethods_old/compressible_Navier_Stokes/MWE_grid_stretching.jl
test/Mesh/topology.jl

As an alternative to #444.
@smarras79 @slifer50 does this help make the code a bit simpler?

improve grid stretching interface, add tests

---

examples/DGmethods/ex_001_dycoms.jl
src/Atmos/Model/boundaryconditions.jl

diffusive.moisture.h_tot -> diffusive.h_tot	
modified:   src/Atmos/Model/boundaryconditions.jl

Update b.c. to reflect h_tot at top level (per #453)

---

src/ODESolvers/AdditiveRungeKuttaMethod.jl
src/ODESolvers/AdditiveRungeKuttaMethod_kernels.jl
src/ODESolvers/MultirateRungeKuttaMethod.jl
src/ODESolvers/MultirateRungeKuttaMethod_kernels.jl
test/ODESolvers/runtests.jl

- Add a test problem from RobertsSarsharSandu2018arxiv
- Allow for multirate within multirate (for more than one rate level)
```
@article{RobertsSarsharSandu2018arxiv,
title={Coupled Multirate Infinitesimal GARK Schemes for Stiff Systems with
Multiple Time Scales},
author={Roberts, Steven and Sarshar, Arash and Sandu, Adrian},
journal={arXiv preprint arXiv:1812.00808},
year={2019}
}
```

Add multirate test and allow nested multirate

---

src/DGmethods/DGmodel.jl
src/DGmethods/DGmodel_kernels.jl
test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl

This teaches `DGModel` to apply its derivatives in the horizontal, the vertical, or every direction.

Teach DGModel about horizontal and vertical

---

.slurmci/test_set.jl
examples/Atmos/heldsuarez.jl
src/Atmos/Model/source.jl
test/DGmethods/compressible_Navier_Stokes/heldsuarez.jl

Visually checked by @mwarusz. We still need some diagnostics, then we can start exploring modifications (imex, turbulence models, etc).

Held-Suarez example

---

src/ODESolvers/AdditiveRungeKuttaMethod.jl
src/ODESolvers/LowStorageRungeKuttaMethod.jl
src/ODESolvers/MultirateRungeKuttaMethod.jl
src/ODESolvers/ODESolvers.jl
src/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl

It doesn't seem like there is much to be gained by immutability here.

change ODE solvers to mutable structs instead of arrays for mutable fields

---

src/ODESolvers/MultirateInfinitesimalStepMethod.jl
test/ODESolvers/runtests.jl

TVDMISB works, however beta values for TVDMISA appear to be incorrect. Awaiting input from the author.

add TVDMIS methods

---

src/Atmos/Model/linear.jl

Our tests for this model are apparently not the greatest ...

Fix direction of gravity in AtmosAcousticGravityLinearModel

---

docs/make.jl
src/Atmos/Model/source.jl

fix subsidence definition

---

azure-pipelines.yml

Doc builds are timing out, so am disabling them for now until I can figure out what is
going on.

Disable docs

---

examples/DGmethods/ex_001_dycoms.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/moisture.jl
src/Atmos/Model/source.jl

Changes in this PR 
1) Remove `subsidence` source term : (incorporate into `flux_nondiffusive` with projection onto vertical direction)
2) Add EquilMoist flux term.

Patch moisture term

---

src/Common/MoistThermodynamics/MoistThermodynamics.jl

Update MT docs

---

examples/DGmethods/ex_001_dycoms.jl
src/Arrays/MPIStateArrays.jl
src/CLIMA.jl
src/InputOutput/VTK/VTK.jl
src/InputOutput/VTK/writepvtu.jl
src/InputOutput/VTK/writevtk.jl
src/Utilities/TicToc/TicToc.jl
test/Utilities/TicToc/runtests.jl
test/runtests.jl

~~Work in progress.~~ Complete.
Currently instrumented:
- DYCOMS driver
- MPI calls
- VTK output
Export `TICTOC_PRINT_RESULTS=1` to display timing output.

Module for timing

---

src/Arrays/MPIStateArrays.jl
test/Arrays/reductions.jl

MPIStateArrays: add generic mapreduce support

---

src/Arrays/MPIStateArrays.jl
src/DGmethods/DGmodel.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl

This wasn't tested, and appears to have broken after the recent MPIStateArray changes.

change mechanism for init on CPU

---

examples/DGmethods/ex_001_dycoms.jl
src/Atmos/Model/source.jl
test/Diagnostics/dycoms_sin_test.jl

Updates `AtmosModel` sources, broken off from #610.
Needs review.

Update Atmos sources

---

README.md

Moves the pipeline over to our shared account.

Switch to new Azure Pipeline

---

examples/DGmethods/ex_001_dycoms-imex.jl
examples/DGmethods/ex_001_dycoms.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/boundaryconditions.jl
src/Atmos/Model/moisture.jl
src/Atmos/Model/turbulence.jl
src/DGmethods/NumericalFluxes.jl
src/Diagnostics/Diagnostics.jl
src/Driver/Driver.jl
test/Diagnostics/dycoms_sin_test.jl
test/LinearSolvers/poisson.jl

Proposed scheme to close out #626

Make diffusive! terms linear 

---

experiments/LES/dycoms.jl
slurmci-test.toml
src/Diagnostics/Diagnostics.jl
src/Driver/Driver.jl
test/Driver/driver_test.jl
test/Driver/runtests.jl

Also, diagnostics collection should be on by default.
Fixes #634

`experiments/LES/dycoms.jl` now runs and generates correct results

---

test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl

Update advection diffusion to use Julia 1.3 results; Slurm CI upgraded to with climate-machine/slurmci#11

Update advection diffusion test to Julia 1.3

---

slurmci-test.toml
src/Ocean/Model/HydrostaticBoussinesqModel.jl
test/Ocean/Hydrostatic_Boussinesq/simple_box_IMEX.jl
test/Ocean/Hydrostatic_Boussinesq/test_divergence_free_IMEX.jl

This PR adds a LinearHBModel to implement the 1D IMEX for vertical viscosity and diffusion. 
The configuration is only tested for viscosity as this is constant in space and time. We need to modify the linear solvers to update the matrices with time to account for the diffusion changes required for the convective adjustment.

Add linearHBmodel to implement 1D IMEX for vertical viscosity.

---

slurmci-test.toml
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/boundaryconditions.jl
src/Atmos/Model/linear.jl
src/DGmethods/NumericalFluxes.jl
src/Ocean/Model/HydrostaticBoussinesqModel.jl
src/Ocean/Model/ShallowWaterModel.jl
test/DGmethods/advection_diffusion/advection_diffusion_model.jl
test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
test/DGmethods/advection_diffusion/pseudo1D_heat_eqn.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
test/DGmethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl

Update boundary conditions to Bassi and Rebay (1997)

---

src/Atmos/Model/boundaryconditions.jl

@mwarusz found a bug in the DYCOMS bc that no boundary conditions was being enforced on the top boundary on the diffusive variables.
This PR fixes that as well as removes unused variables in the boundary conditions (such as some unused moist physics calls) and also refactors the `DYCOMS_BC` to reuse values computed for the `NoFluxBC` whenever possible.
Co-authored-by: Maciej Waruszewski <mwarusz@igf.fuw.edu.pl>

Clean up dycoms BC

---

src/Common/MoistThermodynamics/MoistThermodynamics.jl
src/Common/MoistThermodynamics/isentropic.jl
test/Common/MoistThermodynamics/runtests.jl

- Adds isentropic relations to moist thermo.
I'm not sure what others we need, but it would be nice to change all instances of these hard-coded equations into function calls.

Add isentropic relations

---

Manifest.toml
Project.toml
src/Mesh/Interpolation.jl
test/Mesh/interpolation.jl

Interpolation machinery is being updated to utilize GPUs.

Interpolation machinery

---

src/LinearSolvers/GeneralizedConjugateResidualSolver.jl
src/LinearSolvers/GeneralizedMinimalResidualSolver.jl
src/LinearSolvers/LinearSolvers.jl
test/DGmethods/Euler/isentropicvortex-imex.jl
test/DGmethods/Euler/isentropicvortex-multirate.jl
test/DGmethods_old/Euler/RTB_IMEX.jl
test/DGmethods_old/Euler/isentropic_vortex_standalone_IMEX.jl
test/LinearSolvers/iterativesolvers.jl
test/LinearSolvers/poisson.jl
test/LinearSolvers/runtests.jl
test/LinearSolvers/smallsystem.jl

Change `residual_norm < norm(b)` to `residual_norm < norm(inital_residual) * rel_tolerance`.
Adding larger tests soon.

Termination conditionGMRES matches IterativeSolvers.jl

---

examples/Atmos/dry_rayleigh_benard.jl
experiments/Atmos_LES/dycoms.jl
experiments/Atmos_LES/risingbubble.jl
experiments/Atmos_LES/surfacebubble.jl
slurmci-test.toml
src/Atmos/Model/orientation.jl

RTB with prescribed bottom boundary fluxes. 
1) Adds `LES` `experiment` file. 
2) Exports `vertical_unit_vector`
3) Cleans up dycoms + surfacebubble redundant b.c. function

Surface driven bubble problem 

---

src/Diagnostics/AtmosDiagnostics.jl
src/Diagnostics/Diagnostics.jl
src/Diagnostics/OceanDiagnostics.jl
src/Driver/Configurations.jl
src/Driver/Driver.jl
test/Diagnostics/sin_test.jl

Slightly better structure now.
- Supports different balance laws (stubs for Ocean diagnostics added) (fixes #702)
- Temporary fix for use of non-EquilMoist models (fixes #699)

Small improvements to Diagnostics

---

src/Arrays/MPIStateArrays.jl

The CPU version was buggy. The GPU version didn't work. It didn't make much sense to begin with, since l_inf is not an integral.

Remove weighted infinity norm

---

src/Mesh/Interpolation.jl
test/Mesh/interpolation.jl

Coverted lat and long grid output to degrees from radians. Shifted the lat range to -90 -> 90 from 0 -> 180.

Converted lat and long grid output to degrees from radians

---

src/Driver/Driver.jl

Accidentally introduced in #689.

Fix bug in VTK callback

---

experiments/Atmos_LES/dycoms.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/linear.jl
src/Atmos/Model/radiation.jl
src/Atmos/Model/remainder.jl
src/DGmethods/DGmodel.jl
src/DGmethods/DGmodel_kernels.jl
src/DGmethods/balancelaw.jl
src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
test/DGmethods/integral_test.jl
test/DGmethods/integral_test_sphere.jl

Allows the user to say where integrals are stored and what integrals are reversed

New approach to doing integrals

---

test/DGmethods/courant.jl
test/DGmethods/runtests.jl

Since the result is quite small and the calculation is multiplicative, it makes sense to use a relative tolerance here.

Change Courant tests to use relative tolerances

---

Manifest.toml
src/Driver/Driver.jl

Also fix incorrect dependency for Pkg.

Fix deprecation warning caused by new package

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/GENERAL_ISSUE.md
.github/pull_request_template.md
.github/pull_request_template.md.bak

This fixes #741 
This PR adds PR and Issue templates, as discussed with several members of the CliMA development team.
Please let me know what you feel should be added or anything you feel is could be improved.

adding templates for ISSUE and PR templates

---

src/DGmethods/DGmodel_kernels.jl
src/Driver/Driver.jl
src/LinearSolvers/ColumnwiseLUSolver.jl
src/Mesh/Grids.jl
test/DGmethods/Euler/acousticwave-1d-imex.jl
test/DGmethods/advection_diffusion/direction_splitting_advection_diffusion.jl
test/DGmethods/advection_diffusion/periodic_3D_hyperdiffusion.jl
test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
test/DGmethods/advection_diffusion/pseudo1D_heat_eqn.jl
test/DGmethods/courant.jl
test/DGmethods_old/util/filter_test.jl
test/LinearSolvers/bandedsystem.jl
test/Mesh/min_node_distance.jl

These are used a lot maybe it would be good to export them ?

Export directions from Grids

---

experiments/Atmos_GCM/heldsuarez.jl
src/Atmos/Model/orientation.jl
src/Driver/Driver.jl

We need a few fixes to the Held-Suarez setup as it currently stands. This PR will address the following problems:

Re-engineer Held-Suarez setup

---

test/Atmos/Parameterizations/runtests.jl
test/Atmos/runtests.jl
test/Common/runtests.jl
test/Utilities/runtests.jl
test/runtests.jl

Compress if-statements in test suite. These were some suggestions I missed in #815.

Compress if-statement in test suite

---

slurmci-test.toml

bump time Rayleigh Bernard time limit

---

experiments/AtmosLES/bomex.jl
slurmci-perf.toml
slurmci-test.toml
src/Atmos/Model/source.jl

Adds the BOMEX - LES experiment. 
Shallow-cumulus experiment (6.4km x 6.4km x 3km domain)
1) Large scale subsidence, temperature tendency, moisture tendency, geostrophic relaxation, linear sponge, gravity sources 
2) Prescribed surface flux boundary conditions 
3) The Julia auto-formatter has been applied to the modified files :D 
Key upcoming changes: 
Boundary condition interface changes will follow shortly, as will atomized sources.

Add BOMEX experiment

---

experiments/OceanBoxGCM/ocean_gyre.jl
slurmci-test.toml
src/Driver/Driver.jl

Throw an exception if norm(Q) == NaN

---

slurmci-test.toml
src/Diagnostics/Diagnostics.jl
src/Diagnostics/diagnostic_fields.jl
src/Diagnostics/diagnostic_fields_kernels.jl
src/Mesh/Interpolation.jl
test/Diagnostics/diagnostic_fields_test.jl
test/Mesh/interpolation.jl

New fields added for diagnostics

---

docs/Manifest.toml
docs/Project.toml
docs/make.jl
docs/src/Diagnostics.md
src/Diagnostics/diagnostic_fields.jl

Adding documentation to Diagnostics module.

---

docs/make.jl
docs/src/DiagnosticVariables.md
docs/src/VariableList.md

- Add a separate file (DiagnosticVariables.md) for the list of diagnostic variables in CliMA.
- Point to DiagnosticVariables.md in the Diagnostics section in VariableList.md (not linked yet).
I have

add DiagnosticVariables.md

---

docs/src/DiagnosticVariables.md
docs/src/VariableList.md

- fix the underscore issue in DiagnosticVariables.md
- fix some minor issues in DiagnosticVariables.md and VariableList.md
I have

fix underscore issue in DiagnosticVariables.md

---

README.md
docs/src/Installation.md

Adding a simple guide for installing CLIMA (essentially the content already in the README, but now in the documentation as well.
Let me know what you think is important to put into this!
I have

Installation instructions in documentation

---

docs/src/APIs/Numerics/Meshes/Mesh.md
src/Numerics/Mesh/Interpolation.jl

Removes some unnecessary comments and fixes some docs.
I have

Clean up some docs

---

src/Numerics/Mesh/Interpolation.jl

I have
- [] CLIMA developers with relevant expertise have been assigned to review this submission

Minor revision to argument description for projection onto cubed sphere.

---

docs/list_of_extending_clima.jl
docs/src/ContributionGuides/Timestepping.md
docs/src/ExtendingCLIMA/Numerics/ODESolvers/Timestepping.md
docs/src/ExtendingCLIMA/Numerics/ODESolvers/index.md

This PR adds a markdown script (similar to `IterativeMethods.md`) which details what needs to be considered when adding a new time-integrator (ODESolver) to the codebase.
Please feel free to comment and add suggestions if anyone thinks something is missing or needs further elaboration.
I have

Timestepping contribution guide

---

docs/list_of_tutorials.jl
tutorials/Atmos/heldsuarez.jl

Adds the documentation for the Held-Suarez example.
I have

Adding Held-Suarez example documentation

---

azure-pipelines.yml

Since it runs on `staging` and `trying` for bors.
I have

Turn off Azure CI on master

---

docs/list_of_tutorials.jl
docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
docs/src/ExtendingCLIMA/Atmos/AtmosModel.md
docs/src/ExtendingCLIMA/Atmos/Model/risingbubble.md
docs/src/ExtendingCLIMA/Atmos/Model/tracers.md
docs/src/ExtendingCLIMA/Atmos/Model/turbulence.md
docs/src/ExtendingCLIMA/Common/MoistThermodynamics.md
experiments/AtmosLES/risingbubble.jl

Docs for the `risingbubble.jl` `AtmosModel` experiment. Components may need to move around to fit the skeleton guide. 
I have

AtmosModel example 1

---

experiments/AtmosLES/bomex.jl
src/Diagnostics/Diagnostics.jl
src/Diagnostics/atmos_common.jl
src/Diagnostics/atmos_core.jl
src/Diagnostics/atmos_default.jl
src/Diagnostics/thermo.jl
src/InputOutput/VTK/writevtk.jl

Conditional diagnostics (for `q_liq > 0 && w > 0`) as described in #943.
I have

Add atmosphere 'core' diagnostics

---

src/Diagnostics/diagnostic_fields.jl
test/Diagnostics/diagnostic_fields_test.jl

Sign fix for vorticity.

---

src/Driver/solver_configs.jl

For Multirate solvers, the `DGModel` being stored in `solver_config` was not the one being updated.
I have

Store the correct `DGmodel` in `solver_config`

---

docs/src/index.md

This PR add a landing page to the documentation.
Merging this PR was accidentally aborted in #1027. So we have to open it again.
I have

Landing page for documentation (try 2)

---

docs/list_of_experiments.jl
docs/make.jl

Output --help for each experiment file
I have

generate docs for experiments

---

.gitignore
README.md
bors.toml

- Adds some things to the `.gitignore`
- Updates the README to reflect recent changes (and adds docs-build and bors badges)
- Updates the bors status
I have

Update README, bors and some .gitignore

---

README.md

- Fixes Azure and code-cov URLs
I have

Fix README URLs

---

docs/src/HowToGuides/Diagnostics/DiagnosticVariables.md
src/Diagnostics/atmos_core.jl

`ql_core` and `thv_core`.
I have

Add a couple of core diagnostics

---

docs/src/Installation.md

Fixed small erratum in the documentation.
I have
- [Y] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [Y] Followed all necessary [style guidelines](https://CliMA.github.io/CLIMA/latest/CodingConventions.html) and run `julia .dev/format.jl`
- [Y] Updated the documentation to reflect changes from this PR.

Fixed erratum in the installation documentation.

---

experiments/AtmosLES/dycoms.jl

* replaced ztop = 2500 --> ztop = 1500
* replaced sponge maxiter = 1 --? maxiter = 5
* replaced sponge tolerance = FT(100) --? tolerance = FT(1)
* replaced SmagorinskyLilly --> Vreman because it's been giving best results. But SmagorinskyLilly is still good to go.
* replaced sponge thickness from 1000 to 500
* added a commented option to activate multirate
I have

 Small modification for dycoms experiment file

---

.github/workflows/Coverage.yaml
README.md

Also align code coverage OS with OS variant tested under current Linux CI
Closes #1093 
I have

Fix code coverage cron job after CLIMA -> ClimateMachine rename

---

Project.toml
docs/Manifest.toml
docs/list_of_tutorials.jl
docs/src/HowToGuides/Numerics/LinearSolvers/IterativeSolvers.md
src/ClimateMachine.jl
src/Numerics/LinearSolvers/BatchedGeneralizedMinimalResidualSolver.jl
test/Numerics/DGmethods/advection_diffusion/advection_diffusion_model_1dimex_bgmres.jl
test/Numerics/DGmethods/runtests.jl
test/Numerics/LinearSolvers/bgmres.jl
test/Numerics/LinearSolvers/runtests.jl
tutorials/Numerics/LinearSolvers/bgmres.jl

Adds a GMRES that executes a number of independent GMRES routines. It also adds a tutorial and tests. 
I have

Add BatchedGMRES method

---

docs/src/HowToGuides/Numerics/DGmethods/how_to_make_a_balance_law.md

Fixed balance law equation in HowTo Docs
I have

Fixed balance law equation in HowTo Docs

---

README.md

Also gets rid of empty line in table.
I have

Move docs link to top of table in README.md

---

README.md

Fix installation link in readme

---

docs/make.jl
docs/src/Contributing.md
docs/src/DevDocs/CodeStyle.md
docs/src/GettingStarted/Installation.md

* fix some broken external links
* don't deploy by default in local environments when building docs
I have

add docs about writing / generating docs

---

Project.toml

Bump version to 0.2.0
To be merged after branching.
I have

Bump version to 0.2.0-DEV

---

Project.toml

This commit was added to the `release-0.1` branch to pass the registrator checks.
I have

add version bounds

---

tutorials/Atmos/risingbubble.jl

Added:
```
* #    Top and Bottom boundaries:
* #    Lateral boundaries 
```
in `# 2) Boundaries `
and how to change the time integrator from multi-rate to single rate
```
*  # If the user prefers a single rate explicit time integrator,                                                                                        
ode_solver = ClimateMachine.ExplicitSolverType(
solver_method = LSRK144NiegemannDiehlBusch,
)
```
* I would like to add a list of options for explicit `solver_method` but I don't know which ones are currently working and what type of parameters they would require. It would be good to add this though.
* It would also be good to update the tutorial to show how to modify the lateral boundary conditions if we don't want them to be periodic.
I have

 Added some explanations to the tutorial for risingbubble.jl

---

src/Diagnostics/Debug/StateCheck.jl

Fix docs and typos in StateCheck.jl
I have

Fix docs and typos in StateCheck.jl

---

src/InputOutput/Writers/jld2_writer.jl
test/InputOutput/Writers/runtests.jl
test/InputOutput/runtests.jl

Unsure how this passed CI. We're investigating.
I have

Fix broken `Writers` test

---

test/Atmos/TemperatureProfiles/runtests.jl

- Adds some comments explaining temperature profiles tests
Co-authored with: @tapios 
I have

Add comments to temperature profiles tests

---

.github/workflows/Coverage.yaml
.github/workflows/Documenter.yaml

This is no longer necessary.
I have

remove MPI installation from Documenter and Coverage

---

src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl

There was an assumption that the ARK solver is always called with the
same `Q` that it was initialized with. We remove that by not storing `Q`
itself in the struct.

Remove assumption in ARK schemes about `Q`

---

src/Diagnostics/atmos_common.jl

And don't scale it with the polynomial weight.
Fixes #1207.
I have

Compute `z` correctly

---

README.md
docs/list_of_apis.jl
docs/src/APIs/Atmos/AtmosModel.md
docs/src/APIs/Diagnostics/Diagnostics.md
docs/src/APIs/Driver/index.md
docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
docs/src/APIs/Numerics/SystemSolvers/SystemSolvers.md
docs/src/GettingStarted/Installation.md
docs/src/HowToGuides/Numerics/DGMethods/how_to_make_a_balance_law.md
docs/src/HowToGuides/Numerics/ODESolvers/Timestepping.md
docs/src/HowToGuides/Numerics/SystemSolvers/IterativeSolvers.md
docs/src/Theory/Common/SurfaceFluxes.md
src/Atmos/Model/AtmosModel.jl
src/Common/SurfaceFluxes/SurfaceFluxes.jl
src/Common/Thermodynamics/relations.jl
src/Numerics/ODESolvers/GenericCallbacks.jl
src/Numerics/ODESolvers/ODESolvers.jl
src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl

This PR fixes and adds some docs. This was split off from #1181, but does not touch the tutorials.
- Fixes README badge. The link that azure provides is broken, possibly due to the org name change, so I've just added a more generic build URL
Supersedes #1051.
I have

Fix and add docs

---

src/Numerics/Mesh/Interpolation.jl

Bug fix for interpolation `dimensions()`

---

docs/list_of_tutorials.jl
tutorials/Atmos/heldsuarez.jl

This PR was broken off from #1181
- Fixes the held suarez tutorial
- Reduces the `timeend`, so that it finishes in a short amount of time
Ideally, this tutorial plots some results (even if very crude). @bischtob is there a short plotting script in viz clima that we can use to add a plot to this tutorial?
I have

Fix held suarez tutorial, and run in docs

---

docs/list_of_tutorials.jl
docs/plothelpers.jl
src/Utilities/SingleStackUtils/SingleStackUtils.jl
tutorials/Atmos/burgers_single_stack.jl

Added horizontal statistics diagnostics for single stack driver and a single stack tutorial of the 3D Burgers equation. Modified plothelpers.jl to admit the xlabel as a keyword argument.
I have

Added single stack horizontal statistics and test

---

.github/workflows/Documenter.yaml

Fix docs warnings

---

src/Utilities/SingleStackUtils/SingleStackUtils.jl
test/Utilities/SingleStackUtils/horizontal_stats_test.jl
test/Utilities/SingleStackUtils/runtests.jl
test/Utilities/runtests.jl

Unit tests for horizontal statistics SingleStackUtils.

---

docs/src/APIs/Utilities/SingleStackUtils.md
src/Utilities/SingleStackUtils/SingleStackUtils.jl
test/Utilities/SingleStackUtils/runtests.jl
test/Utilities/SingleStackUtils/ssu_tests.jl

And a couple of tests. Closes #1175.
I have

Add `reduce_[nodal|element]_stack()` in `SingleStackUtils`

---

.github/workflows/Documenter.yaml
.github/workflows/Linux-UnitTests.yml
.github/workflows/OS-UnitTests.yml

Based on https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484
Hopefully should reduce download errors.
I have

cache artifacts in GitHub Actions

---

src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl

Enable user to change the amount of convective adjustment for the HBModel at runtime by turning the convective adjustment diffusivity into a model parameter.
I have

Add model parameter for convective adjustment diffusivity

---

src/Driver/Driver.jl
src/Driver/solver_configs.jl
test/Driver/mms3.jl
test/Driver/runtests.jl

And small fixes to get it working again.
I have

Enable checkpoint/restart test

---

docs/src/APIs/Diagnostics/Diagnostics.md
docs/src/DevDocs/DiagnosticVariables.md
docs/src/DevDocs/VariableList.md
docs/src/GettingStarted/RunningClimateMachine.md

And how they can be controlled.
Closes #1300.
I have

Add documentation for `ClimateMachine` settings

---

docs/src/APIs/Common/Orientations.md
experiments/AtmosGCM/baroclinic-wave.jl
experiments/AtmosGCM/isothermal-zonal-flow.jl
experiments/AtmosGCM/nonhydrostatic-gravity-wave.jl
src/Common/Orientations/Orientations.jl

This PR is co-authored by: @bischtob, @mwarusz, and @akshaysridhar, and supersedes both #1193 and #1205. We have added a suite of experiments for the GCM model. This includes the following:
1. A non-hydrostatic gravity wave,
2. A balanced isothermal flow,
3. A baroclinic wave;
4. An updated Held-Suarez experiment (with tracer-support).
This PR addresses issue #1306, but we still need to sort out how we will test these experiments (similarly for the LES) in order to ensure we don't regress.
I have

Add GCM Benchmarks

---

src/Diagnostics/atmos_les_core.jl
src/Diagnostics/atmos_les_default.jl
src/Diagnostics/atmos_les_default_perturbations.jl
src/Diagnostics/atmos_refstate_perturbations.jl
src/Diagnostics/variables.jl

add les diagnostic variable attributes

---

src/Common/Thermodynamics/relations.jl
test/Common/Thermodynamics/runtests.jl

- Manually handle case when `T = T_freeze` in saturation adjustment.
Before this PR, the newly added test
```julia
_T_freeze = FT(T_freeze(param_set))
e_int_upper = internal_energy_sat.(Ref(param_set), Ref(_T_freeze + sqrt(eps(FT))), ρ, q_tot, phase_type)
e_int_lower = internal_energy_sat.(Ref(param_set), Ref(_T_freeze - sqrt(eps(FT))), ρ, q_tot, phase_type)
_e_int = (e_int_upper .+ e_int_lower)/2
ts = PhaseEquil.(Ref(param_set), _e_int, ρ, q_tot)
@test all(air_temperature.(ts) .== Ref(_T_freeze))
ts = PhaseEquil.(Ref(param_set), _e_int, ρ, q_tot, 8, FT(1e-1), MT.saturation_adjustment_SecantMethod)
@test all(air_temperature.(ts) .== Ref(_T_freeze))
```
fails in master for 432 cases (gist [here](https://gist.github.com/charleskawczynski/3d2f13ddbc3b63fb25896e5cc62cbdf1)), both in …

Handle freezing case in saturation adjustment

---

docs/src/APIs/Atmos/AtmosModel.md
src/Atmos/Model/bc_energy.jl
src/Atmos/Model/bc_moisture.jl
src/Atmos/Model/bc_momentum.jl
src/Atmos/Model/boundaryconditions.jl

clean up boundary conditions

---

docs/src/APIs/Numerics/DGMethods/NumericalFluxes.md
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/linear.jl
src/Numerics/DGMethods/NumericalFluxes.jl
test/Atmos/Model/discrete-hydrostatic-balance.jl
test/Numerics/DGMethods/Euler/isentropicvortex.jl

Add Roe flux

---

Project.toml

Update min julia project dependency to Julia 1.4
I have

Update min Julia to 1.4

---

experiments/AtmosGCM/GCMDriver/GCMDriver.jl
experiments/AtmosGCM/GCMDriver/baroclinicwave_problem.jl
experiments/AtmosGCM/GCMDriver/gcm_base_states.jl
experiments/AtmosGCM/GCMDriver/gcm_bcs.jl
experiments/AtmosGCM/GCMDriver/gcm_moisture_profiles.jl
experiments/AtmosGCM/GCMDriver/gcm_perturbations.jl
experiments/AtmosGCM/GCMDriver/gcm_sources.jl
experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl

Supports Baroclinic Wave and Held-Suarez problems with selectable perturbations, base states, moisture profiles and surface fluxes.
Makes it easier to add new problems.
I have

Modularized GCM driver

---

test/Atmos/Parameterizations/Microphysics/KM_ice.jl
test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl
test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl
test/Land/Model/test_bc.jl
test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
test/Ocean/ShallowWater/GyreDriver.jl
test/Ocean/ShallowWater/test_2D_spindown.jl
test/Ocean/SplitExplicit/split_explicit.jl
tutorials/Atmos/burgers_single_stack.jl
tutorials/Land/Soil/Water/equilibrium_test.jl
tutorials/Numerics/DGMethods/Box1D.jl

Rename step (intrinsic func)

---

.buildkite/pipeline.yml
docs/src/Theory/Atmos/EDMFEquations.md
src/Utilities/VariableTemplates/VariableTemplates.jl
test/Atmos/EDMF/Artifacts.toml
test/Atmos/EDMF/bomex_edmf.jl
test/Atmos/EDMF/bomex_edmf_regression_test.jl
test/Atmos/EDMF/closures/entr_detr.jl
test/Atmos/EDMF/closures/mixing_length.jl
test/Atmos/EDMF/closures/pressure.jl
test/Atmos/EDMF/closures/surface_functions.jl
test/Atmos/EDMF/closures/turbulence_functions.jl
test/Atmos/EDMF/edmf_kernels.jl
test/Atmos/EDMF/edmf_model.jl
test/Atmos/EDMF/helper_funcs/diagnose_environment.jl
test/Atmos/EDMF/helper_funcs/lamb_smooth_minimum.jl
test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
test/Atmos/EDMF/helper_funcs/save_subdomain_temperature.jl
test/Atmos/EDMF/helper_funcs/subdomain_statistics.jl
test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
test/Atmos/EDMF/helper_funcs/utility_funcs.jl

Adds the EDMF model for a BOMEX single stack driver.
We recently had things working on the GPU ~~but it's currently CPU-only. We'll fix the gpu capability in a subsequent PR~~, and we still do 🚀.
Co-authored with: @yairchn, @trontrytel, @ilopezgp, @jiahe23, @simonbyrne, @kpamnany, @jkozdon (and likely more, since I needed a lot of tangential advice on various things)
I have

Add EDMF model

---

.buildkite/pipeline.yml
.gitignore
docs/src/APIs/Driver/index.md
experiments/OceanSplitExplicit/simple_box.jl
src/Driver/ConfigTypes/ConfigTypes.jl
src/Driver/Driver.jl
src/Driver/SolverTypes/SolverTypes.jl
src/Driver/SolverTypes/SplitExplicitSolverType.jl
src/Driver/driver_configs.jl
src/Driver/solver_configs.jl
src/Ocean/SplitExplicit01/BarotropicModel.jl
src/Ocean/SplitExplicit01/OceanModel.jl
src/Ocean/SplitExplicit01/SplitExplicitLSRK2nMethod.jl
src/Ocean/SplitExplicit01/SplitExplicitModel.jl
test/Ocean/SplitExplicit/simple_box_ivd.jl
test/Ocean/SplitExplicit/split_explicit.jl
test/Ocean/SplitExplicit/test_simple_box.jl
test/Ocean/SplitExplicit/test_spindown_short.jl

See title. Draft for now. Main complication is dealing with a second balance, grid, and DGModel.
I have

Integrate Split-Explicit Solver into Driver.jl

---

docs/list_of_tutorials.jl
tutorials/Atmos/agnesi_hs_lin.jl
tutorials/Atmos/agnesi_nh_lin.jl
tutorials/Atmos/risingbubble.jl

1) Agnesi HS/ NHS problems - LaTeX formatting / typos fixed 
2) RTB - Links to documentation and page build, external links fixed
3) Add RTB to list_of_tutorials.jl
modified:   list_of_tutorials.jl
modified:   ../tutorials/Atmos/agnesi_hs_lin.jl
modified:   ../tutorials/Atmos/agnesi_nh_lin.jl
modified:   ../tutorials/Atmos/risingbubble.jl
I have

Tutorial documentation fixes 

---

docs/src/APIs/Atmos/AtmosModel.md
docs/src/APIs/BalanceLaws/BalanceLaws.md
docs/src/APIs/Utilities/VariableTemplates.md
src/Atmos/Model/AtmosModel.jl
src/BalanceLaws/interface.jl
src/BalanceLaws/state_types.jl
src/Numerics/DGMethods/DGModel.jl
src/Utilities/VariableTemplates/VariableTemplates.jl

Hopefully should make this clearer.
I have

improve docs for BalanceLaws

---

docs/src/Contributing.md

Add some additional documentation around test infrastructure  / definitions for end users.
I have

Add some additional information about test infastructure

---

Project.toml

Tag release 0.2.0

---

Project.toml

Bump version to 0.3.0-DEV

---

experiments/AtmosLES/bomex_les.jl

add CFL_direction = HorizontalDirection() and change CFLmax to 0.35 in bomex_les.jl
I have

add CFL direction in bomex_les.jl

---

test/Numerics/DGMethods/advection_diffusion/direction_splitting_advection_diffusion.jl

This PR changes the initial condition of `direction_splitting_advection_diffusion` test on the sphere. The new 
initial condition, in contrast to the old one, is a smooth function on the sphere. This helps with comparing results
of different discretizations on this test.
I have

Change direction splitting test initial condition

---

experiments/AtmosLES/bomex_les.jl
src/BalanceLaws/interface.jl
src/Ocean/SplitExplicit01/Continuity3dModel.jl

Applies the formatter to all files.
I have

Apply formatter globally

---

.buildkite/pipeline.yml
experiments/TestCase/baroclinic_wave.jl
experiments/TestCase/risingbubble.jl
experiments/TestCase/solid_body_rotation.jl

Add dycore test cases to one folder: experiments/TestCase/. Supersedes #1521 
- Move baroclinic_wave.jl from experiments/AtmosGCM/ to experiments/TestCase/ and make some minor changes
- Add risibingbubble.jl (but keep the risingbullel.jl in the tutorials/) and add a moist option
- Add solid_body_rotation.jl
I have

add dycore test cases

---

src/Common/Thermodynamics/relations.jl

At the moment, `saturation_adjustment` failures can occur because `find_zero` cannot find the root, or because `find_zero` searches for `T` for `T<0`, which results in `DomainError` (`saturation_vapor_pressure(T) ~ (T / _T_triple)^(Δcp / _R_v)`). Rather than implementing bracketing tooling in RootSolvers.jl, this PR effectively brackets temperature by applying `abs` to temperature in `find_zero` (and wraps the result in `abs`). The upside of this PR is that, IIUC, ThermodynamicState input parameters will now always be reported when convergence fails. Before this PR, ThermodynamicState input parameters are reported so long `DomainError` does not occur. This should help us more gracefully handle, and collect data for, non-converged saturation adjustment cases.
This is one more small step …

Apply abs to temperature in sat adjust

---

Manifest.toml
docs/Manifest.toml
docs/list_of_how_to_guides.jl
docs/src/APIs/Common/SurfaceFluxes.md
docs/src/HowToGuides/Common/UniversalFunctions.md
src/Common/SurfaceFluxes/SurfaceFluxes.jl
src/Common/SurfaceFluxes/UniversalFunctions.jl
test/Common/SurfaceFluxes/runtests.jl
test/Common/SurfaceFluxes/test_universal_functions.jl

There are more refactoring needs at the SurfaceFluxes module level, however, I'd like to reserve those changes for another PR, since this PR
- Refactors and modularizes the universal functions
- Moves UniversalFunction parameters to CLIMAParameters and updates CLIMAParameters version
- Adds verification plots to the universal functions docs, which appear to match the literature
- Adds @akshaysridhar's SurfaceFluxes test which compares computed fluxes with LES data.
Co-authored with @akshaysridhar.
I have

Refactor UniversalFunctions, add SurfaceFluxes test based on LES data

---

test/Atmos/Parameterizations/Microphysics/KM_ice.jl
test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl
test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl
test/Atmos/Parameterizations/Microphysics/KinematicModel.jl

This adds netcdf output to Kinematic Model tests for microphysics. 
I have

add netcdf output to Kinematic Model tests

---

.dev/climaformat.jl
src/Diagnostics/atmos_les_spectra.jl

Format src/Diagnostics/atmos_les_spectra.jl

---

.buildkite/pipeline.yml
src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
test/Atmos/Parameterizations/Microphysics/KM_ice.jl
test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl
test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl
test/Atmos/Parameterizations/Microphysics/KinematicModel.jl

This PR:
- updates the Kinematic Model ice test to take advantage of center coords from local geometry (thank you @jkozdon!)
- reduces the timestep in the above test and extends the stable simulation time to 1 hour
- cleans up the Kinematic Model tests to use more functions from Thermodynamics
- adds two additional guards against negative numbers to Microphysics module

Cleanup in Kinematic Model tests

---

test/Atmos/Parameterizations/Microphysics/KM_ice.jl

As described in issue https://github.com/CliMA/ClimateMachine.jl/issues/1668
Reducing temporarily test length to not block other PRs.

Reduce the ice test length

---

src/Utilities/SingleStackUtils/SingleStackUtils.jl

Fix index in reduce_nodal_stack (SingleStackUtils)

---

test/Numerics/DGMethods/advection_diffusion/pseudo1D_heat_eqn.jl

Since the CI doesn't run with
JULIA_CLIMA_INTEGRATION_TESTING=true
this was never hit before

Update errant number in `pseudo1D_heat_eqn.jl`

---

docs/list_of_tutorials.jl
tutorials/Land/Soil/Coupled/equilibrium_test.jl
tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
tutorials/Land/Soil/Water/equilibrium_test.jl

This PR utilizes the `dict_of_nodal_states` with interpolation in the land tutorials.
Will wait on #1674, which has some things we need.

Use `dict_of_nodal_states` in land tutorials

---

src/Driver/Callbacks/Callbacks.jl

This PR adds some info, efficiency (simtime / runtime) and estimated remaining wallclock time, to the Driver `@info` Update.

Add more info to driver Update

---

.dev/clima_formatter_default_image.jl
.dev/clima_formatter_image.jl
docs/src/DevDocs/CodeStyle.md
docs/src/DevDocs/SystemImage.md

- Adds scripts for building the system images for the julia formatter
- Adds examples for how to call the system image script for `ClimateMachine`

Update system image instructions

---

src/Numerics/Mesh/Interpolation.jl

1). Replaced separate CUDA and CPU kernels with KernelAbstractions kernels.
2). Enabled support for different polynomial orders in different
directions.

Interpolation -> KA kernels + Variable polynomial orders.

---

src/Driver/driver_configs.jl
test/Driver/driver_test.jl
test/Driver/gcm_driver_test.jl
test/Driver/mms3.jl

This PR is part of a series of PRs (see PR #1702 and PR #1741 ) to expand the DG kernels capability to support multiple degree polynomials in the horizontal and vertical directions. 
This PRcan be merged independently of the above mentioned PRs, as it only touches the Driver configurations.

Driver update: Variable polynomial order 

---

experiments/AtmosLES/dycoms.jl
experiments/AtmosLES/schar_scalar_advection.jl
src/Atmos/Model/atmos_tendencies.jl
src/Atmos/Model/source.jl
src/Atmos/Model/tendencies_momentum.jl
src/BalanceLaws/sum_tendencies.jl
tutorials/Atmos/agnesi_hs_lin.jl
tutorials/Atmos/agnesi_nh_lin.jl
tutorials/Atmos/heldsuarez.jl

This PR moves the RayleighSponge to the new tendency specification.

Move RayleighSponge to new tendency specification

---

.buildkite/pipeline.yml
experiments/AtmosLES/Artifacts.toml
experiments/AtmosLES/squall_line.jl
src/Atmos/Model/atmos_tendencies.jl
src/Atmos/Model/declare_prognostic_vars.jl

Added a working Squall line experiment using NonEquilMoist

Working Squall line with NonEquilMoist

---

docs/src/APIs/Land/LandModel.md
docs/src/APIs/Land/SoilWaterParameterizations.md
src/Land/Model/LandModel.jl
src/Land/Model/SoilWaterParameterizations.jl
src/Land/Model/soil_bc.jl
src/Land/Model/soil_heat.jl
src/Land/Model/soil_water.jl
src/Land/Model/source.jl
test/Land/Model/freeze_thaw_alone.jl
test/Land/Model/runtests.jl
test/Land/Model/test_water_parameterizations.jl
tutorials/Land/Soil/Water/equilibrium_test.jl

This code:
- adds in a model for freezing and thawing in soil. The model is of the form of a source term in the water and ice equations.  
In the future, we anticipate testing different methods for the source function, and so have made a "Source" abstract type, with concrete types that we can dispatch on in the land_source function.
- We have an integration test showing agreement with an analytic solution, and individual functions called by our source method have unit tests. 
- adjusts the maximum volumetric water content to be porosity - volumetric ice fraction. Previously it was equal to porosity, but when ice is present, there is less volume for liquid water to fill. The changes in soil_water.jl, soil_heat.jl, SoilWaterParameterizations.jl, and to the test_water_parameterizations.jl …

freeze thaw model

---

docs/Manifest.toml
docs/Project.toml

Update Documenter version, pin min version to support Buildkite deployment

---

test/Common/Thermodynamics/runtests.jl

This PR adds a few helpers to clean up some of the thermo tests.

Clean up thermo tests

---

experiments/AtmosLES/bomex_model.jl
experiments/AtmosLES/dycoms.jl
experiments/AtmosLES/squall_line.jl
experiments/AtmosLES/stable_bl_model.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/atmos_tendencies.jl
src/Atmos/Model/moisture.jl
src/Atmos/Model/source.jl
src/Atmos/Model/tendencies_moisture.jl

This PR moves some liquid and ice sources to the new tendency specification.

Move liq and ice sources to new tend spec.

---

docs/plothelpers.jl

This PR adds `sample_rate` as a kwarg to the `plothelper.jl` functions `export_plot` and `export_state_plots `. This PR also renames the local name `all_data` to `dons_arr`, as this is an array of `dict_of_nodal_states`.

Add `sample_rate` to plothelper funcs

---

src/Numerics/Mesh/Filters.jl
test/Numerics/Mesh/filter.jl

This is just an initial draft of the support for multiple polynomial orders in Filters, so that I can easily get people's feedback and guidance.

Poly order splitting in Filters

---

test/Driver/mms3.jl
test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl

Move MMS sources to new tendency specification.

Move MMS source tendencies to new specification

---

src/Diagnostics/diagnostic_fields.jl

Updating diagnostic_fields.jl to support different polynomial order in different directions.

---

src/Numerics/Mesh/Interpolation.jl

Updates Interpolation.jl to support zero-degree polynomial approximation in any direction within each spectral element.

 Interpolation.jl 0-degree polynomial support

---

.buildkite/pipeline.yml
experiments/AtmosLES/dycoms.jl

This PR adds a simple CI test for rain and moisture variables for LES dycoms case.

add simple rain CI checks

---

.buildkite/pipeline.yml
docs/bibliography.bib
docs/src/APIs/Atmos/AtmosModel.md
experiments/AtmosLES/Artifacts.toml
experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/lsforcing.jl
src/Numerics/DGMethods/DGModel.jl
src/Numerics/DGMethods/DGModel_kernels.jl

Co-authored-by: @akshaysridhar 
This PR:
- Adds the ability to read initial conditions and forcing from a netcdf file and use them to force the LES
- Adds a GCM-forced LES driver

Add GCM forced LES case

---

docs/src/APIs/Arrays/Arrays.md
src/Arrays/MPIStateArrays.jl
src/Driver/Callbacks/Callbacks.jl
src/Utilities/VariableTemplates/VariableTemplates.jl
src/Utilities/VariableTemplates/flattened_tup_chain.jl
test/Arrays/varsindex.jl
test/Utilities/VariableTemplates/test_complex_models.jl

Show more specific !isfinite error

---

docs/src/HowToGuides/Atmos/AtmosReferenceState.md
test/Atmos/EDMF/stable_bl_edmf.jl
test/Atmos/EDMF/stable_bl_edmf_implicit.jl
test/Atmos/Model/ref_state.jl
test/Land/Model/freeze_thaw_alone.jl
test/Land/Model/test_bc.jl
tutorials/Land/Heat/heat_equation.jl
tutorials/Land/Soil/Coupled/equilibrium_test.jl
tutorials/Land/Soil/Water/equilibrium_test.jl
tutorials/Numerics/DGMethods/Box1D.jl

Not sure what I was thinking calling a variable `all_data`. This changes `all_data` to `dons_arr` (array of dict of nodal states).

Change `all_data` to `dons_arr`

---

experiments/AtmosLES/bomex_model.jl
experiments/AtmosLES/convective_bl_model.jl
experiments/AtmosLES/stable_bl_model.jl

This PR
- (1) Moves bomex sources to new tendency specification
- (2) Moves convective BL sources to new tendency specification
- (3) Moves dry BL sources to new tendency specification
@ilopezgp do we have any tests hooked in for (2) and (3)?

Move bomex and convective/dry BL sources to new tend spec

---

experiments/AtmosGCM/GCMDriver/GCMDriver.jl
experiments/AtmosGCM/GCMDriver/gcm_sources.jl
experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl
experiments/AtmosGCM/heldsuarez.jl
src/Atmos/Model/tendencies_momentum.jl
tutorials/Atmos/heldsuarez.jl

Move sources in Held-Suarez to new tendency specification.

Move held suarez sources to new tend spec

---

.buildkite/pipeline.yml
docs/src/APIs/Atmos/AtmosModel.md
docs/src/HowToGuides/Atmos/PrecipitationModelChoices.md
docs/src/Theory/Atmos/Microphysics.md
docs/src/Theory/Atmos/Microphysics_0M.md
experiments/AtmosLES/dycoms.jl
experiments/AtmosLES/squall_line.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/atmos_tendencies.jl
src/Atmos/Model/bc_precipitation.jl
src/Atmos/Model/boundaryconditions.jl
src/Atmos/Model/get_prognostic_vars.jl
src/Atmos/Model/multiphysics_types.jl
src/Atmos/Model/precipitation.jl
src/Atmos/Model/source.jl
src/Atmos/Model/tendencies_energy.jl
src/Atmos/Model/tendencies_mass.jl
src/Atmos/Model/tendencies_moisture.jl
src/Atmos/Model/tendencies_precipitation.jl
src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
src/Diagnostics/atmos_les_default.jl
src/Diagnostics/variables.jl

This adds snow to Atmos interface
I still need to:

Let it snow

---

src/Numerics/Mesh/Interpolation.jl
test/Numerics/Mesh/interpolation.jl

Tests, which use different polynomial orders in horizontal and vertical directions, added.
Bugs, effecting interpolation code when different polynomial orders are
used in horizontal and vertical directions, are fixed.

Interpolation + vardeg tests + bug fix

---

src/Numerics/DGMethods/DGModel.jl

Fix pointwise_courant size for variable polynomial order

---

.buildkite/pipeline.yml
experiments/AtmosLES/bomex_les.jl
experiments/AtmosLES/dycoms.jl
src/Diagnostics/atmos_common.jl
src/Diagnostics/atmos_gcm_default.jl
src/Diagnostics/atmos_les_core.jl
src/Diagnostics/atmos_les_default.jl
src/Diagnostics/atmos_les_default_perturbations.jl
src/Diagnostics/atmos_refstate_perturbations.jl
src/Diagnostics/helpers.jl
src/Diagnostics/thermo.jl

Uses `Grids.basic_grid_info()` and `Topologies.basic_topology_info()` and thereby `grid_info.Nqk`, `grid_info.Nqh`, `grid_info.Nq`, `topl_info.nvertelem` and `topl_info.nhorzrealelem` in all the diagnostics groups that traverse the DG grid.

Update diagnostics groups to handle variable degrees

---

.buildkite/pipeline.yml
experiments/AtmosLES/squall_line.jl

This adds testing of different moisture and precipitation configurations to CI using squall line setup.
The tests are just a simple asserts at the end of a short run. Next up is adding squall line to QA.

add moisture and precipitation asserts to squall line CI

---

.buildkite/pipeline.yml
experiments/AtmosLES/stable_bl_model.jl
test/Atmos/EDMF/stable_bl_edmf.jl
test/Atmos/EDMF/stable_bl_single_stack_implicit.jl

In this branch the stable_bl_model file is corrected with the calls for EDMF source and BCs

update source and BC edmf calls in stable_bl_model.jl

---

experiments/AtmosLES/dycoms.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/moisture.jl
src/Atmos/Model/precipitation.jl
src/Atmos/Model/tendencies_energy.jl
src/Atmos/Model/tendencies_mass.jl
src/Atmos/Model/tendencies_moisture.jl
src/Atmos/Model/tendencies_momentum.jl
src/Atmos/Model/tendencies_precipitation.jl
src/Atmos/Model/tendencies_tracers.jl
src/Atmos/Model/tracers.jl
src/Common/TurbulenceConvection/TurbulenceConvection.jl
test/Atmos/EDMF/edmf_kernels.jl

This is the first-order flux counter-part to #1850.

Reformulate first order flux arguments, add precomputed NamedTuple

---

src/Driver/Driver.jl
src/Driver/driver_configs.jl
src/Driver/solver_configs.jl

A first attempt at adding the polynomial degrees as a CL option. 
This partially addresses #1641. 
Still to do:
cc: @kpamnany

Add polynomial degrees CL option

---

.buildkite/docs-pipeline.yml

force documenter previews on bors trying branches

---

experiments/AtmosLES/convective_bl_les.jl
experiments/AtmosLES/convective_bl_model.jl

This PR take the changes to convective_bl_model.jl from #1817 that do not effect the output of a test and adds them to master separately.

fix turb_source bug and set CBL_model similar to SBL_model

---

experiments/TestCase/baroclinic_wave.jl

Adds the spectrum diagnostics group to the baroclinic wave test case.

EKE power spectrum diagnostic for the baroclinic_wave test

---

experiments/AtmosGCM/GCMDriver/GCMDriver.jl

Fix for running GCMdriver.jl

---

src/Common/Spectra/power_spectrum_gcm.jl
src/Diagnostics/atmos_gcm_spectra.jl
test/Common/Spectra/gcm_standalone_visual_test.jl
test/Common/Spectra/runtests.jl

Small fix to update an offline test for the GCM spectrum diagnostic.

small update of an offline test

---

src/Driver/driver_configs.jl

Only print tendency table in `mpirank == 0`.

Show tendency table on rank 0

---

Project.toml
docs/Project.toml
docs/src/GettingStarted/Installation.md

Update Compat, and some docs, to julia 1.5.

Update compat to 1.5

---

src/InputOutput/VTK/writevtk.jl

Some small changes to `writevtk` so that all branches are exercised in `runtests.jl`.

Exercise all branches in writevtk

---

test/Common/Spectra/runtests.jl
test/Common/SurfaceFluxes/runtests.jl
test/Common/Thermodynamics/runtests.jl
test/Common/Thermodynamics/runtests_gpu.jl
test/InputOutput/VTK/runtests.jl
test/InputOutput/Writers/runtests.jl
test/Utilities/SingleStackUtils/runtests.jl
test/Utilities/TicToc/runtests.jl
test/Utilities/VariableTemplates/runtests.jl
test/Utilities/VariableTemplates/runtests_gpu.jl

This PR wraps some `runtests.jl` in modules. A step towards #1368.

Wrap some runtests in modules

---

test/Utilities/VariableTemplates/test_base_functionality.jl
test/Utilities/VariableTemplates/test_complex_models.jl
test/Utilities/VariableTemplates/varsindex.jl

Reviewing CodeCov, these added tests should help cover some parts of VariableTemplates that are not currently unit-tested.

Add some VariableTemplates tests

---

experiments/TestCase/solid_body_rotation_fvm.jl

This PR modifies solid_body_rotation_fvm.jl:
- Turn off grid stretching
- Change the lat lon grids in the diagnostics

modify solid body rotation driver

---

src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/get_prognostic_vars.jl
src/Atmos/Model/linear.jl
src/Atmos/Model/linear_atmos_tendencies.jl
src/Atmos/Model/linear_tendencies.jl
test/Atmos/EDMF/report_mse_bomex.jl
tutorials/Atmos/heldsuarez.jl

WIP. Transfers over atmos linear model tendencies to the new type specification.

Transfer over atmos linear model tendencies to new specification

---

src/Numerics/Mesh/Grids.jl

Since these aren't documented anywhere, it is useful to at least have comments

add comments on grid components

---

src/Diagnostics/Debug/StateCheck.jl

Bugfix for copy/paste output of StateCheck. Adds missing comma

Bugfix for StateCheck

---

src/Numerics/Mesh/Grids.jl

This PR adds minimum nodal distance to the grids, while keeping `min_node_distance` defined. So, calling `min_node_distance` now has significantly reduced overhead. I'm not sure if/what tests to add, but I'm pretty sure that everything should be fully exercised.

Add min nodal distance to DG grid

---

tutorials/BalanceLaws/tendency_specification_layer.jl

This PR:
- Silences some noisy output (`push!(LOAD_PATH, ".")`)
- Adds some `ref`s
- Adds/improve some description
- Improves some names
in the tendency specification layer tutorial

Small changes/improvements to tend layer docs tutorial

---

src/Numerics/Mesh/Filters.jl
tutorials/Numerics/DGMethods/Box1D.jl

Fix minor errata in filter comments.

Fix minor errata in comments

---

docs/bibliography.bib
docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
test/Numerics/ODESolvers/ode_tests_common.jl

Add DBM453 time stepper

---

src/Numerics/Mesh/Interpolation.jl

offset fixed for elements not containing interpolation points.

Bug fix for brick interpolation

---

experiments/AtmosLES/convective_bl_model.jl
experiments/AtmosLES/stable_bl_model.jl

Remove code duplication in sbl model.

Remove duplication in sbl model

---

src/Common/SurfaceFluxes/SurfaceFluxes.jl

This PR resolves issue #2068, by adding documentation of the exchange coefficient formulation, and making the formulation consistent with the SurfaceFluxes module. In particular,
- The new formulation is consistently applicable to both DG and FV discretization.
- The new formulation is general enough to capture any similarity-based vertical profile.

Fix and document get_flux_coefficients

---

src/Numerics/Mesh/BrickMesh.jl
src/Numerics/Mesh/Topologies.jl
test/Driver/mms3.jl
test/InputOutput/VTK/runtests.jl
test/Numerics/DGMethods/Euler/fvm_isentropicvortex.jl
test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model_1dimex_bgmres.jl
test/Numerics/DGMethods/advection_diffusion/direction_splitting_advection_diffusion.jl
test/Numerics/DGMethods/advection_diffusion/fvm_advection.jl
test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion.jl
test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion_model_1dimex_bjfnks.jl
test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion_periodic.jl
test/Numerics/DGMethods/advection_diffusion/fvm_swirl.jl
test/Numerics/DGMethods/advection_diffusion/periodic_3D_hyperdiffusion.jl
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion.jl
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_mrigark_implicit.jl
test/Numerics/DGMethods/advection_diffusion/pseudo1D_heat_eqn.jl
test/Numerics/DGMethods/advection_diffusion/variable_degree_advection_diffusion.jl
test/Numerics/DGMethods/courant.jl
test/Numerics/DGMethods/grad_test.jl
test/Numerics/DGMethods/horizontal_integral_test.jl
test/Numerics/DGMethods/integral_test.jl
test/Numerics/DGMethods/vars_test.jl
test/Numerics/Mesh/mpi_connect.jl
test/Numerics/Mesh/mpi_connect_ell.jl
test/Numerics/Mesh/mpi_connect_sphere.jl
test/Numerics/Mesh/mpi_connect_stacked.jl
test/Numerics/Mesh/mpi_connect_stacked_3d.jl
test/Numerics/Mesh/topology.jl
test/Numerics/SystemSolvers/bandedsystem.jl

Make connectmeshfull default for use with both DG and CG.

Make connectmeshfull default for DG and CG.

---

.buildkite/docs-pipeline.yml
docs/bibliography.bib
docs/list_of_tutorials.jl
tutorials/Atmos/risingbubble.jl
tutorials/Numerics/TimeStepping/explicit_lsrk.jl
tutorials/Numerics/TimeStepping/imex_ark.jl
tutorials/Numerics/TimeStepping/mis.jl
tutorials/Numerics/TimeStepping/multirate_rk.jl
tutorials/Numerics/TimeStepping/ts_intro.jl
tutorials/Numerics/TimeStepping/tutorial_acousticwave_config.jl
tutorials/Numerics/TimeStepping/tutorial_risingbubble_config.jl

This PR adds some Time Stepping tutorials. The aim is for the users/learners to learn about the different Time Steppers/Integrators available in the ClimateMachine and their different properties and usage.

Time Stepping tutorials

---

src/Utilities/SingleStackUtils/single_stack_diagnostics.jl

Fix merged NamedTuples in single_stack_diagnostics

---

src/Utilities/SingleStackUtils/SingleStackUtils.jl

Fix identity operation in reduce_nodal_stack

---

docs/src/Contributing.md

This will close #1972 
It adds some additional git instructions and useful tips to our contributing guide.

Docs: Add some useful git tips to the Contributing guide

---

.github/workflows/Coverage.yaml
.github/workflows/Documenter.yaml
.github/workflows/JuliaFormatter.yml
.github/workflows/Linux-UnitTests.yml
.github/workflows/OS-UnitTests.yml

Julia 1.5.4 includes bufixes that fix building a system image.
closes #1952

Update github actions to use Julia 1.5.4

---

tutorials/Atmos/burgers_single_stack_bjfnk.jl
tutorials/Atmos/burgers_single_stack_fvm.jl

This PR fixes Burgers tutorials plotting problems due to common naming between output files (issue #2119 )

Fix Burgers tutorials plotting (issue 2119)

---

docs/src/GettingStarted/Atmos.md
docs/src/HowToGuides/Atmos/MoistureAndPrecip.md
experiments/AtmosGCM/GCMDriver/GCMDriver.jl
experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
experiments/AtmosLES/bomex_model.jl
experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
experiments/AtmosLES/convective_bl_model.jl
experiments/AtmosLES/dycoms.jl
experiments/AtmosLES/squall_line.jl
experiments/AtmosLES/stable_bl_model.jl
experiments/AtmosLES/surfacebubble.jl
experiments/TestCase/baroclinic_wave.jl
experiments/TestCase/baroclinic_wave_fvm.jl
experiments/TestCase/risingbubble.jl
experiments/TestCase/risingbubble_fvm.jl
src/Atmos/Model/AtmosModel.jl
src/Atmos/Model/moisture.jl
src/Common/Thermodynamics/states.jl
test/Atmos/prog_prim_conversion/runtests.jl
test/Numerics/DGMethods/Euler/isentropicvortex.jl
test/Numerics/DGMethods/Euler/isentropicvortex_lmars.jl

Closes #2108.
This PR technically changes the behavior of the drivers, so I'm wondering if we should adjust the drivers so that this PR is a no-op.

Synchronize maxiter and temperature tolerance between EquilMoist and PhaseEquil

---

Manifest.toml
docs/Manifest.toml

Upgrade some packages (`add GPUCompiler; up GPUCompiler; rm GPUCompiler`)

---

src/Numerics/Mesh/Elements.jl
test/Numerics/Mesh/Elements.jl

Add a function for computing Jacobi polynomials.

Add a function wrapper for Jacobi polynomials.

---

tutorials/Atmos/risingbubble.jl

correct paraviev link

---

docs/bibliography.bib
tutorials/Atmos/agnesi_hs_lin.jl
tutorials/Atmos/agnesi_nh_lin.jl

This PR moves the `giraldoRestelli2008a` citations to the .bib file.

Move citation to .bib

---

README.md

This quick PR updates the top-level README with Zenodo's DOI badge for the repository.

README: Add Zenodo DOI's badge
