CliMA/ClimateMachine.jl

- src/CLIMA-atmos/Dycore/src/gpu.jl
The numerical flux on the GPU is shared between dimensions so we use
the dimension `dim` to select the direction of gravity.
> [AtmosDycore] Fix gravity in gpu numerical flux

- src/PlanetParameters/src/PlanetParameters.jl
In the PlanetParameters `T_trip` in the definition of `T_0` should be `T_triple`
> Typo in PlanetParameters

- src/CLIMA-atmos/Dycore/src/CLIMAAtmosDycore.jl
- src/CLIMA-atmos/Dycore/src/gpu.jl
Moving the necessary reshape for the gpu to right before the kernel invocation (removes unnecessary duplicate pointer)
> [AtmosDycore] Removing d_QC, d_rhsC, and d_vgeoC

- src/CLIMA-atmos/Dycore/README.md
In the line on building MPI there should be backslashes with the double
quotes for building MPI.
> [AtmoDycore] Fixing README.md with MPI

- src/CLIMA-atmos/Dycore/src/types.jl
There was an erroneous definition of `inittimestate!` in `types.jl`
> [AtmosDycore] Removing erroneous `inittimestate!`

- src/CLIMA-atmos/Dycore/drivers/isentropic_vortex.jl
- src/CLIMA-atmos/Dycore/drivers/rising_thermal_bubble.jl
- src/CLIMA-atmos/Dycore/src/GenericCallbacks.jl
Ensure that all ranks call a wall time callback.  Before only some ranks
would call the callback and some would execute the next step.  When this
happened a reduction (e.g, L2 error calculation) in the callback would
cause a deadlock.
> [AtmosDycore] Fix deadlock in wall time callback

- src/CLIMA-atmos/Dycore/TODO.md
- src/CLIMA-atmos/Dycore/drivers/tracers_test.jl
- src/CLIMA-atmos/Dycore/src/GenericCallbacks.jl
- src/CLIMA-atmos/Dycore/src/VanillaEuler.jl
- src/CLIMA-atmos/Dycore/src/VanillaEuler_cuda.jl
This primarily implements tracers and moist variables for the AtmosDycore on both the CPU and GPU. Right now the moist variables have no physics and are just passively advected. As a test we make sure that if the tracers are initialized to be the scaled density that they remain this through out the simulation.
A few other things that are caught up in commits with this pull-request:
- In `VanillaEuler` the  Euler state variable storage order now matches the input function ordering
- In `VanillaEuler` the `facerhs!` on the CPU is now unified for 2- and 3-D
- In `GenericCallbacks` there is a comment fix for `EveryXWallTimeSeconds`
- In `VanillaEuler` an unneeded `MJI` array is removed on the CPU
- In `VanillaEuler` some postscript `L` are removed in the device arrays for the GPU kernel …
> [AtmosDycore] Implementation of tracers and (passive) moist variables

- src/CLIMA-atmos/Dycore/drivers/isentropic_vortex.jl
- src/CLIMA-atmos/Dycore/drivers/rising_thermal_bubble.jl
- src/CLIMA-atmos/Dycore/drivers/tracers_test.jl
- src/CLIMA-atmos/Dycore/src/LSRK.jl
- src/CLIMA-atmos/Dycore/src/VanillaEuler.jl
- src/CLIMA-atmos/Dycore/src/types.jl
In the AtmosDycore I had originally set up the accessor functions to use
`getindex` and `setindex!`, but this is out of line with the julia
coding style, so we are switching to using straight accessors and member
access.
> [AtmosDycore] Remove `getindex` and `setindex!`

- src/CLIMA-atmos/Dycore/src/VanillaEuler.jl
In the CPU kernels the viscosity was being set on the tracers and not
the moisture variables
@lcw please confirm this is the correct fix
> [AtmosDycore] Bug fix for viscosity on CPU

- .travis.yml
This is a tempory fix for \#90 related to currently nightly and Canary dependency. Now we create the "Build path" for Canary before testing.
> Temporary fix for #90 travis build issue with nightly

- src/ClimaAtmos/Dycore/src/AtmosStateArrays.jl
- src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations.jl
- src/ClimaAtmos/Dycore/src/vtk.jl
This uses underscore where the return values are unused.  This address the comment @simonbyrne had on https://github.com/climate-machine/CLIMA/pull/97.
> Use _ for unused return values

- src/Arrays/MPIStateArrays.jl
host_recvQ was getting set to hold numsendelem and not numrecvelem
> Fixing host_recvQ in MPIStateArrays

- src/Mesh/Topologies.jl
In this case the element is both the top and bottom, so we cannot use an `elseif` check to set the boundary conditions
> Bug fix for StackedBrickTopology when stacksize==1

- Manifest.toml
- env/gpu/Manifest.toml
> Update Canary to fix `Allreduce` warning

- src/Utilities/MoistThermodynamics/src/MoistThermodynamics.jl
- pressure was missing in the wrapper
function call to virt_pottemp, so
it was added.
- specific_volume wrapper was changed to compute
specific volume using the specific_volume function,
which takes into account q_tot.
> [MoistThermo] Fixed functions wrappers

- src/Mesh/Topologies.jl
- src/Mesh/test/mpi_connect_sphere.jl
Brick mesh uses `boundary` as its keyword argument for boundary conditions so unifying StackedCubedSphereTopology to do the same
> Change `bc` to `boundary` in sphere topology

- src/DGmethods/DGBalanceLawDiscretizations.jl
- src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
- src/DGmethods/NumericalFluxes.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_aux.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_bc.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_source.jl
- src/DGmethods/test/util/grad_test.jl
Several things happening here:
- inviscid_X -> X (since function will be inviscid + some viscous). All
these function now get passed the viscous state as well
- Qgrad -> QV (for Q viscous flux state)
- adding some more callbacks and sizes needed for viscous handling
(nviscstate, nviscfluxstate, viscous_transform!, viscous_flux!,
viscous_numerical_flux!, viscous_boundary_numerical_flux!)
> [BL] Refactor of inviscid in prep for viscous

- src/Atmos/Dycore/test/rising_thermal_bubble.jl
- src/Atmos/Dycore/test/tracers_test.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_aux.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_bc.jl
- src/DGmethods/test/Euler/isentropic_vortex_standalone_source.jl
- src/DGmethods/test/Sphere/advection_sphere.jl
- src/DGmethods/test/compressible_Navier_Stokes/mms_bc.jl
- src/DGmethods/test/conservation/sphere.jl
When `NullLogger` is used for non-root logging, MPI calls in log records are optimized away resulting in deadlock. Using `devnull` avoids this problem.
This should fix some of the recent test timeouts
> use devnull and not NullLogger for non-root MPI logging

- .gitlab-ci.yml
Since we currently pass on the gitlab nightly CI, I recommend removing the allow_failures
cc: @lcw @simonbyrne @charleskawczynski @vchuravy
> Remove allow_failure on nightly with gitlab

- docs/src/Atmos/TurbulenceConvection.md
- src/Atmos/Parameterizations/TurbulenceConvection/Grids/GridOperators.jl
- src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/BoundaryConditions.jl
- src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/StateVecFuncs.jl
- src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/StateVecs.jl
- test/Atmos/Parameterizations/TurbulenceConvection/Grids.jl
This PR:
- Fixes 1st order gradient operators and their tests
- Adds documentation to boundary conditions
- Adds new grid operators
- Adds @inbounds to some loops
- Improves / changes defaults in `StateVec` print / export
- Adds Neumann BC tests to documentation
> [TurbConv] Many improvements in Grids / StateVecs

- src/Arrays/MPIStateArrays.jl
- src/ODESolvers/LowStorageRungeKuttaMethod.jl
As discussed in https://github.com/climate-machine/CLIMA/pull/237#issuecomment-495392923 we do not need to be filling MPIStateArrays with zeros by default.
> Removing default zeroing of MPIStateArray

- .slurmci/gpu-test.sh
- test/Utilities/RootSolvers/runtests.jl
- test/runtests_gpu.jl
Only test what is actually GPU-enabled. Should help avoid timeout issues.
> Reduce GPU tests

- .gitignore
- .slurmci/jobs.jl
- examples/DGmethods/ex_003_acoustic_wave.jl
- src/DGmethods/DGBalanceLawDiscretizations.jl
- src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
- src/Mesh/Grids.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc.jl
- test/DGmethods/runtests.jl
- test/DGmethods/sphere/advection_sphere_lsrk.jl
- test/DGmethods/sphere/advection_sphere_ssp33.jl
- test/DGmethods/sphere/advection_sphere_ssp34.jl
This adds the acoustic wave test case of [Tomita and Satoh (2004)](https://doi.org/10.1016/j.fluiddyn.2004.03.003) to the balance law examples.
This also includes the skew-form metric treatment from #262
@tapios and @charleskawczynski  these use the moist thermodynamics routines so it would be great to get your review on the file `examples/DGmethods/ex_003_acoustic_wave.jl` concerning the use of this functionality
> Adding acoustic wave on sphere balance law example

- src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl
- src/Utilities/MoistThermodynamics/MoistThermodynamics.jl
- src/Utilities/RootSolvers/RootSolvers.jl
Key word arguments can prevent functions from being inlined when run in a
GPU kernel.  For this reason, we remove the keyword arguments from
`find_zero`.
> Remove kwargs from find_zero

- docs/src/Atmos/Microphysics.md
- docs/src/Utilities/MoistThermodynamics.md
- src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
- src/Utilities/MoistThermodynamics/MoistThermodynamics.jl
- src/Utilities/MoistThermodynamics/states.jl
- src/Utilities/PlanetParameters/PlanetParameters.jl
- test/Atmos/Parameterizations/Microphysics/runtests.jl
- test/Utilities/MoistThermodynamics/runtests.jl
To make naming more consistent among different modules I suggest to:
-  use \rho_water and \rho_ocean for water density. (We already use \rho for air density.)
- use q_vap_saturation instead of saturation_shum for saturation specific humidity. (We use q_ to denote specific humidities of our tracers)
> Names cleanup

- examples/DGmethods/ex_001_periodic_advection.jl
- src/DGmethods/DGBalanceLawDiscretizations.jl
- src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
- test/DGmethods/Euler/isentropic_vortex_standalone.jl
- test/DGmethods/util/filter_test.jl
Sometimes there was an aux array passed to the initial condition function and sometimes not. Since all realistic use case have aux state, we might as well always pass it.
> [BL] Unify aux treatment in init of MPIStateArray

- src/DGmethods/DGBalanceLawDiscretizations.jl
- src/DGmethods/DGBalanceLawDiscretizations_kernels.jl
- test/DGmethods/compressible_Navier_Stokes/dycoms.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc.jl
- test/DGmethods/compressible_Navier_Stokes/rtb_visc.jl
- test/LinearSolvers/poisson.jl
- test/profiling/DGmethods/CNS.jl
Based on how I have seen things being used, I think that removing the `states_for_gradient_transform` from the balance law solver will simplify things (and unify the interface).
cc: @lcw @asraero @simonbyrne @smarras79
> [BL] Remove states_for_gradient_transform

- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- src/DGmethods/NumericalFluxes.jl
- test/DGmethods/Euler/isentropic_vortex_standalone.jl
- test/DGmethods/Euler/isentropic_vortex_standalone_aux.jl
- test/DGmethods/Euler/isentropic_vortex_standalone_bc.jl
- test/DGmethods/Euler/isentropic_vortex_standalone_integral.jl
- test/DGmethods/Euler/isentropic_vortex_standalone_source.jl
- test/DGmethods/compressible_Navier_Stokes/dycoms.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc.jl
- test/DGmethods/compressible_Navier_Stokes/rtb_visc.jl
- test/DGmethods/sphere/advection_sphere_lsrk.jl
- test/DGmethods/sphere/advection_sphere_ssp33.jl
- test/DGmethods/sphere/advection_sphere_ssp34.jl
- test/profiling/DGmethods/CNS.jl
- test/profiling/DGmethods/Euler.jl
Based on how I have seen things being used, I think that removing the `preflux` from the balance law solver will simplify things (and unify the interface).
cc: @lcw @asraero @simonbyrne @trontrytel @smarras79
> [BL] Remove preflux from flux computations

- src/Atmos/Model/moisture.jl
- Made the `DryModel` use `PhaseDry`
- Removed unecessary function call to `get_phase_partition`
- Removed `get_phase_partition` wrapper for `PhaseDry`
> Made DryModel use PhaseDry

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
Meant to use `PhaseDry` for the second definition, which short-circuits to `liquid_ice_pottemp`. Fixes warning.
> Fixed redefinition of `liquid_ice_pottemp_sat`

- src/Atmos/Model/AtmosModel.jl
Related to moisture.jl, turbulence.jl 
1) Fix MoistEquil -> EquilMoist
2) Export SmagorinskyLilly
https://github.com/climate-machine/CLIMA/blob/2f215bf9b6dd20fadee0c5f79d6a08bfa4446eb5/src/Atmos/Model/moisture.jl#L53
> Fix: moisture model + turbulence export

- src/Utilities/VariableTemplates/VariableTemplates.jl
also use .= instead of = for assigning matrices
Fixes #392.
> use inbounds in VariableTemplates

- src/Atmos/Model/AtmosModel.jl
This removes `UM`, `VM`, and `WM` from the boundary condition.
> Remove unused variables from AtmosModel

- examples/DGmethods/ex_001_dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/radiation.jl
- src/Atmos/Model/turbulence.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
Reduces the assumptions on the moisture model, and also avoids the need for updating the mms test case for the time being.
Also changes the order of `diffusive!` calculations so that SmagorinskyLilly usese the most recent gradient. As a result, this affects the DYCOMS tolerance. cc @asraero @smarras79 
Supersedes #413.
> AtmosModel: move total specific enthalpy to top level

- examples/DGmethods/ex_001_dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/DGmethods/DGmethods.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/balancelaw.jl
- src/DGmethods_old/DGBalanceLawDiscretizations.jl
- src/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/ODESolvers/LowStorageRungeKuttaMethod.jl
- src/ODESolvers/ODESolvers.jl
- src/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/compressible_Navier_Stokes/density_current-model.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl
- test/DGmethods/compressible_Navier_Stokes/mms_model.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/DGmethods/compressible_Navier_Stokes/rising_bubble-model.jl
- test/DGmethods/integral_test.jl
- test/DGmethods/integral_test_sphere.jl
- test/DGmethods_old/Euler/RTB_IMEX.jl
- test/DGmethods_old/Euler/isentropic_vortex_standalone_IMEX.jl
- test/LinearSolvers/poisson.jl
- test/ODESolvers/runtests.jl
- test/Ocean/shallow_water/GyreDriver.jl
Removes the `params` from the ODE solver interface and merges previously stored data into the `DGmodel`.
The `params` was complicating the ODE interface when multiple balance laws are needed (e.g., IMEX and multirate). The interface I added should also simplify the sharing of `auxstate` and `diffstate` (which is really just scratch space) between different DGmodels
> Remove the param structure of the ODE solver

- src/ODESolvers/LowStorageRungeKuttaMethod.jl
- test/ODESolvers/runtests.jl
Using an Euler timestepper allows us to easily compare the results of the code against analytical / by-hand numbers for small numbers of time steps. Should never be used in a production run, but can be very useful for seeing exactly what the DGmethod kernels are computing.
> implement Euler timestepping for debugging

- bors.toml
There has been a bit of a backlog on the cluster recently meaning jobs are timing out. This should hopefully let them finish.
> Increase bors timeout to 1 day

- src/DGmethods/DGmodel_kernels.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl
The current way we treat metric terms for 2nd order derivatives is funky. This approach is a little more standard, and respects the symmetry of the operator.
> Symmetric treatment of metrics for 2nd derivatives

- slurmci-test.toml
pseudo1D_advection_diffusion.jl is currently failing. This was previously hidden by #523, but now that is fixed tests are broken.
> Disable failing integration test

- azure-pipelines.yml
We are seeing occasional Azure Pipelines failures on MacOS, e.g.:
https://dev.azure.com/spjbyrne/CLIMA/_build/results?buildId=1504&view=logs&jobId=93056758-5bfb-5750-f113-e720ddefdb4c&taskId=c73b3de0-27be-598b-c922-0c24c64f8585&lineStart=324&lineEnd=333&colStart=1&colEnd=1
According to https://stackoverflow.com/a/31222970/392585, this can be fixed by manually adding the current hostname to /private/etc/hosts
Also remove cmake and gfortran build dependencies as they are no longer required.
> Azure: attempt to fix occasional Mac build failures

- docs/src/Common/MoistThermodynamics.md
- examples/DGmethods/ex_001_dycoms.jl
- examples/DGmethods/ex_002_IOstrings.jl
- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/states.jl
- src/Common/PlanetParameters/PlanetParameters.jl
- test/Common/MoistThermodynamics/runtests.jl
Adds consistency tests to `ThermoDynamicState` constructors:
- Tests that getter functions return the same value as input arguments to the thermo state.
@tapios 10 of these tests are failing (related to pressure and liquid-ice potential temperature), and I may need your help in resolving some of these tests. This is likely the issue that @smarras79, @slifer50 is running into with initial conditions prescribed by liquid ice potential temperature.
> Add MoistThermo constructor consistency tests

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
Subtracting `q_v_sat` in `saturation_adjustment` is causing convergence issues in #529, so it's being removed here.
> Undo subtraction of `q_v_sat` in `saturation_adjustment`

- slurmci-test.toml
- test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
Fix Float32 for the advection diffusion test so that integration testing can be enabled.
See #526
> Fix Float32 for pseudo1D_advection_diffusion test

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/remainder.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- test/DGmethods/integral_test.jl
- test/DGmethods/integral_test_sphere.jl
Our current call to `update_aux!` only allows one to use state and auxiliary variables during the function call. Since `auxstate` and `diffstate` are now members of the `DGModel` struct, I'd like to access them this way instead of being passed in as arguments. This would be very useful for the ocean model (PR #535) which needs to access the gradient variables during the `update_aux!` call. 
I'm not 100% happy with the current implementation, as it requires the function passed into `nodal_update_aux!` to always take all three arrays as arguments, but this is still fewer changes than passing the gradient variables as an argument in `update_aux!`. Please give suggestions if you can think of a better way to do this. This is also partially future-proofing for when we add an integral state to …
> Make arguments to update_aux! more general

- azure-pipelines.yml
- docs/src/Atmos/TurbulenceConvection.md
- docs/src/Common/MoistThermodynamics.md
- docs/src/DGmethods_old.md
- Fixes broken `NumericalFluxes_old` docs.
- Removes reference to missing docs for `faceviscterms!` and `volumeviscterms!`
- Fixes and removes broken docs in `TurbulenceConvection`
- The tests in `TurbulenceConvection` are duplicated from what's in the test folder, so I don't think it has much value in the docs
> Fix broken docs

- src/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/ODESolvers/AdditiveRungeKuttaMethod_kernels.jl
- test/ODESolvers/runtests.jl
Seems to decrease the number of iterations of GMRES by half at the cost of storing `Nstages - 1` extra vectors. I don't have a good theory why this works, only some hand-wavy arguments. Maybe worth checking if it changes anything for https://github.com/climate-machine/CLIMA/pull/505 @jkozdon
> Reformulate ARK timesteppers

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- test/Common/MoistThermodynamics/runtests.jl
- Fixes/cleans up some docs
- Removes saturation adjustment from export, as this should not be called from outside of MoistThermo
> Fix docs, remove sat adjust from export

- examples/Atmos/heldsuarez.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- src/InputOutput/VTK/writevtk.jl
- src/LinearSolvers/ColumnwiseLUSolver.jl
- src/Mesh/Filters.jl
- src/Mesh/Filters_kernels.jl
- src/Mesh/Grids.jl
- src/Mesh/Grids_kernels.jl
- test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
- test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
- test/DGmethods_old/util/filter_test.jl
- test/LinearSolvers/bandedsystem.jl
- test/Mesh/min_node_distance.jl
This adds a function that approximates the minimum node distance for a given grid in the horizontal and / or vertical directions of the reference element.  In addition, the way direction is specified for the filter is changed to match that of the DGmodel.  This addressed issue #573.
> Add minimum node distance function

- examples/Microphysics/ex_1_saturation_adjustment.jl
- src/Atmos/Model/boundaryconditions.jl
- src/Atmos/Model/moisture.jl
- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/states.jl
- test/Common/MoistThermodynamics/runtests.jl
- test/DGmethods_old/compressible_Navier_Stokes/MWE_grid_stretching.jl
Fixes #353,
Specifically, I think it makes sense to have the same order of arguments in `PhaseDry` as `PhaseEquil`, so that the argument list of `PhaseEquil` extends that of `PhaseDry`, rather than swapping the order of density and specific total humidity.
> Pass args in similar order

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- test/Common/MoistThermodynamics/runtests.jl
This adds the quadratic term in the Taylor expansion for temperature in `air_temperature_from_liquid_ice_pottemp `. The previous version (with only the linear term, but not quadratic) fails the test that has been added (and is passing with the quadratic term).
Closes #567
> Add quadratic term to air temperature Taylor expansion

- src/Atmos/Model/AtmosModel.jl
Extends arguments for `init_state!`, since we'll need [many additional arguments](https://github.com/climate-machine/CLIMA/pull/601/files#diff-30c477a58b9368ed896dc001fedda8f8R57) in the Squal line setup. Hopefully, this will limit how many files #601 touches.
> Extend init args

- slurmci-test.toml
This is timing out, and also consuming large amounts of memory. Once we can simplify this we can reopen
> Disable advection diffusion 1d imex integration test

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- src/Ocean/Model/HydrostaticBoussinesqModel.jl
- test/DGmethods/integral_test.jl
- test/DGmethods/integral_test_sphere.jl
- test/Ocean/Hydrostatic_Boussinesq/simple_box.jl
I implemented a second `update_aux!` function with access to the gradients computed at the current time step as discussed in #565 and #535. 
This also allowed me to remove the VerticalSupplementModel from the HydrostaticBoussinesqModel as we now have access to the partial derivatives used to compute the horizontal divergence of the velocity vector.
> Add `update_aux_diffusive!` and remove VSModel from HBModel

- src/Diagnostics/Diagnostics.jl
This will make sure that diagnostics will use the same `ThermodynamicState` as the solver, determined by its `MoistureModel`.
> Update `compute_thermo` in diagnostics to use balance law

- src/Atmos/Model/moisture.jl
- src/Common/MoistThermodynamics/states.jl
- test/Common/MoistThermodynamics/runtests.jl
- Adds `maxiter` to `EquilMoist`
- Reorders `maxiter` and `tol` to protect against bug fix caught in #632
This was added so that `EquilMoist(5)` can be used for the DYCOMS driver in #597 without changing the default `maxiter` in saturation adjustment, based on discussions in #636.
The `maxiter` in `EquilMoist` should probably be reverted at some point since there will be two default `maxiter`'s (one in `states.jl`, and another in `moisture.jl`), which is not an ideal design.
> Add `maxiter` to `EquilMoist`, reorder (`tol,maxiter`)

- docs/src/Atmos/SurfaceFluxes.md
- src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl
- src/Mesh/BrickMesh.jl
- src/Mesh/Topologies.jl
Hello :-)
The DOI Foundation [started recommending a new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). While their URL change may be a bit ironic, it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old `dx` subdomain is being redirected. So, there is no urgency here.
However, for consistency, this PRs suggests to update all static DOI links accordingly.
Cheers!
> Hyperlink DOIs to preferred resolver

- azure-pipelines.yml
Apparently this triggered an abuse detector, which killed our previous CI setup
https://developercommunity.visualstudio.com/content/problem/892178/tf24668-the-following-team-project-collection-is-s-2.html
Hopefully this works?
> Azure: disable modification of hosts

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- test/Common/MoistThermodynamics/runtests.jl
I noticed that this equation is being manually implemented, and assuming `ice` is zero in some places, so I'm adding a function to replace existing implementation.
> Add `vapor_specific_humidity`

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/turbulence.jl
This would help with diagnosing issues at the intersection of numerics and turbulence models by
allowing creation of simpler test cases, e.g. isotropic decaying turbulence.
> Allow turbulence models with NoOrientation

- src/Common/MoistThermodynamics/states.jl
Since we've been having issues with `q_tot` not satisfying `0 <= q_tot <= 1`, let's force this constraint upon creating a thermo state for the default constructor.
Note that this does not apply to the initial conditions if defined with a different constructor (e.g., liquid ice potential temperature)
> Bound `q_tot` in thermo state

- experiments/GCM/heldsuarez.jl
- experiments/LES/dycoms.jl
- src/Driver/Configurations.jl
Otherwise it's impossible to specify time-stepper in IMEX without setting `linear_model` and `linear_solver` first.
> Fix keyword arguments in SolverTypes

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
Total specific humidity is not a property of `ts` for non-equilibrium thermodynamic states, so let's call `total_specific_humidity`.
> Fix MoistThermo bug

- src/Driver/Driver.jl
@kpamnany 
Minor fixes to `Driver.jl`
1) Allow `flattenednames`,`vars_names`, `vars_aux` to be used within `Driver.jl`
2) Fix `cbdiagnostics` -> `cbvtk` in field-dump callback.
> Output callback + function access within `src/Driver.jl`

- Manifest.toml
- Project.toml
- src/Arrays/CMBuffers.jl
- src/Arrays/MPIStateArrays.jl
- test/Arrays/mpi_comm.jl
We recently discussed what would be needed to implement support for CUDA-aware MPI.
This is an early prototype I was working on.
> implement different bufferkinds for CUDA-aware MPI

- src/Driver/Configurations.jl
- src/Driver/Driver.jl
This PR changes the default linear solver in `IMEXSolverType` to `ManyColumnLU`. This is a better
default since `SingleColumnLU` won't work on the sphere. This also fixes a bug where the linear solver specified in `solver_type` was not used.
> Change default linear solver in IMEXSolverType to ManyColumnLU

- test/Utilities/RootSolvers/runtests.jl
- test/Utilities/RootSolvers/runtests_gpu.jl
The RootSolvers runtests include CPU and GPU tests, but they should be split. I'm not adding this to the GPU test just yet (it wasn't ever running anyway), but I don't want to discard the code since I've run it locally in the past.
Closes #698
> Split RootSolvers CPU/GPU tests

- experiments/Atmos_GCM/heldsuarez.jl
- src/Driver/Configurations.jl
Apply `FT` when using the global constants. Fixes #713.
> Small Held-Suarez fix

- slurmci-test.toml
- src/DGmethods/DGmodel_kernels.jl
- test/DGmethods/Euler/isentropicvortex-imex.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/advection_diffusion/direction_splitting_advection_diffusion.jl
- test/DGmethods/advection_diffusion/pseudo1D_advection_diffusion.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_dgmodel.jl
This adds a test for horizontal/vertical splitting in the box and on the sphere using advection-diffusion
equation. It also removes split treatment of metric terms in `volumerhs`, which caused some small inconsistencies in the splitting that could become important as we move towards actually solving equations in the horizontal/vertical (as opposed to only using it for 1D IMEX where this didn't seem to matter).
> Test horizontal/vertical splitting and remove skew symmetric

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/Atmos_GCM/heldsuarez.jl
- experiments/Atmos_LES/dycoms.jl
- experiments/Atmos_LES/risingbubble.jl
- experiments/Atmos_LES/surfacebubble.jl
- src/Atmos/Model/AtmosModel.jl
- test/DGmethods/Euler/acousticwave-1d-imex.jl
- test/DGmethods/Euler/isentropicvortex-imex.jl
- test/DGmethods/Euler/isentropicvortex-multirate.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/compressible_Navier_Stokes/density_current-model.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/DGmethods/courant.jl
- test/Diagnostics/sin_test.jl
- test/Driver/driver_test.jl
- test/Mesh/interpolation.jl
- test/runtests.jl
Adds balance law to initial condition functions, this will allow us to use `orientation` methods, and not re-implement them in all of the drivers.
> Add balance law to init funcs

- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- src/DGmethods/NumericalFluxes.jl
- src/DGmethods/balancelaw.jl
- src/DGmethods_old/DGBalanceLawDiscretizations.jl
- src/DGmethods_old/DGBalanceLawDiscretizations_kernels.jl
- src/Mesh/BrickMesh.jl
- src/Mesh/Grids.jl
- test/Mesh/BrickMesh.jl
- test/Mesh/mpi_connect_sphere.jl
Marking things that come from the interior/minus side and exterior/plus side with minus/plus signs instead of M/P. 
This should make the variable names easier to read and make their intent clearer. 
This PR only affects the DG Kernels.
> Replace 'M' and 'P' with '⁻' and '+'

- test/testhelpers.jl
CLIMA tests fail on systems with fewer processors without the `--oversubscribe` option. We could add another exception for these cases or make the `--oversubscribe` option default.
The following error will appear on systems with fewer processors:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4
slots that were requested by the application:
/usr/bin/julia
Either request fewer slots for your application, or make more slots
available for use.
A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:
1. Hostfile, via "slots=N" clauses (N defaults to number of
processor …
```
> Fixing runtests for systems with OpenMPI and less than 5 physical cores

- experiments/Atmos_LES/risingbubble.jl
- src/Atmos/Model/ref_state.jl
- test/DGmethods/compressible_Navier_Stokes/density_current-model.jl
This adds a constant potential temperature profile for visualization of perturbations in the rising thermal bubble and density current test cases. This is also probably a better state for linearization in the IMEX rising thermal bubble test.
@thomasgibson
> Add isentropic temperature profile

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/Atmos_GCM/heldsuarez.jl
- src/Atmos/Model/AtmosModel.jl
Adds a `data_config` field to `AtmosModel` to avoid globals in drivers. For now, we have to make an exception for `randomseed`.
> Add `data_config` to `AtmosModel`

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/Atmos_GCM/heldsuarez.jl
- experiments/Atmos_LES/dycoms.jl
- experiments/Atmos_LES/risingbubble.jl
- experiments/Atmos_LES/surfacebubble.jl
- src/Atmos/Model/orientation.jl
- src/Common/MoistThermodynamics/states.jl
- test/Common/MoistThermodynamics/runtests.jl
- test/DGmethods/Euler/acousticwave-1d-imex.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/compressible_Navier_Stokes/density_current-model.jl
Now that the `init_state` methods are aware of the balance law, we should utilize the following methods in the `init_state` methods:
- `altitude`
- `gravitational_potential`
- `internal_energy(::ThermodynamicState)`
- `total_energy(..., ::ThermodynamicState)`
Since several `DryPhase` models use `p` and `T` for initialization, I've also added a constructor to moist thermo that accepts these args:
- Adds a `PhaseDry_given_pT` constructor in moist thermo.
I’ve also added 
- A `latitude` function for `SphericalOrientation`
- A `longitude` function for `SphericalOrientation`
> [Atmos] Utilize existing functions in atmos init

- experiments/Atmos_LES/dycoms.jl
This removes some of the random perturbations that were being applied to the initial state of DYCOMS, leaving behind only one for `θ_liq`.
Submitted on behalf of @smarras79.
> Remove some random perturbations for DYCOMS

- src/Driver/Driver.jl
- test/Driver/driver_test.jl
- test/testhelpers.jl
Add a convenience wrapper of `DGmethods.courant` to be called using an already defined `SolverConfiguration`. This allows the user to write
```julia
CLIMA.DGmethods.courant(CLIMA.Courant.nondiffusive_courant,
solver_config)
```
instead of 
```julia
CLIMA.DGmethods.courant(CLIMA.Courant.nondiffusive_courant,
solver_config.dg,
solver_config.dg.balancelaw,
solver_config.Q,
solver_config.dt)
```
> Allow calling DGmethods.courant with SolverConfiguration

- src/Driver/Driver.jl
- test/Driver/driver_test.jl
It is likely convenient to allow the driver to inject extra output into the `cbinfo` callback (for instance to write out the current CFL numbers)
> Allow driver to add to the cbinfo invoke! callback

- src/Diagnostics/AtmosDiagnostics.jl
https://github.com/climate-machine/CLIMA/blob/466709c28b525850789f448873b192d7b1ac23de/src/Diagnostics/AtmosDiagnostics.jl#L132 Line 132 requires the LinearAlgebra package. This PR adds a statement to use it.
> `using LinearAlgebra` in AtmosDiagnostics

- src/ODESolvers/MultirateInfinitesimalStepMethod.jl
- src/ODESolvers/MultirateRungeKuttaMethod.jl
Make the multirate solvers consistent with the other solvers in dispatching based on time variables being `Real` as opposed to `AbstractFloat`
Mainly this allows the `timeend` to be an integer as opposed to an float.
> Cleanup a few things in multirate codes

- src/Driver/Driver.jl
Switches to using a fixed format for printing simtime and endtime, and print denominator in callback.
Old:
```
┌ Info: Update
│ simtime = 2.6159163716067161e+02
│ runtime = 00:01:59
└ norm(Q) = 3.0116687421160989e+09
```
New:
```
┌ Info: Update
│ simtime =    15.34 /  1000.00
│ runtime = 00:28:31
└ norm(Q) = 3.0115880375677762e+09
```
> improve formatting of simtime and endtime in logging

- test/Atmos/Parameterizations/runtests.jl
- test/Atmos/runtests.jl
- test/Common/runtests.jl
- test/Utilities/runtests.jl
- test/runtests.jl
This adds flexibility to call specific tests, using [command line args](https://github.com/JuliaLang/Pkg.jl/pull/1226).
Now, we can call a specific test as follows
```
julia --project test/runtests.jl Common
Starting tests for Common
Starting tests for MoistThermodynamics
[ Info: CUDAdrv.jl failed to initialize, GPU functionality unavailable (set JULIA_CUDA_SILENT or JULIA_CUDA_VERBOSE to silence or expand this message)
Completed tests for MoistThermodynamics, 30 seconds elapsed
Starting tests for PlanetParameters
Completed tests for PlanetParameters, 0 seconds elapsed
Completed tests for Common, 31 seconds elapsed
Test Summary: | Pass  Total
CLIMA         |  457    457
```
> Make tests flexibly callable

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/Atmos_GCM/heldsuarez.jl
- experiments/Atmos_LES/dycoms.jl
- experiments/Atmos_LES/risingbubble.jl
- experiments/Atmos_LES/surfacebubble.jl
- experiments/Ocean_BoxGCM/homogeneous_box.jl
- experiments/Ocean_BoxGCM/ocean_gyre.jl
- src/DGmethods/DGmodel.jl
- src/Driver/Driver.jl
- test/DGmethods/advection_diffusion/direction_splitting_advection_diffusion.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/Diagnostics/sin_test.jl
- test/Ocean/Hydrostatic_Boussinesq/simple_box.jl
- test/Ocean/Hydrostatic_Boussinesq/simple_box_IMEX.jl
- test/Ocean/Hydrostatic_Boussinesq/test_divergence_free.jl
- test/Ocean/Hydrostatic_Boussinesq/test_divergence_free_IMEX.jl
Replaces instances of `forcecpu` keyword with `init_on_cpu` to clarify its functionality. It only enables initialisation on CPU, and does not force the run to be on CPU. (use cases: Currently CPU initialisation needs to be enabled when using random number generators for the initial condition)
> Replaces `forcecpu` with `init_on_cpu` for clarity

- experiments/AtmosGCM/heldsuarez.jl
- experiments/OceanBoxGCM/homogeneous_box.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/courant.jl
- src/Atmos/Model/linear.jl
- src/CLIMA.jl
- src/DGmethods/Courant.jl
- src/DGmethods/balancelaw.jl
- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
- test/Driver/driver_test.jl
- The courant functions were atmos specific. This adds a stub module `Courant` then lets `AtmosModel` override them.
- The `calculate_dt` function did not use the initial condition, thus the courant number may be larger for the given initial condition (this lead to a [weird test in `driver_test.jl`](https://github.com/climate-machine/CLIMA/blob/b7515251d1aeec89e69c8997c31ddb09991025c7/test/Driver/driver_test.jl#L82-L87). Since the initial condition is known before the time step is calculated, this can be used to calculate a consistent dt
The new `calculate_dt` is only used for the atmos model and the ocean model remains unchanged (cc @blallen)
> More consistent and general Courant calculations

- src/Atmos/Model/source.jl
Using `map` seemed to cause problems for > 4 sources.
This manually unrolls the loop using the `@nexprs` macro.
cc: @akshaysridhar
> Unroll loop over sources

- .dev/.gitignore
- .dev/Project.toml
- .dev/format.jl
- .github/pull_request_template.md
- .github/workflows/JuliaFormatter.yml
- CONTRIBUTING.md
On each PR, this will run the JuliaFormatter.jl on all modified .jl files, failing if the formatting modifies any of the files.
I originally tried using https://github.com/julia-actions/julia-format, but it wasn't really sufficient for our needs, so it made more sense to use a custom workflow.
> Create JuliaFormatter GitHub Action

- experiments/AtmosLES/dycoms.jl
experiments/AtmosLES/dycoms.jl:
Modified dycoms.jl to have the correct parameters that allow it to run to completion if timeend is set to 14400. 
* D_subsidence = 3.75e-6
* maxiter = 1
* tolerance = FT(50)
* Courant_number = 1.8
These are the parameters that allowed me to run dycoms to completion off-line. I used these parameters to produce the first results plotted in the dycoms paper draft (overleaf) and in the slack #dycoms channel.
> Update DYCOMS subsidence parameter to reflect 14400s offline simulations

- experiments/AtmosLES/risingbubble.jl
- src/Driver/Driver.jl
- src/Driver/driver_configs.jl
- src/Driver/solver_configs.jl
- test/Driver/gcm_driver_test.jl
- test/Driver/runtests.jl
This PR simply adds a multirate solver type that executes a 2-rate method. The idea is that slow (advection & diffusion) processes are evaluated using a slow method (some explicit RK method) and the fast (acoustic waves, gravity waves) processes using a fast method with a smaller time-step size.
I tried to not modify the current interface too much, but I am not really happy with the handling of these solver types. I think it can be done in a far more clean way, but I want to save that for another PR. I tried to keep the changes in the PR fairly minimal.
This PR just adds a quick multirate solver to be used in the LES experiments. An example is shown for the risingbubble test in `Atmos_LES`.
[UPDATE]: I've added a gcm driver test (acoustic wave) using the multirate solver. This also …
> Add a multirate solver type to driver

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/states.jl
Removes many warnings in moist thermo. Closes #829. Sorry for all of the noise everyone! (I couldn't wait to fix this to get #802 in)
This is not ideal, as there are a growing number of default values for various methods. I'll soon try using kwargs in moist thermo, which will fix this problem and significantly improve the interface, but I'd like to make sure this doesn't tank performance. cc: @kpamnany
> Remove moist thermo warnings

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/risingbubble.jl
- experiments/AtmosLES/surfacebubble.jl
- src/Driver/driver_configs.jl
- test/Diagnostics/sin_test.jl
- test/Driver/driver_test.jl
Fix grid1d (min extent), and float-type in driver configs.
This closes #827 
@charleskawczynski 
Fixes issue  #827. Users can now set either integer or float values for their domain extents (preserves functionality of current experiments). Also changes (in sim-summary info) `grid` -> `domain` , since `grid` might (in this case incorrectly) imply number of grid points for the printed output.
> Fix for #827, domain extents in LES are now floats

- experiments/OceanBoxGCM/homogeneous_box.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- src/CLIMA.jl
- src/Ocean/HydrostaticBoussinesq/Courant.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
- src/Ocean/HydrostaticBoussinesq/OceanBoundaryConditions.jl
- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
- test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
- test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
I realized instead of storing the values for viscosity and diffusivity we could just use a function to calculate them pointwise. I would like to do something similar with the Coriolis `f`, wind stress `τ`, and sea surface temperature `θʳ` variables, but these require accessing either `geom` or `coords` in `source!`, `numerical_boundary_flux_*!` and `boundary_state!`.
> Reduce aux usage for Ocean Model

- examples/Atmos/dry_rayleigh_benard.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/risingbubble.jl
- experiments/AtmosLES/surfacebubble.jl
The merger of #823 results in some necessary changes to the experiment files; this PR adds the atmos-default diagnostic configuration to the BOMEX experiment (and other existing atoms experiments / examples), such that `--enable-diagnostics` will produce the appropriate `.jld2` file with horizontally averaged terms. Also uses `ODESolvers` in preparation for the MRRK methods to be built into experiments in a future PR. 
cc: @kpamnany
```
modified:   experiments/AtmosLES/bomex.jl
modified:   experiments/AtmosLES/surfacebubble.jl
modified:   experiments/AtmosLES/risingbubble.jl
modified:   examples/Atmos/dry_rayleigh_benard.jl
```
> Add diagnostic (atmos-default) setting to Atmos experiments

- .dev/clima_formatter_options.jl
- .dev/climaformat.jl
- .dev/format.jl
- .dev/hooks/pre-commit
- CONTRIBUTING.md
This adds two julia scripts to help with formatting julia code using CLIMA's standards.
First, is a utility `.dev/climaformat.jl` that will format the julia files in the given path. For example, from the top-level CLIMA directory
```
julia .dev/climaformat.jl src/CLIMA.jl
```
will format `src/CLIMA.jl` and
```
julia .dev/climaformat.jl .
```
will format all of CLIMA's julia files.
The second is a `pre-commit` script that can be placed in `$GIT_DIR/hooks/*` which will  prevent commits of incorrectly formatted julia code.  It will also provide commands that can be run to format the code correctly.
One may tell git about the script with (from the top-level directory of a clone of CLIMA)
```
ln -s ../../.dev/hooks/pre-commit .git/hooks
```
and then when `git commit` is run an error message …
> Scripts for formatting CLIMA's julia code

- .github/pull_request_template.md
- bors.toml
Right now our git commit log is littered with:
```
```
this tells bors to cut the noise out. The sideeffect is that it will ignore everything afterwards.
> limit noise from boilerplate

- src/Diagnostics/atmos_default.jl
modified:   src/Diagnostics/atmos_default.jl
Fixes issue #831 : incorrect cumulative summation in diagnostics module. 
I have
> Diagnostics - bugFix for issue #831

- .dev/hooks/pre-commit
The git pre-commit hook for the `JuliaFormatter` should ignore files that have been deleted.
> Fix git pre-commit hook for file removal

- src/Driver/driver_configs.jl
modified:   src/Driver/driver_configs.jl
To help with logging, this PR provides access to fields of `AtmosModel` and prints it 
with the initial simulation start-up information. 
Boundary conditions are captured, but a bit cumbersome to read through at this logging level since all the terms are lumped; initial conditions are not at all represented in a useful form. I've found this useful in keeping track of simulation parameters as I submit a bunch of stuff to the cluster. Formatting could use a bit of work to make it easier to interpret. Would also be useful to extend this to `solver` properties in a separate PR. 
I have
> Print AtmosModel composition to the init-info statement 

- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Ocean/HydrostaticBoussinesq/Courant.jl
Exposes vtk and diagnostics saving methods. Reduces default courant number to somewhere near stable and shows how to manually set the time step. Better information from the automatic timestep calculation. Also applied the JuliaFormattere to these two files.
> Changes to ease use of ocean_gyre.jl

- docs/src/Mesh.md
- src/Mesh/Interpolation.jl
- test/Mesh/interpolation.jl
1. Decoupled projection operator.
2. Added GPU acceleration to accumulate_interpolated_data.
3. Merged accumulation functions for cubedsphere and brick topologies.
4. Added docs.
For the test cases in test/Mesh/interpolation.jl, sample timing results are as follows:
Topology: Brick
Precision: Float64
processors: 1
interpolation: 0.000010 seconds (52 allocations: 1.797 KiB)
accumulation: 0.000014 seconds (58 allocations: 2.297 KiB)
Topology: CubedSphere
processors: 1
Precision: Float64
interpolation: 0.000012 seconds (48 allocations: 1.734 KiB)
projection: 0.000017 seconds (85 allocations: 3.703 KiB)
accumulation: 0.000016 seconds (58 allocations: 2.297 KiB)
I have
> Decoupled projection operator.

- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
#727 lacked the integration of pkin in the ocean model. This fixes that.
> Fix integration of pkin in ocean model

- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
Minor modification to "ocean_gyre.jl", mostly changing initial Temperature to no longer
be horizontally homogeneous ; this turns to be very useful by triggering short time-scale
adjustement on top of (longer) spin-up under wind-stress action. Was key in finding problem
that got fixed by PR #883
> Jm c/improve ocean gyre

- Parameters/EarthParameters.jl
- Parameters/Planet.jl
- examples/Atmos/dry_rayleigh_benard.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/risingbubble.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/OceanBoxGCM/homogeneous_box.jl
- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/isentropic.jl
- src/Common/MoistThermodynamics/states.jl
- src/Common/Parameters/Parameters.jl
- src/Common/PlanetParameters/UniversalConstants.jl
- src/Driver/driver_configs.jl
- test/DGmethods/Euler/acousticwave_1d_imex.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/Euler/isentropicvortex_imex.jl
- test/DGmethods/Euler/isentropicvortex_multirate.jl
- test/DGmethods/compressible_Navier_Stokes/density_current_model.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/DGmethods/courant.jl
- test/Driver/gcm_driver_test.jl
- test/Mesh/interpolation.jl
Removes `FT` from `ParameterSet`. Trade-offs of including/excluding `FT`:
- Cannot make a single global instance of `ParameterSet`, since `FT` is needed and is only known within each function. This is especially a problem for drivers without a balance law since they cannot create a local copy.
- We cannot make generic typed types, e.g., `foo(param_set::PS{FT}) where {FT,PS}`, so it's inconvenient without a single global abstract type for `ParameterSet`.
- Including `FT` does alleviate needing to use `FT` around functions (e.g., `FT(grav(param_set))`), but the main purpose of `ParameterSet` is really to decide which set of parameters to use, not their float type, so it's not really an orthogonal design to include `FT`.
I have
> Remove `FT` from ParameterSet

- test/Atmos/Parameterizations/TurbulenceConvection/TDMA.jl
Changes are a bit obscured by formatting. Essentially, all 3 `@test` lines were `@assert`s.
I have
> Use `@test`, not `@assert` in TDMA tests

- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Utilities/VariableTemplates/runtests.jl
- test/Utilities/VariableTemplates/varsindex.jl
Adds a convenience function `varsindex` for determining which array indices a symbol corresponds to in a `VariableTemplate` defined `NamedTuple`
This functionality is already in #731 and this makes that functionality a standalone PR.
> Add convenience `varsindex` functionality

- experiments/AtmosGCM/heldsuarez.jl
- slurmci-test.toml
- src/Utilities/VariableTemplates/VariableTemplates.jl
This updates the Held-Suarez experiment file with some modified settings that results in a stable simulation (tested to 365 days) with a 3x speedup in terms of WCT compared to the previous settings with the same resolution.
I have
> New settings to make Held-Suarez 3x faster than before

- examples/Atmos/dry_rayleigh_benard.jl
- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Atmos/Model/turbulence.jl
- src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
- test/DGmethods/compressible_Navier_Stokes/density_current_model.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/Diagnostics/sin_test.jl
- test/Driver/driver_test.jl
- test/Driver/gcm_driver_test.jl
- test/Mesh/interpolation.jl
- test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
- test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
Makes tests/drivers use only what is needed from `CLIMA.PlanetParameters`. 
I have
> Import planet parameters explicitly

- slurmci-test.toml
- test/Driver/runtests.jl
Closes #879.
Running with code coverage causes this test to take over an hour -- without code coverage it completes in two minutes. This moves the test to SlurmCI until code coverage slowdowns are sorted.
I have
> Move GCM driver test from AzureCI to SlurmCI

- src/Atmos/Model/courant.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- src/DGmethods/balancelaw.jl
- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
- src/Ocean/HydrostaticBoussinesq/Courant.jl
- test/DGmethods/courant.jl
This PR makes the Courant calculations time-aware. As pointed out by @akshaysridhar, this is useful if we want to make `C_smag` (or, effectively, the inverse timestep) decay so that we can speed up calculations after initial transient stiffness. It also simplifies some of the Courant functions.
> Make Courant absolute time aware

- src/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/ODESolvers/LowStorageRungeKuttaMethod.jl
- src/ODESolvers/MultirateInfinitesimalStepMethod.jl
- src/ODESolvers/MultirateRungeKuttaMethod.jl
- src/ODESolvers/ODESolvers.jl
- src/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
Some cleanup for the ARK routines:
- fixed some long comments
- remove some dead code
- remove `dt` from `dostep!` to force the use of `updatedt!` in order to catch better whether `dt` with implicit solvers can really be changed
> Improve implicit time stepper interface

- examples/Microphysics/KinematicModel.jl
- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- slurmci-test.toml
- src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
- src/Atmos/Parameterizations/CloudPhysics/MicrophysicsParameters.jl
- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Atmos/Parameterizations/Microphysics/runtests.jl
- test/Driver/driver_test.jl
Converts the microphysics example, `examples/Microphysics/ex_1_saturation_adjustment.jl` to the new framework.
It would be nice to reduce the boundary condition boilerplate. cc: @simonbyrne 
Co-authors: @trontrytel
> Convert Microphysics `saturation_adjustment` driver to new framework

- Manifest.toml
- Project.toml
- examples/Atmos/dry_rayleigh_benard.jl
- examples/DGmethods_old/ex_003_acoustic_wave.jl
- examples/Microphysics/KinematicModel.jl
- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/risingbubble.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/OceanBoxGCM/homogeneous_box.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- slurmci-test.toml
- src/Driver/driver_configs.jl
- test/DGmethods/Euler/acousticwave_1d_imex.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/Euler/isentropicvortex_imex.jl
- test/DGmethods/Euler/isentropicvortex_multirate.jl
- test/DGmethods/compressible_Navier_Stokes/density_current_model.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/DGmethods/courant.jl
- test/Driver/gcm_driver_test.jl
- test/Mesh/interpolation.jl
Converts examples and experiments to use `CLIMAParameters.jl` package, and removes PlanetParameters from these files.
I have
> Use CLIMAParameters

- docs/src/Atmos/EDMFEquations.md
- docs/src/Atmos/Microphysics.md
- src/Atmos/Model/boundaryconditions.jl
- src/Atmos/Model/radiation.jl
- test/Atmos/Parameterizations/Microphysics/runtests.jl
- test/DGmethods/Euler/acousticwave_1d_imex.jl
- test/DGmethods/Euler/isentropicvortex.jl
- test/DGmethods/Euler/isentropicvortex_imex.jl
- test/DGmethods/Euler/isentropicvortex_multirate.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/DGmethods/courant.jl
- test/DGmethods/horizontal_integral_test.jl
- test/DGmethods_old/Euler/RTB_IMEX.jl
- test/Diagnostics/sin_test.jl
- test/Driver/driver_test.jl
- test/Mesh/interpolation.jl
- test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
- test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
- test/Ocean/ShallowWater/GyreDriver.jl
- test/Ocean/ShallowWater/GyreInABox.jl
- test/runtests_gpu.jl
Removes more use/references of `PlanetParameters` with CLIMAParameters.jl. This should also partially address #919.
I have
> Remove more use of PlanetParameters

- experiments/AtmosLES/risingbubble.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/boundaryconditions.jl
- src/Atmos/Model/hyperdiffusion.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/remainder.jl
- src/DGmethods/NumericalFluxes.jl
Adds the user-facing component to allow hyperdiffusion (#658) to be used at the AtmosModel level via a subcomponent `hyperdiffusion` within `AtmosModel{}(...)`
1) Adds `hyperdiffusion.jl`
2) Updates `AtmosLES` experiments (and other existing simulation drivers) to include hyperdiffusion wherever activated. (The sensible default prescribed in `AtmosModel.jl` is the `NoHyperDiffusion` model)
> User-facing changes to include hyperdiffusion in AtmosModel

- azure-pipelines.yml
Upgrades the Microsoft MPI used by Azure CI
> Azure: Use latest Microsoft MPI

- .github/workflows/Coverage.yaml
- azure-pipelines.yml
> Move coverage CI  to GitHub Actions

- src/Driver/Driver.jl
Callbacks are done sequentially so any user-defined callbacks must appear before diagnostic callbacks. Currently this affects filter application.
I have
> Change order of user callbacks 

- docs/make.jl
- docs/src/Atmos/Model/turbulence.md
- examples/Atmos/dry_rayleigh_benard.jl
- experiments/AtmosLES/risingbubble.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/remainder.jl
- src/Diagnostics/atmos_default.jl
Update eddy-viscosity turbulence models, add documentation, allow diffusivity to be imported from turbulence.jl (allows tracer gradient dependent diffusivities, upgrade from current reliance on turbulent Prandtl numbers in `AtmosModel.jl`). Update example file to use Vreman model. 
```
modified: src/Atmos/Model/AtmosModel.jl
new file: docs/src/Atmos/Model/turbulence.md
modified: src/Atmos/Model/turbulence.jl
modified: examples/Atmos/dry_rayleigh_benard.jl
modified: experiments/AtmosLES/risingbubble.jl
modified: src/Diagnostics/atmos_default.jl
modified: src/Atmos/Model/bc_energy.jl
modified: src/Atmos/Model/remainder.jl
modified: docs/make.jl
```
I have
> Update turbulence models and add documentation

- src/Diagnostics/atmos_default.jl
- src/Diagnostics/dump_state_and_aux.jl
- src/InputOutput/Writers/Writers.jl
- src/InputOutput/Writers/jld2_writer.jl
- src/InputOutput/Writers/netcdf_writer.jl
- test/InputOutput/Writers/runtests.jl
Adds a `time` dimension of length 1 as well as a `simtime` variable that uses the `time` dimension and records the simulation time at which the diagnostics were run.
Also fixes a minor bug that was preventing "DumpStateAndAux" from writing diagnostics output.
Closes #940. Cc: @szy21 
I have
> Add `simtime` to output diagnostics

- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/courant.jl
- src/Atmos/Model/orientation.jl
- src/Atmos/Model/ref_state.jl
- src/Atmos/Model/source.jl
- test/DGmethods/Euler/acousticwave_1d_imex.jl
- test/DGmethods/advection_diffusion/advection_diffusion_model.jl
- test/Driver/gcm_driver_test.jl
- test/Mesh/interpolation.jl
This PR adds `param_set` to function arguments in `orientations.jl`, to prepare switching from PlanetParameters to CLIMAParameters. This is needed because `grav` in `altitude` needs to change to `grav(param_set)`. Convenience wrappers were added that accept the balance law and aux.
I have
> Add `param_set` to `orientations.jl` function args

- .dev/hooks/pre-commit.sysimage
- .dev/precompile.jl
- CONTRIBUTING.md
Add procedure for using the [`PackageCompier`](https://github.com/JuliaLang/PackageCompiler.jl) to speeds up the `JuliaFormatter`.
> Add instructions for precompiling JuliaFormatter

- src/ODESolvers/GenericCallbacks.jl
- test/ODESolvers/genericcb_tests.jl
- test/ODESolvers/runtests.jl
Was not enabled. Closes #878. Also adds tests for `GenericCallbacks`.
I have
> Add back `EveryXSimulationTime` callback mechanism

- examples/Microphysics/ex_1_saturation_adjustment.jl
- examples/Microphysics/ex_2_Kessler.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/remainder.jl
- src/Atmos/Model/source.jl
- src/DGmethods/DGmodel_kernels.jl
- src/DGmethods/balancelaw.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/ShallowWater/ShallowWaterModel.jl
- test/DGmethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- test/DGmethods/compressible_Navier_Stokes/mms_model.jl
- test/DGmethods/vars_test.jl
- test/LinearSolvers/poisson.jl
In order to avoid applying the sources twice (once in the vertical and again in the horizontal) for multirate time stepping methods, the `source!` function needs to be direction aware.
> Pass direction into source!

- experiments/OceanBoxGCM/homogeneous_box.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- slurmci-test.toml
- src/Driver/solver_configs.jl
- src/Ocean/HydrostaticBoussinesq/BoundaryConditions.jl
- src/Ocean/HydrostaticBoussinesq/Courant.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
- src/Ocean/HydrostaticBoussinesq/OceanBoundaryConditions.jl
- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
- test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
- test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
The current implementation didn't properly zero out the normal component of velocity. Updated these to follow equations 1.26 and 1.28 from the numerics section of the design docs. 
I have
> Fix CoastlineFreeSlip boundary conditions for HydrostaticBoussinesqModel

- docs/src/Atmos/Model/turbulence.md
- src/Atmos/Model/courant.jl
- src/Atmos/Model/turbulence.jl
Patches courant callback functionality, fix for issue #950. Sample output (from `risingbubble.jl`) included below. Removes cross products in `turbulence.jl` and simplifies functions for users. 
```
[ Info: Initializing DryRisingBubble
┌ Info: Starting DryRisingBubble
│     dt              = 2.07039e+00
│     timeend         =  1000.00
│     number of steps = 483
└     norm(Q)         = 3.0116018495687184e+09
┌ Info: Courant numbers at simtime:     0.00, Δt =     2.07 s
│     Acoustic (vertical) Courant number    = 20
│     Acoustic (horizontal) Courant number  = 20
│     Advection (vertical) Courant number   = 0
│     Advection (horizontal) Courant number = 0
│     Diffusion (vertical) Courant number   = 1.6e-08
│     Diffusion (horizontal) Courant number = 2.3e-08
```
I have
> Patch courant callback - fixes issue #950

- src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl
- test/Atmos/Parameterizations/SurfaceFluxes/runtests.jl
- Removes `PlanetParameters` from `SurfaceFluxes`
- Cleans up some docs/naming conventions
- Adds type stability tests (and fixes some type instabilities)
- Applies formatter
I have
> Remove `PlanetParameters` from `SurfaceFluxes`

- experiments/AtmosGCM/heldsuarez.jl
- src/Atmos/Model/ref_state.jl
Added the Smagorinksy-Lilly SGS model and 4-th-order hyperdiffusion to the Held-Suarez driver. 
I also simplified some of the code in the driver file. All in all, with these parameters we get a nice speedup.
I have
> Add turbulence models to Held-Suarez for 1.5x speedup of simulation

- test/DGmethods/Euler/isentropicvortex.jl
Fixes type instability in the isentropic vortex test
> Fix type instability in isentropic vortex test

- test/LinearSolvers/cg.jl
The test is not reproducible because the seed is set after rand has been
called a few times.
> Set random seed in cg test at start of file

- experiments/AtmosLES/dycoms.jl
* Reduced initial random perturbation intensity for from +-0.002 to +-0.001
* Replaced: moisture = EquilMoist{FT}(; maxiter = 5), with moisture = EquilMoist{FT}(maxiter = 1, tolerance(FT(100)),
I have
>  experiments/AtmosLES/dycoms.jl

- examples/Atmos/dry_rayleigh_benard.jl
- examples/Microphysics/KinematicModel.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/risingbubble.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Arrays/MPIStateArrays.jl
- src/CLIMA.jl
- src/DGmethods/DGmodel.jl
- src/DGmethods/DGmodel_kernels.jl
- src/Diagnostics/Diagnostics.jl
- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
- src/Utilities/Callbacks/Callbacks.jl
- src/Utilities/Checkpoint/Checkpoint.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Diagnostics/sin_test.jl
- test/Driver/cr_unit_tests.jl
Closes #877 and #909.
Most of the command line arguments relate to whether or not something should occur, and then specifying the interval at which it occurs. These intervals are (somewhat randomly) either in wall-clock time or simulation steps.
After #951, specifying simulation time is now also possible. So, rather than have, for instance, `--checkpoint-walltime` and `--checkpoint-simtime` and `--checkpoint-simsteps`, this allows intervals to be specified as:
- `2hours` or `10mins` or `30secs` => wall-clock time,
- `9.5smonths` or `3.3sdays` or `1.5shours` => simulation time,
- `1000steps` => simulation steps,
- `never` => disable,
- `default` => use any pre-defined interval (only present for diagnostics groups at the moment).
And now there is just `--checkpoint <interval>`. All command …
> Rework command line arguments

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/isentropic.jl
- src/Common/MoistThermodynamics/states.jl
Updates the moist thermodynamics docs to include `param_set` arguments. Since `param_set` is used in many function arguments, I made the docs for `param_set` for each function simply say:
```
- `param_set` an `AbstractParameterSet`, see the [`MoistThermodynamics`](@ref) for more details
```
At the top of the module, I added a section explaining [more details](https://github.com/climate-machine/CLIMA/pull/997/files#diff-b930a7e34792312cae59cfd0823efe90R7-R24).
I have
> Update moist thermo doc strings

- src/Utilities/Callbacks/Callbacks.jl
> Fix interval parsing for `s*`

- src/Utilities/Callbacks/Callbacks.jl
The Courant number callback broke again during the merging of #958. Fortunately, the fix seems to be quick: I just introduced the missing imports. The Courant monitor should be working now.
I have
> Fix missing imports for Courant number callback

- src/CLIMA.jl
- src/Driver/Driver.jl
This will output what the WIKI [now shows](https://github.com/climate-machine/CLIMA/wiki/CLIMA-command-line-arguments). Closes #996.
I have
> Improve output of `--help`

- .github/workflows/Documenter.yaml
- bors.toml
This PR tells Bors to check that the doc-build is passing.
I have
> Make Bors depend on Docs

- test/Numerics/LinearSolvers/cg.jl
The CI was failing for the pcg test. This seems to be because the mpi_x variable was initialized with some NaNs already in it. This fixes that and also sets the "Architecture-specific Array test" to no longer run when Arrays have already been tested on CPU-only devices.
[Example for failed CI on Mac](https://dev.azure.com/climate-machine/CLIMA/_build/results?buildId=3445&view=results) (#998)
We might want to talk about how MPIStateArrays are initialized with whatever is in memory. Maybe they should be initialized as all 0s?
I have
> potential fix for pcg test

- experiments/AtmosLES/dycoms.jl
- src/Numerics/DGmethods/DGmodel_kernels.jl
Bugfix - (var naming + assignment in integral_load_aux)	
modified:   experiments/AtmosLES/dycoms.jl
Bugfix - (element access within reverse integral kernel)
modified:   src/Numerics/DGmethods/DGmodel_kernels.jl
Fixes issue with `reverse_integral` #1009. 
I have
> Bugfix -(issue #1009)

- docs/src/ExtendingCLIMA/Diagnostics/DiagnosticVariables.md
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_core.jl
- src/Diagnostics/atmos_default.jl
- src/Diagnostics/dump_state_and_aux.jl
- src/Diagnostics/thermo.jl
- src/InputOutput/Writers/Writers.jl
- src/InputOutput/Writers/jld2_writer.jl
- src/InputOutput/Writers/netcdf_writer.jl
- test/Diagnostics/sin_test.jl
- test/InputOutput/Writers/runtests.jl
- Adds more of the `default` diagnostics from #943 (excluding LWP and cloud cover).
- Changes the variable names for the diagnostics according to the [variable list](https://climate-machine.github.io/CLIMA/latest/DiagnosticVariables/).
- Changes the computation of the vertical fluxes and variances to use density-weighted means.
- Applies the idea from and closes #739.
- Changed `Writers.write_data()` to allow specifying dimension names for a variable.
I have
> More LES diagnostics

- slurmci-test.toml
- src/Driver/solver_configs.jl
- src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/Numerics/ODESolvers/BackwardEulerSolvers.jl
- src/Numerics/ODESolvers/LowStorageRungeKuttaMethod.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalGARKDecoupledImplicit.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalGARKExplicit.jl
- src/Numerics/ODESolvers/ODESolvers.jl
- test/Numerics/DGmethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGmethods/Euler/isentropicvortex_imex.jl
- test/Numerics/DGmethods/Euler/isentropicvortex_mrigark.jl
- test/Numerics/DGmethods/Euler/isentropicvortex_mrigark_implicit.jl
- test/Numerics/DGmethods/Euler/isentropicvortex_multirate.jl
- test/Numerics/DGmethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
- test/Numerics/DGmethods/advection_diffusion/pseudo1D_advection_diffusion_mrigark_implicit.jl
- test/Numerics/ODESolvers/ode_tests_basic.jl
- test/Numerics/ODESolvers/ode_tests_common.jl
- test/Numerics/ODESolvers/ode_tests_convergence.jl
Adds support for the MRI-GARK methods of Sandu (2019).
Also refactors the linear solver interface for the ODE solvers, by allowing for non-linear solvers (as opposed to just linear solvers).
```
@article{Sandu2019,
title={A class of multirate infinitesimal gark methods},
author={Sandu, Adrian},
journal={SIAM Journal on Numerical Analysis},
volume={57},
number={5},
pages={2300--2327},
year={2019},
publisher={SIAM},
doi={10.1137/18M1205492}
}
```
> Adding MultiRate, Infinitesimal GARK methods

- docs/list_of_tutorials.jl
- docs/make.jl
Fixes logic of `generate_tutorials` Bool. Before this PR, tutorials are generated with `generate_tutorials=false`, but they are not included in the docs. After this PR, `generate_tutorials=false` will skip generating tutorials and the docs will reflect this.
I have
> Fix docs `generate_tutorials` logic

- experiments/AtmosLES/bomex.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
Replaces IMEX time stepper with MRRK as the default in 2 LES experiments. 
I have
> Switch LES timestepper (experiments/bomex.jl and tutorials/dry_rayleigh_benard.jl)

- docs/list_of_tutorials.jl
The existing
```julia
tutorials_jl = [
joinpath(root, f)
for (root, dirs, files) in Base.Filesystem.walkdir(tutorials_dir)
for f in files
]
```
in `docs/list_of_tutorials.jl` is sometimes picking up local temporary files, and this should only be a list of Julia files. This PR adds a filter to prevent picking up unwanted files:
```julia
filter!(x -> endswith(x, ".jl"), tutorials_jl) # only grab .jl files
```
I have
> Add docs file filter

- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- slurmci-test.toml
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_core.jl
- src/Diagnostics/atmos_default.jl
- src/Diagnostics/dump_state_and_aux.jl
- src/Driver/solver_configs.jl
- src/Numerics/DGmethods/DGmethods.jl
- src/Numerics/DGmethods/DGmodel.jl
A bug in 'DumpStateAndAux'. Also clean up some issues caused by the concurrent merge of 1019 and 961. Finally, enable diagnostics collection in two experiments on Slurm CI, to ensure all diagnostics groups run at least once on CI.
I have
> Fix some diagnostics bugs

- src/Numerics/DGmethods/DGmodel.jl
- src/Numerics/DGmethods/DGmodel_kernels.jl
- src/Numerics/DGmethods/balancelaw.jl
- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Numerics/DGmethods/advection_diffusion/pseudo1D_heat_eqn.jl
Adds support for higher order (polynomial order up to 22) DG on the GPU. Closes #502.
- `volumerhs!` and `volumeviscterms!` DG kernels were modified to use less shared memory
- `Grad` wrapper was modified to support views
- Argument order of the main computational kernels was changed slightly to have output arrays near the beginning and all non-modified arrays afterwards
I have
> Add support for higher order DG on GPU

- docs/src/ExtendingCLIMA/Numerics/DGmethods/how_to_make_a_balance_law.md
- src/Numerics/DGmethods/balancelaw.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
Updates the documentation for "How to make a Balance Law" with all the functions necessary and descriptions, with terminology updated to match #961. Improvements can be made upon this, but this should be good as a quick start guide.
I have
> BalanceLaw Documentation consistent with #961

- src/InputOutput/VTK/VTK.jl
- src/InputOutput/VTK/writepvtu.jl
- src/InputOutput/VTK/writevtk.jl
- src/Utilities/Callbacks/Callbacks.jl
And rework how VTK timing is done.
`export TICTOC_PRINT_RESULTS=1` before running CLIMA to see timing information.
I have
> Add TicToc timing for diagnostics

- .github/pull_request_template.md
- .github/pull_request_template.md.bak
- README.md
- docs/make.jl
- docs/src/CodingConventions.md
- docs/src/ExtendingCLIMA/Atmos/Model/risingbubble.md
- docs/src/ExtendingCLIMA/Contributing/CONTRIBUTING.md
- docs/src/ExtendingCLIMA/Numerics/LinearSolvers/IterativeSolvers.md
- docs/src/ExtendingCLIMA/Numerics/ODESolvers/Timestepping.md
- docs/src/Installation.md
- experiments/AtmosLES/risingbubble.jl
- tutorials/Atmos/heldsuarez.jl
Change `climate-machine` to reflect the new organization name.
I have
> Rename climate-machine-> CliMA

- src/Common/MoistThermodynamics/MoistThermodynamics.jl
- src/Common/MoistThermodynamics/relations.jl
- src/Common/MoistThermodynamics/states.jl
- test/Common/MoistThermodynamics/profiles.jl
- test/Common/MoistThermodynamics/runtests.jl
Changes Moist Thermo's saturation adjustment tolerance to accept the residual tolerance and not the solution tolerance.
- Some of the tolerances in moist thermo's test suite need to be reviewed
I have
> Make moist thermo tolerance residual-based

- src/Numerics/DGmethods/DGmodel.jl
- src/Numerics/DGmethods/DGmodel_kernels.jl
- src/Numerics/Mesh/Grids.jl
This limits the number of threads in a thread block for two kernels used in Courant number calculation. This allows use of high order polynomials on the GPU, at least without hyperdiffusion. Missed in #1005.
CC
@vchuravy 
I have
> Limit thread block size in Courant number kernels

- .github/workflows/Documenter.yaml
- docs/make.jl
- docs/src/HowToGuides/Atmos/Microphysics.md
- docs/src/HowToGuides/Atmos/Model/risingbubble.md
- docs/src/HowToGuides/Atmos/Model/tracers.md
- docs/src/HowToGuides/Atmos/Model/turbulence.md
Fixes several broken docs:
- Microphysics: had missing variables / function arguments
- RTB/Turbulence/Tracers: switched `@example` to `julia` blocks, since they are split across scope blocks (which breaks), or does not include sufficient code for an example.
- Fixes the
```
connect: Connection refused
GKS: can't connect to GKS socket application
GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC in routine ACTIVATE_WS
```
error by [installing](https://gr-framework.org/julia.html#installation) required libraries as suggested [here](https://github.com/jheinen/GR.jl/issues/278#issuecomment-587101840) and [here](https://github.com/jheinen/GR.jl/issues/278#issuecomment-587090846)
I have
> Fix some broken docs

- test/Arrays/runtests.jl
- test/Diagnostics/runtests.jl
- test/Driver/runtests.jl
- test/Numerics/DGmethods/runtests.jl
- test/Numerics/LinearSolvers/runtests.jl
- test/Numerics/Mesh/runtests.jl
- test/Numerics/ODESolvers/runtests.jl
- test/Ocean/runtests.jl
- test/testhelpers.jl
Simplify the runmpi function
I have
> switch to using new mpiexec interface from MPI.jl

- docs/make.jl
My docs were hanging locally because of some leftover files in `docs/src/generated/` (this folder is not git-tracked). So, this PR removes this folder before building the docs so that others don't fall into this trap.
I have
> Remove generated docs folder in docs/make.jl

- src/Numerics/DGmethods/DGmodel_kernels.jl
Fixes a possible race condition in the vertical tendency evaluation.
I have
> Add missing sync in vertical volume tendency kernel

- .dev/systemimage/climate_machine_image.jl
- .gitignore
- azure-pipelines.yml
- docs/src/HowToGuides/Contributing/CONTRIBUTING.md
CLIMA startup times are long, which can make iterative development and
debugging difficult / painful. This adds a process for creating a custom
system image which drastically reduces initialization time.
|                      command                      |  no image |  with image |
|---------------------------------------------------|-----------|-------------|
| experiments/AtmosLES/dycoms.jl --help             |   31.44s  |       2.5s  |
| experiments/AtmosLES/dycoms.jl                    |  244.03s  |    138.64s  |
| test/Numerics/DGmethods/Euler/isentropicvortex.jl |  229.62s  |    144.19s  |
I have
> Add instructions for creating custom system image

- .dev/climaformat.jl
This is better for my work flow than the pre-commit hook. @charleskawczynski likes it too.
I have
> Add old `.dev/format.jl` capability into `.dev/climaformat.jl`

- src/Numerics/DGmethods/DGmodel.jl
This is a fix for the restart functionality, the create_state function would cause an exit with an error saying the function does not exist, I've replaced it with create_conservative_state and restarting works again.
@simonbyrne @kpamnany @akshaysridhar
> fixed restart minor bug

- azure-pipelines.yml
I have no idea why this is failing, but it is.
I have
> disable sysimg script on Windows CI

- Manifest.toml
- docs/Manifest.toml
- docs/src/Theory/Atmos/EDMFEquations.md
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/ref_state.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/gcm_driver_test.jl
- test/Numerics/DGmethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGmethods/compressible_Navier_Stokes/density_current_model.jl
- test/Numerics/DGmethods/compressible_Navier_Stokes/ref_state.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
- Removes `LinearTemperatureProfile` and replaces its use with `DecayingTemperatureProfile`
I have
> Remove LinearTemperatureProfile, switch to DecayingTemperatureProfile

- docs/list_of_how_to_guides.jl
- docs/src/HowToGuides/Atmos/TemperatureProfiles.md
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/ref_state.jl
- src/Atmos/TemperatureProfiles/TemperatureProfiles.jl
- src/ClimateMachine.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/gcm_driver_test.jl
- test/Numerics/DGmethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGmethods/compressible_Navier_Stokes/density_current_model.jl
- test/Numerics/DGmethods/compressible_Navier_Stokes/ref_state.jl
- test/Numerics/DGmethods/courant.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
This PR pulls the `TemperatureProfile`'s out of the AtmosModel into its own module. This makes plotting in the docs not require using `VariableTemplates`. Also, we may share these profiles in the thermo test suite. This also adds plots of each profile in the docs.
I'm agnostic as to where this module and the corresponding docs should go. @kpamnany and @simonbyrne feel free to make suggestions!
I have
> Moves temperature profiles to separate module

- src/Driver/solver_configs.jl
When the hyperviscosity terms were added a while ago, so was the `diffusion_direction` argument to `DGModel`. This was never taken into account in the driver and was therefore missed. This ensures the diffusion direction argument is passed to the slow solver, which is where we want _all_ diffusion to be handled!
Note sure if this fixes #1047, but it was definitely causing problems when using multirate rate together with hyperviscosity.
I have
> Driver hotfix: Pass diffusion direction to the slow dg model for multirate methods

- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
Added these at some point when debugging, turns out they aren't necessary. Code is cleaner without doing this.
I have
> Remove unnecessary zero initializations in HBModel

- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_core.jl
- src/Diagnostics/atmos_default.jl
- src/Driver/Driver.jl
- Don't try and compute `cld_*` diagnostics in `DryModel`s. 🙄 
- Run diagnostics collection at `t0` apart from the specified intervals (like VTK does).
- Run VTK collection at `timeend` apart from the specified intervals (like diagnostics does).
I have
> Diagnostics and VTK fixes+adjustments

- docs/src/GettingStarted/Atmos.md
Removing `LinearTemperatureProfile ` from docs.  This was missed in #1057.
I have
> Fix ref state docs

- src/Utilities/VariableTemplates/VariableTemplates.jl
- src/Utilities/VariableTemplates/var_names.jl
- test/Utilities/VariableTemplates/ntuple_type.jl
- test/Utilities/VariableTemplates/runtests.jl
This PR allows for `VariableTemplates` to work with `NTuple` types. Example:
```julia
struct SingleType{FT} end
struct NTupleType{FT} end
Base.@kwdef struct Container{FT, N}
ntuple_type::NTuple{N,NTupleType{FT}} = ntuple(i->NTupleType{FT}(), N)
single_type::SingleType{FT} = SingleType{FT}()
end
vars_state(m::NTupleType, FT) = @vars(a::FT, b::SVector{3,FT})
vars_state(m::NTuple{N,NTupleType}, FT) where {N} = Tuple{ntuple(i->vars_state(m[i], FT), N)...}
vars_state(::SingleType, FT) = @vars(a::FT)
function vars_state(m::Container, FT)
@vars(single_type::vars_state(m.single_type, FT),
ntuple_type::vars_state(m.ntuple_type, FT)
);
end
```
This also provides support for `flattenednames`. This is needed for the EDMF model, which will have multiple updrafts.
Co-Authored by @simonbyrne. Thanks for …
> Add support for NTuple types in VariableTemplates

- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- tutorials/Land/Heat/heat_equation.jl
This PR fixes some signs in the second-order fluxes, and fixes a small bug in `get_vars_from_element_stack`.
Thanks for catching the bug in `get_vars_from_element_stack` @ilopezgp! And thanks for fixing @kpamnany!
I have
> Fix bug in `get_vars_from_element_stack` and sign in heat eq tutorial

- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Driver/Driver.jl
- tutorials/Microphysics/ex_1_saturation_adjustment.jl
- tutorials/Microphysics/ex_2_Kessler.jl
- tutorials/Numerics/DGmethods/nonnegative.jl
Only create top-level prefix path on rank 0 of a communicator group to prevent output race conditions.  This doesn't impact unit tests because they are run sequentially, but slurm-ci tests have issues if multiple concurrent tests are scheduled to write to a common prefix.  We'll need to also change slurm-ci so that jobs don't write to a common prefix for test output.
Closes #1114 
I have
> Init shared path prefix from a single rank before run

- docs/src/index.md
Removes a broken ref on the landing page.
I have
> Remove broken ref on landing page

- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
Turns out these zero initializations are needed for the initial CFL condition calculations, so I'm reverting #1142 
I have
> Revert PR #1142

- experiments/AtmosLES/bomex.jl
Rolls back BOMEX driver to use 1D-IMEX method.	
```modified:   experiments/AtmosLES/bomex.jl```
While pending issues with MRRK interactions with physics and boundaries are addressed, this is the stable solution.
> 1) Revert BOMEX to use IMEX timestepper

- src/Numerics/LinearSolvers/ColumnwiseLUSolver.jl
- test/Numerics/LinearSolvers/bandedsystem.jl
- test/Numerics/LinearSolvers/columnwiselu.jl
This refactors the LU columnwise linear solver code. The main idea is to have  a single
function where the various size parameters of the matrix have to be specified and to avoid having to
pass `DGmodel` around. Since those parameters have to known statically for GPU performance they are stored in type domain, which has the benefit of simplifying many kernel calls.
I have
> Refactor columnwise LU code

- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
- src/Ocean/HydrostaticBoussinesq/SimpleBoxProblem.jl
Makes things make more physical sense and imposing boundary conditions easier.
I have
> Reverse sign of gradient flux states in HB Model

- src/Diagnostics/diagnostic_fields.jl
- test/Diagnostics/diagnostic_fields_test.jl
Changes to interfaces for vector gradient and vorticity computation:
- Remove use of `ClimateMachine.array_type()` to determine device array;
use state array location instead.
- Rename constructors appropriately.
- Remove unnecessary parameters.
- Use correct interfaces to determine number of nodal points and number
of elements.
I have
> Small fixes for vorticity computation

- src/Common/MoistThermodynamics/relations.jl
- src/Common/MoistThermodynamics/states.jl
- test/Common/MoistThermodynamics/profiles.jl
- test/Common/MoistThermodynamics/runtests.jl
- tutorials/Microphysics/KinematicModel.jl
- tutorials/Microphysics/ex_1_saturation_adjustment.jl
- tutorials/Microphysics/ex_2_Kessler.jl
Since `liquid_frac` really depends on whether the phase is in equilibrium or not, we need to pass this information down from the constructors. In this PR, `ThermodynamicState`'s are passed down to inform which state is being constructed.
Co-authored by: @kpamnany, @trontrytel and @tapios 
I have
> Method dispatch on `liquid_frac` based on thermodynamic state type

- .dev/climaformat.jl
- docs/src/DevDocs/DiagnosticVariables.md
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/surfacebubble.jl
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_les_core.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/dump_state_and_aux.jl
- src/Diagnostics/groups.jl
- src/Diagnostics/helpers.jl
- src/Diagnostics/thermo.jl
- src/Diagnostics/variables.jl
- src/InputOutput/Writers/Writers.jl
- src/InputOutput/Writers/jld2_writer.jl
- src/InputOutput/Writers/netcdf_writer.jl
- src/Numerics/Mesh/Interpolation.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Diagnostics/runtests.jl
- test/Diagnostics/sin_test.jl
- test/InputOutput/Writers/runtests.jl
- test/Numerics/Mesh/interpolation.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
- tutorials/Land/Heat/heat_equation.jl
This adds a GCM diagnostics group. [These](https://github.com/CliMA/ClimateMachine.jl/blob/ln/new-dgngrp/src/Diagnostics/atmos_gcm_default.jl#L38-L67) diagnostics are currently in this group. Attributes have been added to the NetCDF files to comply with the CF convention. 
Some refactoring of the Diagnostics module accompanies this. Also:
- Includes #1082.
- Closes #1165.
Some remaining things will be addressed in subsequent PRs:
- Density weighting.
- More diagnostics:
- Variances and covariances
- Means/covariances based time-window convolution (e.g. Lanczos filtering)
- Horizontal divergence, streamfunction (from the Laplacian of vorticity), potential vorticity
- Ability for user-defined diagnostics (general kernels for gradients, etc.) 
- Aggregation of files using unlimited time …
> GCM diagnostics

- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
See title. Much safer than hardcoded indices. 
I have
> Use varsindex instead of hard-coded indices in HBModel

- docs/list_of_tutorials.jl
- docs/pages_helper.jl
This PR assembles the tutorials array, and then grabs, flattens and transforms their paths so that they can be filtered and fed into Literate. This reduces the redundancy between the array and list of tutorial files.
I have
> Automate tutorial files from pages array

- src/Atmos/TemperatureProfiles/TemperatureProfiles.jl
- test/Atmos/TemperatureProfiles/runtests.jl
- test/Atmos/runtests.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- Fixes reference state definition for `DecayingTemperatureProfile`.
- Adds tests for hydrostatic balance for all temperature profiles
- Updates expected solution in `test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl`
Should close #1183
Co-authored with: @tapios 
I have
> Fix reference state definition, add tests

- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/AtmosLES/taylor-green.jl
- experiments/OceanBoxGCM/homogeneous_box.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Driver/Driver.jl
Separates out cli argument processing from `ClimateMachine.init()` by defining a new method `ClimateMachine.cli()` that parses arguments and initializes ClimateMachine runtime.  `ClimateMachine.init()` is preserved to allow for programmatic initialization when command line parsing is not needed (tests / notebooks / scripts).  `ClimateMachine.cli` and `ClimateMachine.init` now take keyword arguments to allow for easy overloading for `ClimateMachine.Settings` at configuration / runtime.  The experiment files have been updated to use `cli`, the tutorials I kept the same. 
Consistent overloading fallback behaviour is also defined: 
1. cli arguments (if applicable)
2.  keyword argument overloads
3. `CLIMATEMACHINE_SETTINGS_<VALUE_NAME>` process environment definitions
4. …
> Separate cli arg parsing from initialization

- docs/src/HowToGuides/Atmos/TemperatureProfiles.md
- docs/src/HowToGuides/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
- Refactors thermodynamic profiles
- Adds a struct to hold fields, which can be re-used for dry, equilibrium moist, and non-equilibrium moist profiles
- Adds `has_condensate` and `condensate` convenience methods to ensure consistent tolerances between different `liquid_fraction` behaviors
- Use `DecayingTemperatureProfile` to test thermodynamics
- Adds plots of thermodynamic profiles to docs
This PR should be non-behavior changing and will take some of the weight off of #1050.
I have
> Refactor thermo profiles, add plots to docs

- .dev/systemimage/climate_machine_image.jl
- azure-pipelines.yml
Drop test macro, just execute script. move into a sep build stage
I have
> Fix pre-compilation test, run unit tests with built system image 

- experiments/AtmosGCM/heldsuarez.jl
- experiments/OceanBoxGCM/homogeneous_box.jl
- experiments/OceanBoxGCM/ocean_gyre.jl
- src/Driver/SolverTypes/ExplicitSolverType.jl
- src/Driver/SolverTypes/IMEXSolverType.jl
- src/Driver/SolverTypes/MISSolverType.jl
- src/Driver/SolverTypes/MultirateSolverType.jl
- src/Driver/SolverTypes/SolverTypes.jl
- src/Driver/driver_configs.jl
- src/Driver/solver_configs.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/gcm_driver_test.jl
- test/Ocean/HydrostaticBoussinesq/test_divergence_free.jl
- test/Ocean/HydrostaticBoussinesq/test_ocean_gyre.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
This PR does the following:
- It moves current time-stepping solver types into their own self-contained directory, but with the intention of being used specifically with the driver. The rationale behind this: the stream of `if elseif elseif elseif...` is not sustainable in the long term and one can EASILY imagine this getting way out of hand when adding more time-stepping wrappers.
- I've added discrete splitting types to be used with the solver types: (1): `SlowFastSplitting()` which is designed to be simple splitting of fast (acoustic in all directions) and slow (everything else). And (2): `HEVISplitting()` - this splitting will split the acoustic part into horizontal and vertical parts. The vertical part is implicitly treated while all other tendencies are explicit.
- It extends the …
> Driver update: Solver types for explicit, IMEX, multirate, and MIS methods

- src/Driver/driver_configs.jl
The land model uses `z_min < 0` and, while we support `z_min < 0` in the configuration, no domain minimum information is printed. This PR adds a print for `domain_min` to the single stack driver, as this will be used in the land and ocean model where `z_min < 0`.
I have
> Add domain min to single stack driver info

- README.md
This PR fixes the README azure badge links. (this broke when we changed the CI name to `azure-ci`)
I have
> Fix README azure badge links

- src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
- test/Numerics/ODESolvers/ode_tests_common.jl
Adding these to more easily compare against existing DG ocean models.
I have
> Add two forms of Heun's method as SSPRK solvers

- docs/make.jl
- src/Driver/Driver.jl
- src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
The logger is not playing nice with Documenter.jl and Literate.jl (we're seeing `Base.IOError("stream is closed or unusable", 0)` exceptions). This PR fixes this issue by disabling the logger for tutorials.
- Adds a check for `ENV["DISABLE_CUSTOM_LOGGER"]` in `init` in `Driver.jl`
- Sets `ENV["DISABLE_CUSTOM_LOGGER"] = "OFF"` in `docs/make.jl`
Closes #1190
I have
> Add disable_custom_logger option to Driver

- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Utilities/VariableTemplates/varsindex.jl
This PR:
- Adds `varsindices`, a refactored version of the indexing functionality needed
in #1182 moved to `VariableTemplates` for general use
- Adds mulit-argument method of `varsindex` for getting indices of submodel variables
I have
> Add varsindices

- docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
- docs/src/HowToGuides/Numerics/ODESolvers/Timestepping.md
- src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
- test/Numerics/ODESolvers/ode_tests_basic.jl
- test/Numerics/ODESolvers/ode_tests_common.jl
- test/Numerics/ODESolvers/ode_tests_convergence.jl
This PR adds two simple 2-stage IMEX-RK methods.
These will be potentially useful for multirate methods, where we want to resolve the acoustic waves using a low-order IMEX (horizontally explicit, vertically implicit) scheme.
I have
> Add two low-order, 2-stage IMEX methods

- .dev/systemimage/climate_machine_image.jl
By moving the line `Pkg.add("PackageCompiler")` to before activating
`ClimateMachine` we avoid having it get added to `ClimateMachine.jl`s
`Project.toml` and `Manifest.toml`
> Move add of `PackageCompiler` in sys image script

- .github/workflows/CompatHelper.yml
- .github/workflows/Coverage.yaml
- .github/workflows/Documenter.yaml
- .github/workflows/JuliaFormatter.yml
- docs/src/GettingStarted/Installation.md
Port the last of the CI checks to use 1.4, closes #1061 
I have
> bump existing github actions to use julia 1.4

- .github/workflows/JuliaFormatter.yml
- bors.toml
- src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
#1136 introduced a formatter error. This fixes it and adds the formatter to the bors checklist.
I have
> fix format, add formatter to bors

- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/AtmosLES/taylor-green.jl
- src/Arrays/MPIStateArrays.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/filters.jl
- src/Numerics/Mesh/Filters.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/Mesh/filter.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
- tutorials/Microphysics/ex_2_Kessler.jl
- tutorials/Numerics/DGMethods/nonnegative.jl
This adds hooks to modify filtered variables before application of the filter, which is
needed for filtering only the perturbations from the reference state.
Closes #1161
I have
> Add filter targets and filter perturbations in Held-Suarez

- src/Numerics/Mesh/Interpolation.jl
- test/Numerics/Mesh/interpolation.jl
Due to a formatting error, bottom lines of a multi-line statement are ignored. This bug is fixed.
I have
> Bug fix for v_lat component (interpolation)

- docs/list_of_tutorials.jl
- docs/src/Contributing.md
- tutorials/Atmos/dry_rayleigh_benard.jl
- tutorials/Atmos/risingbubble.jl
- tutorials/Diagnostics/Debug/StateCheck.jl
- tutorials/Land/Heat/heat_equation.jl
- tutorials/Numerics/DGMethods/nonnegative.jl
- tutorials/Numerics/SystemSolvers/bgmres.jl
- tutorials/Numerics/SystemSolvers/cg.jl
- tutorials/topo.jl
Some of the tutorials do not generate valid markdown. This PR attempts to make them generate valid markdown and removes them from the docs and many take too long to run (#1233). The upside is that all of them are still tested in slurm. We can add these tutorials back into the docs once they've been tested to generate valid markdown and finish in a reasonable amount of time.
Supercedes #1181. Another step towards #1189 !
I have
> Fix docs and remove slurm-tested broken tutorials from docs

- src/Driver/Driver.jl
I made the incorrect assumption that when a boolean flag is not defined on the CLI it's argument value is not defined in the parsed_args dictionary.  This fixes the `ClimateMachine.cli()` behavior to fallback to using the correct default ordering (defined kw args with calling `cli()`, env variable, original global setting struct). 
Closes #1238
I have
> use store_const for boolean flags define fallback behavior to defaults

- tutorials/Atmos/burgers_single_stack.jl
Fix equation formatting in burgers single stack tutorial (adds line breaks to the equations).
I have
> Fix formatting in burgers single stack tutorial

- .github/workflows/Linux-UnitTests.yml
- .github/workflows/OS-UnitTests.yml
@kpamnany pointed out that there are some sporadic `EEXIST` errors in some `runmpi` tests when decomposed as part of the build matrix.  Add explicit `Pkg.precompile` step to build stage to see if this fixes the possible race issue.
I have
> add separate precompile step for unit build matrix

- .github/workflows/Documenter.yaml
- docs/clean_build_folder.jl
- docs/list_of_tutorials.jl
- docs/make.jl
Generating the tutorial output when building the documentation can take a long time, so enable parallel generation of literate output.   This should not impact normal single core builds (ex. `julia --project=docs/ docs/make.jl`).
I have
> generate tutorial output in parallel

- src/Atmos/Model/turbulence.jl
- tutorials/Atmos/densitycurrent.jl
- tutorials/Atmos/risingbubble.jl
* This is an updated replacement of [#1151](https://github.com/CliMA/ClimateMachine.jl/pull/1151/). Uses Vreman model. 
* This test runs to completion in 3 minutes of wallclock.
* Updates turbulence model to correct multiplier bug-fix. 
I have
> Added densitycurrent.jl at 100m resolution

- docs/list_of_tutorials.jl
- docs/src/APIs/Atmos/AtmosModel.md
- tutorials/Atmos/agnesi_hs_lin.jl
- tutorials/Atmos/agnesi_nh_lin.jl
- tutorials/Atmos/risingbubble.jl
This draft PR is for:
1) linear hydrsotatic gravity waves: Case 6 in [1] 
2)non-linear hyrostatuc gravity waves: Section 5.2.5. Nonlinear Hydrostatic Flow in [2]
3)  removed experiments/AtmosLES/equilibrium.jl --> there will be a PR for this alone.
From this tutorial you will also see how a mountain is added by looking for the function `warp_agnesi` in tutorial/Atmos/agnesi_*
**References:**
[1] Giraldo and Restelli (2007) A study of spectral element and discontinuous Galerkin methods for the Navier–Stokes equations in nonhydrostatic mesoscale atmospheric modeling: Equation sets and test cases, J. Comput. Phys. 227
[2] Restelli PhD thesis
I have
> Mountain gravity waves: linear hydrostatic and non-hydrostatic

- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
CI is currently broken. This PR attempts to fix the broken experiments by reverting some changes from #1050. #1050 should have failed CI, and so these changes never should have gotten in. I've also removed the `@print` statements in case this is somehow responsible for swallowing kernel errors.
Hopefully closes #1272.
I have
> Revert Thermo changes to fix CI

- docs/src/APIs/Atmos/AtmosModel.md
- docs/src/APIs/Diagnostics/Diagnostics.md
- experiments/AtmosGCM/heldsuarez.jl
- src/Atmos/Model/ref_state.jl
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_les_core.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/atmos_refstate_perturbations.jl
- src/Diagnostics/dump_aux.jl
- src/Diagnostics/dump_state.jl
- src/Diagnostics/groups.jl
- src/Diagnostics/variables.jl
Currently requires that an [`InterpolationConfiguration`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Driver/diagnostics_configs.jl#L12-L16) be provided.
Add it to your experiment's diagnostics configuration the usual way (e.g. [BOMEX](https://github.com/CliMA/ClimateMachine.jl/blob/master/experiments/AtmosLES/bomex.jl#L464-L479), but with an `InterpolationConfiguration` specified, as in [Held Suarez](https://github.com/CliMA/ClimateMachine.jl/blob/master/experiments/AtmosGCM/heldsuarez.jl#L185-L201)).
Closes #1225.
I have
> Diagnostics group for perturbations from reference state

- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
- Adds thrown exceptions to Thermodynamics when convergence fails.
- Uses `@test_throws` to ensure that exceptions are thrown when expected (tested with low `maxiter` and small tolerance)
Should fix part 1 of #1274.
@vchuravy is this sufficient to ensure that errors are fatal in kernel calls?
I have
> Add exceptions to thermo for failed convergence

- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
This PR updates the relative humidity function, which was reverted in #1273.
Now that #1275 has been merged, this PR should see the driver failures that #1050 did not see.
Closes #1274.
I have
> Update Thermo humidity function

- docs/src/APIs/Numerics/DGMethods/DGMethods.md
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
Adds a 6-argument form `f(du, u, param, t, α, β)` to the DG evaluation that computes
du .= α .* f(u, param, t) .+ β .* du
which will be used by the new timestepping interface.
See https://github.com/SciML/DifferentialEquations.jl/issues/615
I have
> Add scaled-increment interface to main DG evaluation

- src/Arrays/MPIStateArrays.jl
- src/Diagnostics/Debug/StateCheck.jl
- src/Diagnostics/atmos_les_default.jl
- src/Numerics/Mesh/BrickMesh.jl
This allows the use of non-MPI types in ClimateMachine (such as `DoubleFloat`)
> Use generic functions instead of MPI specific ones

- src/Atmos/Model/AtmosModel.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
- Moves `turbulence_tensors` wrapper to `AtmosModel`
- Add `SingleStackConfigType` to `AtmosModel` initialization
I have
> Fix turbulence_tensors call, add single stack to Atmos init

- docs/src/HowToGuides/Common/Thermodynamics.md
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
Thermodynamics currently has no GPU tests. It would be nice to ensure that all thermo constructors, and `fun(::ThermodynamicState)` methods, work on the GPU. This PR makes `profiles` use given `ArrayType`'s, which should have the flexibility to reside on the GPU.
I have
> Prep thermodynamics for gpu unit tests

- src/Driver/Driver.jl
A one line change to src/Driver/Driver.jl that fixes call to cb_vtk. It looks like this fix was missed in #1224 
I have
- [ x] Written and run all necessary tests with CLIMA by including `tests/runtests.jl`
- [ x] Followed all necessary [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) and run `julia .dev/climaformat.jl .`
- [ x] Updated the documentation to reflect changes from this PR.
> sync cb_ctk with #1224

- docs/src/APIs/Diagnostics/Diagnostics.md
- experiments/AtmosLES/surfacebubble.jl
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_les_default_perturbations.jl
- src/Diagnostics/groups.jl
For LES configurations. Requires that an `InterpolationConfiguration` be provided. Added to the surface bubble experiment for testing.
Closes #1243.
I have
> Diagnostics group for perturbations from horizontal averages

- src/Atmos/Model/ref_state.jl
- src/Common/Thermodynamics/relations.jl
- test/Atmos/Model/ref_state.jl
- test/Atmos/Model/runtests.jl
- test/Atmos/runtests.jl
This PR
- Was split off from #1050
- Updates the atmospheric reference state using newly added functions from #1050
- Adds unit tests for the reference state
- Tests state for thermodynamic consistency (with ideal gas law)
- Tests that relative humidity in reference state is approximately equal to the input relative humidity
Closes #882
I have
> Update atmos reference state

- .github/workflows/Documenter.yaml
- .github/workflows/doc_build_common_error_messages.md
Adds a markdown file of common doc build error messages, and hints of what is wrong / how to fix it, to the `.github/workflows/` folder.
Disclaimer: this was my personal "cheat sheet" that I've been using while fixing docs. I don't know how accurate/precise it is, but perhaps we can update it as users come across mistakes.
I have
> Add doc build common error messages

- docs/make.jl
Doing `makedocs(linkcheck = true, strict = true)` as we were previously doing will cause CI to fail if any of the linked sites is temporarily down or if any link breaks. While we do want to check the links periodically, we can't allow CI to depend on `n` external sites.
I have
> Disable `linkcheck` for `docs-build`

- src/Driver/Driver.jl
- test/Driver/driver_test.jl
> Validate `ClimateMachine.init()` keyword arguments

- experiments/AtmosLES/schar_scalar_advection.jl
- slurmci-test.toml
Adds experiment: Schar mountain scalar advection over topography.  
Uses single tracer with zero diffusion coefficient. 
new file:   experiments/AtmosLES/schar_scalar_advection.jl
I have
> Additional benchmark experiment. Passive scalar advection over topography feature.

- docs/plothelpers.jl
- docs/src/HowToGuides/Common/Thermodynamics.md
- src/Common/Thermodynamics/Thermodynamics.jl
- src/Common/Thermodynamics/relations.jl
For some strange reason, after rebasing and pushing #551, apparently, the delta (changes against master) was 0 and the PR was automatically closed. This PR re-applies what was in #551:
- Adds plots showing space of converged & non-converged saturation adjustment for permutations of the inputs to thermodynamic constructors
- Adds a plot-helper that bins the 3D plot into several 2D scatter plots.
I have
> Add input space plots to thermo constructors

- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
This PR:
- Replaces `create_hypervisc_indexmap` with a simple application of `varsindices`
- Passes the resulting mapping as a compile time constant to get rid of local memory accesses on the GPU (resulting
from indirect addressing of the form `A[B[i]]`) which improves performance
> Simpler calculation of hyperdiffusive variables indices

- src/Driver/Callbacks/Callbacks.jl
- src/Driver/Driver.jl
- src/InputOutput/VTK/writepvtu.jl
- src/InputOutput/VTK/writevtk.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGMethods/Euler/acousticwave_mrigark.jl
- test/Numerics/DGMethods/Euler/isentropicvortex.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl
- test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model_1dimex_bgmres.jl
- test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl
- test/Numerics/DGMethods/advection_diffusion/periodic_3D_hyperdiffusion.jl
- test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion.jl
- test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_1dimex.jl
- test/Numerics/DGMethods/advection_diffusion/pseudo1D_advection_diffusion_mrigark_implicit.jl
- test/Numerics/DGMethods/advection_diffusion/pseudo1D_heat_eqn.jl
- test/Numerics/Mesh/min_node_distance.jl
- tutorials/Numerics/DGMethods/nonnegative.jl
Previously only VTK output at the LGL nodes was supported, this allows interpolation to an equidistant grid of points which allows for better visualization.
Co-authored-by:  Thomas Gibson <thomas.gibson@nps.edu>
> Allow equispaced output in VTK

- src/Atmos/Model/filters.jl
This PR implements subtraction of specific humidity reference state in the `AtmosFilterPerturbations` target.
Closes #1348.
> Remove q_tot reference state when filtering

- Manifest.toml
- Project.toml
- src/InputOutput/VTK/writemesh.jl
Closes #1282 with suggested fix.
I have
> Upgrade WriteVTK

- src/Atmos/Model/AtmosModel.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
The EDMF model needs to estimate the updraft top, which requires computing an integral. This PR adds the `turbconv` integral hooks to the AtmosModel.
I have
> Add turbconv integral hooks to AtmosModel

- src/Atmos/Model/radiation.jl
In the EDMF branch, we found that the upward/downward calls to [integral_load_auxiliary_state! and integral_set_auxiliary_state!](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/AtmosModel.jl#L611-L641) do not match the [method signature for the default radiation model](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/radiation.jl#L14-L35). This PR corrects this bug. We haven't had any issues because, currently, no models that use the `RadiationModel` have integrals (i.e., [num_states](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/AtmosModel.jl#L573) is always false), and so we've not yet hit this problem.
I have
> Fix integral kernel args in `RadiationModel `

- docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
- src/Diagnostics/groups.jl
- src/Driver/Callbacks/Callbacks.jl
- src/Driver/Driver.jl
- src/Numerics/ODESolvers/GenericCallbacks.jl
- src/Numerics/ODESolvers/ODESolvers.jl
- test/Numerics/ODESolvers/callbacks.jl
@akshaysridhar discovered that #1299 wasn't a sufficient fix (the final argument `t` is required and cannot be `nothing`). Then I saw that `call!`ing the VTK callback at finish checks if the requisite interval has expired first. So I added `fini!()` as a cleaner solution.
This should restore the original behavior for VTK and for diagnostics, i.e.:
1. Collect at `t0`.
2. Collect at specified intervals.
3. Collect at `timeend`.
If anyone prefers different behavior, please speak up!
This does not solve #1310 and #1085 will require further tweaks.
Closes #1376.
I have
> Add `GenericCallbacks.fini!()`

- docs/src/APIs/Utilities/VariableTemplates.md
- src/Utilities/VariableTemplates/VariableTemplates.jl
- src/Utilities/VariableTemplates/flattened_tup_chain.jl
- test/Utilities/VariableTemplates/runtests.jl
- test/Utilities/VariableTemplates/test_complex_models.jl
Debugging highly nested models (e.g., EDMF) is difficult because, at the moment, checking fields in all sub-models requires manually writing out all fields/subfields, or writing recursive `getproperty`/`getindex` methods, which is painful/overkill just for debugging. This PR adds a method `flattened_tup_chain`, along with a recursive and interleaved `getindex`/`getproperty`, to `VariableTemplates` so that users can iterate through every field in compute kernels in a convenient way, as demonstrated in a new test in the test suite:
```julia
ftc = flattened_tup_chain(st)
@test ftc[1] === (:ntuple_model, 1, :scalar_model, :x)
@test ftc[2] === (:ntuple_model, 2, :scalar_model, :x)
@test ftc[3] === (:ntuple_model, 3, :scalar_model, :x)
@test ftc[4] === (:vector_model, :x)
@test ftc[5] === …
```
> Add `flattened_tup_chain ` and chained getproperty/getindex methods

- src/Atmos/Model/AtmosModel.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_refstate_perturbations.jl
- src/Diagnostics/dump_aux.jl
- src/Diagnostics/dump_state.jl
- src/Diagnostics/helpers.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
- src/Numerics/DGMethods/NumericalFluxes.jl
- src/Numerics/DGMethods/create_states.jl
- src/Numerics/DGMethods/remainder.jl
- src/Numerics/SystemSolvers/columnwise_lu_solver.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/SplitExplicit/Communication.jl
- src/Ocean/SplitExplicit/HydrostaticBoussinesqCoupling.jl
- test/Atmos/Model/ref_state.jl
- test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model.jl
- test/Numerics/DGMethods/remainder_model.jl
@jkozdon pointed out that `number_states` doesn't actually need the float type. So, this PR does some house-cleaning and removes `FT` in calls to `number_states`.
I have
> Remove unused arg in number_states calls

- src/Numerics/Mesh/Filters.jl
Fix suggested by @jiahe23 in issue #1391.
I have implemented the correction suggested by @jiahe23 in issue #1391
> Fixed Boyd_Vandeven filter bug

- docs/src/GettingStarted/RunningClimateMachine.md
- src/BalanceLaws/interface.jl
- src/Diagnostics/diagnostic_fields.jl
- src/Diagnostics/dump_aux.jl
- src/Diagnostics/groups.jl
- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/create_states.jl
If this is specified, fill state arrays with NaNs on creation and write auxiliary and prognostic state arrays to VTK files immediately after they are initialized.
Closes #1213. Closes #1343.
I have
> Add `--debug-init`

- docs/plothelpers.jl
- tutorials/Atmos/burgers_single_stack.jl
- tutorials/Land/Heat/heat_equation.jl
- Remove unused methods in `docs/plothelpers.jl` (which were originally there for use with Revise.jl)
- Remove `export_plot_snapshot`, and just use `export_plot`
- Remove abstract `param_set` type in `HeatModel`, since this is not GPU friendly (thanks @ilopezgp!)
- Fix docs
- Clarify meaning of `bctype` (thanks @kmdeck!)
Thanks @blallen for general help with BCs!
I have
> Improve and clarify heat eq tutorial

- src/Driver/SolverTypes/MISSolverType.jl
- src/Driver/SolverTypes/MultirateSolverType.jl
Add curly brackets to equation text that should be subscript. See the [relevant docs](https://clima.github.io/ClimateMachine.jl/latest/APIs/Driver/#ClimateMachine.MISSolverType) for current behavior.
I have
> docs: fix subscripts on math equations in Driver/SolverTypes/

- tutorials/Atmos/burgers_single_stack.jl
Added divergence damping and model orientation
Added 2D divergence damping horizontal flow, model orientation for correct projections and changed the timescale of the problem for more relevant output.
I have
> Added divergence damping and model orientation

- docs/plothelpers.jl
- tutorials/Atmos/burgers_single_stack.jl
This PR fixes the legend of the _solution_vs_time.png_ plot, rounding the time shown to two digits.
I have
> Fix plot legend in plothelpers.jl

- slurmci-test.toml
- src/Utilities/Checkpoint/Checkpoint.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
- test/Ocean/SplitExplicit/test_restart.jl
The split-explicit solver used for the Ocean requires two sets of state and aux variables to be stored in order to restart properly. We extended `write_checkpoint()` to enable this and then put in a simple version of what is done in the Driver to our script. (This method will be added as a driver once all parts have been ported over). 
I have
> Hack in writing and reading checkpoint files for split-explicit method

- docs/src/GettingStarted/RunningClimateMachine.md
- docs/src/HowToGuides/Numerics/DGMethods/how_to_make_a_balance_law.md
Fix some missed name change from `conservative` to `prognostic` in docs.
I have
> Fix missed `conservative` -> `prognostic` rename in docs.

- experiments/AtmosGCM/moist-baroclinic-wave.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/variables.jl
A typo was fixed to enable saving GCM diagnostics and added the `qi` variable (output tested). 
`experiments/AtmosGCM/moist-baroclinic-wave.jl` is a copy of `baroclinic-wave.jl` with moisture switched on. Perhaps this can be merged into one file once the config interface is cleaned up.
I have
> Minor fixes for moist GCM diagnostics

- docs/src/APIs/Diagnostics/Diagnostics.md
- experiments/AtmosLES/taylor_green.jl
- src/ClimateMachine.jl
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_les_core.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/atmos_les_default_perturbations.jl
- src/Diagnostics/atmos_refstate_perturbations.jl
- src/Diagnostics/atmos_turbulence_stats.jl
- src/Diagnostics/dump_aux.jl
- src/Diagnostics/dump_state.jl
- src/Diagnostics/groups.jl
- src/Diagnostics/variables.jl
- src/Driver/diagnostics_configs.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
Defines a callback for calculating volumetrically averaged dimensionless kinetic energy and dissipation
I have built a module that allows for a callback to calculate volumetrically averaged dimensionless kinetic energy and kinetic energy dissipation. This will be useful as it replaces the tedious procedure of calculating these during post-processing. These represent useful insight into certain turbulence dominated cases like the Taylor-Green vortex.
> Add turbulence statistics diagnostics

- docs/plothelpers.jl
`round_digits` is not actually used in `export_plot`. This PR makes `export_plot` use the `round_digits` input kwarg.
I have
> Make `export_plot` use `round_digits` kwarg

- .buildkite/pipeline.yml
- bors.toml
Switch cluster tests to use Buildkite https://buildkite.com/clima for dynamic CI tests that need to run on CPU / GPU cluster resources.
I have
> Use buildkite to drive slurm cpu/gpu tests

- docs/src/APIs/Driver/index.md
- src/Arrays/MPIStateArrays.jl
- src/Driver/SolverTypes/ImplicitSolverType.jl
- src/Driver/SolverTypes/SolverTypes.jl
- tutorials/Land/Heat/heat_equation.jl
This PR makes the heat tutorial use an implicit time marching method (`Kvaerno3`) from the DiffEq library and adds an implicit solver type to the driver configuration.
At the moment, we cannot use ForwardDiff to approximate the Jacobians. Instead, DiffEq is falling back on finite difference method, which results in more kernel calls. Next, we'd like to see how this implicit method fairs with explicit for a range of thermal conductivities (which varies the stiffness). While I'm working on a preliminary comparison PR, @kanav99 will be trying to get ForwardDiff working with #1291 to reduce the number of kernel calls. Thanks @kanav99 and @thomasgibson for all of your help with time marching!
I have
> Add implicit time marching to heat tutorial

- .buildkite/pipeline.yml
- docs/src/APIs/Atmos/AtmosModel.md
- experiments/AtmosLES/bomex_bulk_sfc_flux.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/bc_moisture.jl
- src/Atmos/Model/boundaryconditions.jl
Add bulk surface flux of moisture and energy to boundaryconditions.
I have
> Add bulk surface flux to boundaryconditions

- bors.toml
> reduce bors timeout from 24 to 3 hours

- docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
- src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/Numerics/ODESolvers/DifferentialEquations.jl
- src/Numerics/ODESolvers/LowStorageRungeKutta3NMethod.jl
- src/Numerics/ODESolvers/LowStorageRungeKuttaMethod.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalGARKDecoupledImplicit.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalGARKExplicit.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalStepMethod.jl
- src/Numerics/ODESolvers/MultirateRungeKuttaMethod.jl
- src/Numerics/ODESolvers/ODESolvers.jl
- src/Numerics/ODESolvers/SplitExplicitMethod.jl
- src/Numerics/ODESolvers/StrongStabilityPreservingRungeKuttaMethod.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/ODESolvers/callbacks.jl
An alternative way to do this that isn't invasive of the `ODESolver` types is to make [this `step`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Numerics/ODESolvers/ODESolvers.jl#L113) a global `const Ref`. Thoughts?
Closes #1419. 
I have
> Add `ODESolvers.getsteps()`

- .buildkite/pipeline.yml
- src/Land/Model/SoilWaterParameterizations.jl
- src/Land/Model/soil_water.jl
- test/Land/Model/Artifacts.toml
- test/Land/Model/haverkamp_test.jl
- test/Land/Model/prescribed_twice.jl
- test/Land/Model/test_bc.jl
This PR does two things
- switched to using Artifacts for data in the haverkamp_test.jl
-  modified haverkamp_test.jl and test_bc.jl to run on the GPU without error.
I have
> fixing issues re: type stability and closures

- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
- test/Driver/driver_test.jl
For performance analysis runs and testing it is often useful to force a fixed
number of time steps. To achieve this is the addition of the keyword
argument `fixed_number_of_steps` to `SolverConfiguration`; this can also
be set with the command line argument `--fixed-number-of-steps`.
If `fixed_number_of_steps < 0` then the original number of steps
(inferred from `tend`) is used, otherwise the number of specified by
`fixed_number_of_steps` is used.
> Add fixed_number_of_steps option to driver

- src/Driver/driver_configs.jl
@LenkaNovak ran into some issues with not being able to specify different BCs for the inner and outer sphere for a GCM configuration. This PR fixes this, so that we can specify different BCs for the inner and outer spheres. Thanks @mwarusz and @jkozdon for help with this!
I have
> Fix GCM config BCs

- src/InputOutput/VTK/writemesh.jl
- test/InputOutput/VTK/runtests.jl
- test/InputOutput/runtests.jl
By switching from `VTK_LINE`, `VTK_PIXEL`, and `VTK_VOXEL` to `VTK_LAGRANGE_CURVE`, `VTK_LAGRANGE_QUADRILATERAL`, and `VTK_LAGRANGE_HEXAHEDRON` the degree of freedom connecting lines are removed from the mesh.
Additionally, there is hope of eventually doing [high-order viz in paraview], but this requires an additional interpolation to an equally spaced mesh. Ideally we would want this done in paraview itself, since then the aliasing errors occur at the interpolation nodes (as in the code)
[high-order viz in paraview]: https://blog.kitware.com/modeling-arbitrary-order-lagrange-finite-elements-in-the-visualization-toolkit/
> Switch VTK to use VTK_LAGRANGE_XXX

- src/Atmos/Model/moisture.jl
@LenkaNovak - This PR adds `q_ice` to the auxiliary state in the `EquilMoist` model. (The `q_liq` was already there). 
I think at least for now for debugging, it would be good to dump and output both. 
I have
> add q_ice to Aux in EquilMoist

- src/Driver/solver_configs.jl
- src/Numerics/DGMethods/create_states.jl
Small fixes as of now for the working of Array Changes by @simonbyrne , but we still need to figure out how to make `array_device` compatible with Duals.
cc: @charleskawczynski 
I have
> Make MPIStateArray AD Compatible

- src/Driver/SolverTypes/IMEXSolverType.jl
- src/Driver/SolverTypes/MISSolverType.jl
- src/Driver/SolverTypes/MultirateSolverType.jl
- test/Driver/gcm_driver_test.jl
A particular code path in the multirate solver driver was never tested, so this particular problem wasn't caught. Basically some stale code in the driver setup wasn't updated. This PR fixes the bug and updates a unit test.
I have
> Bugfix: remove old driver syntax

- src/Arrays/MPIStateArrays.jl
Previously the underlying data array was returned for `fill!` with an
`MPIStateArray`, so that calls like
```julia
B = fill!(A, 0)
```
would return result in `B === A.data` not `B === A` as is standard for
other array types in Julia.
> Fix `fill!` return on an MPIStateArrays

- experiments/AtmosLES/taylor_green.jl
This experiment was breaking after updates to the ref-state design, this PR patches this issue by explicitly specifying the reference state when orientation = `NoOrientation()`. 
I have
> Patch experiment: Taylor-Green Vortex

- experiments/AtmosLES/bomex.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/bc_moisture.jl
Merge temperature and moisture computation functions for energy in bulk surface fluxes. Simplifies #1447.
I have
> Change construction of bulk surface fluxes

- docs/src/APIs/Common/TurbulenceClosures.md
- src/Atmos/Model/AtmosModel.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
Adds a viscous sponge layer to turbulence closures. This sponge later can be used (just like the Rayleigh sponge layer that we already have) to damp waves near the top of the domain. 
`turbconv` and `turbulence` models can be used simultaneously with viscous sponges in this configuration.
I have
> Add ViscousSponge to TurbulenceClosures

- docs/src/APIs/Numerics/DGMethods/DGMethods.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/ref_state.jl
- src/Common/Orientations/Orientations.jl
- src/Driver/solver_configs.jl
- src/Numerics/DGMethods/DGMethods.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
- src/Numerics/DGMethods/create_states.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/HydrostaticBoussinesq/LinearHBModel.jl
- src/Ocean/ShallowWater/ShallowWaterModel.jl
- src/Ocean/SplitExplicit/VerticalIntegralModel.jl
- test/Numerics/DGMethods/grad_test.jl
- test/Numerics/DGMethods/grad_test_sphere.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
- tutorials/Atmos/burgers_single_stack.jl
One problem I ran into (and @jkozdon helped in tracking down), when working on the BOMEX single stack, was that `direction` currently does not propagate to `contiguous_field_gradient!`. As a result, the horizontal components of `orientation.∇Φ`, which should be zero for single stack configurations (and maybe LES configurations? @akshaysridhar), had precision errors which significantly impacted results at `Float32` precision. This PR makes `init_state_auxiliary!` and `contiguous_field_gradient!` direction-aware so that the horizontal components of `orientation.∇Φ` are exactly zero for single stack configurations.
In addition, this PR renames `contiguous_field_gradient!` to `continuous_field_gradient!` and fixes the implementation for when `direction = VerticalDirection()`.
- *Note that …
> Make `init_state_auxiliary!` direction aware

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
Adds a function `saturated` to Thermodynamics, which returns a bool indicating if a given thermodynamic state is saturated or supersaturated.
I have
> Add saturated function to thermo

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
State conservative is no more, `ũc̃⁺` and `ũc̃⁻` were misleading since the superscripts didn't refer to the + and - face.
I have
> Improve names in Roe fluxes

- .buildkite/pipeline.yml
- docs/list_of_apis.jl
- docs/src/APIs/Land/LandModel.md
- docs/src/APIs/Land/SoilHeatParameterizations.md
- src/Land/Model/LandModel.jl
- src/Land/Model/SoilHeatParameterizations.jl
- src/Land/Model/SoilWaterParameterizations.jl
- src/Land/Model/land_bc.jl
- src/Land/Model/soil_bc.jl
- src/Land/Model/soil_heat.jl
- src/Land/Model/soil_model.jl
- src/Land/Model/soil_water.jl
- test/Land/Model/haverkamp_test.jl
- test/Land/Model/heat_analytic_unit_test.jl
- test/Land/Model/prescribed_twice.jl
- test/Land/Model/runtests.jl
- test/Land/Model/test_bc.jl
- test/Land/Model/test_heat_parameterizations.jl
- tutorials/Land/Soil/Water/equilibrium_test.jl
This PR builds on PR 1342 which added the balance law components and boundary condition interface for the soil water model. 
PR 1442 adds the SoilHeatModel to soil_heat.jl, and the functions needed for the balance law for heat conduction and diffusion in the soil (SoilHeatParameterizations.jl). It adds an internal test (test_heat_parameterizations.jl) to test these functions, and a unit test (heat_analytic_unit_test) to verify the analytic solution to the heat equation in dry soil with dirichlet boundary conditions matches CLiMA's numerical solution, using a PrescribedWaterModel, with no ice and no liquid water. No water implies K and C are constant. We also changed the names of certain state variables and parameters to be consistent with variables used across CliMA, and to follow the …
> Adding soil heat model into soil model

- tutorials/Numerics/DGMethods/Box1D.jl
- tutorials/Numerics/DGMethods/showcase_filters.jl
Add mass conservation check filter showcase to show that TMAR is not mass conservative.
I have
> Add mass conservation check to filter showcase

- .buildkite/pipeline.yml
- test/Numerics/SystemSolvers/bgmres.jl
Add GPU unit test execution on Slurm CI
I have
> add GPU unittests to central cluster test pipeline

- .buildkite/pipeline.yml
- docs/Project.toml
- experiments/AtmosLES/bomex_les.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/bomex_single_stack.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- src/Common/TurbulenceConvection/boundary_conditions.jl
This PR adds a BOMEX single stack experiment and splits up the existing BOMEX LES experiment into a shared model file and an LES and single stack experiment files. This PR needs changes coming from #1462 to pass CI. This new experiment should provide a baseline to compare the single stack BOMEX with/without EDMF.
This also modifies the default horizontal domain extent to 50km.
Closes #1356
I have
> Add BOMEX single stack experiment

- src/Utilities/VariableTemplates/VariableTemplates.jl
We want to disallow the following:
```julia
using StaticArrays
using ClimateMachine.VariableTemplates
function vs(FT)
@vars begin
a::FT
end
end
FT = Float64
arr = fill!(MArray{Tuple{3, 1}, FT}(undef), 0)
g = Grad{vs(FT)}(arr)
g.a = 4           # changes arr to [4 4 4]
g.a = [5]         # changes arr to [5 5 5]
```
This is not a perfect solution though, because it will result in the sort of unclear error:
```julia
julia> g.a = 4
ERROR: type Grad has no field a
Stacktrace:
[1] setproperty!(::Grad{NamedTuple{(:a,),Tuple{Float64}},MArray{Tuple{3,1},Float64,2,3},0}, ::Symbol, ::Int64) at ./Base.jl:34
[2] top-level scope at REPL[7]:1
```
close #1457
> Remove implicit broadcast for `Grad`

- src/Atmos/Model/AtmosModel.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
`\tau` is an output of `turbulence_tensors` ; for optional  
upper atmosphere sponges this fixes the viscous stress modifier. 
No effect on existing master branch experiments/ tutorials. 
Independent of the rayleigh linear sponge in `source.jl`
I have
> Bugfix for sponge modifier

- bors.toml
Changes the bors settings to require at least one GitHub approval before merging a PR. This should help make sure all PRs are properly documented and that the PR checklist has *actually* been completed. This is following up on the discussion from the `#software` slack channel.
I have
> Require approval from a reviewer besides the PR author

- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- experiments/AtmosGCM/baroclinic-wave.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosGCM/moist-baroclinic-wave-bulksfcflux.jl
Small fix that refines the GCM ref_state to be more physical, allowing for more stable runs.
I have
> GCM ref_state refinement

- src/Utilities/TicToc/TicToc.jl
> Fix TicToc for Revise

- docs/plothelpers.jl
This PR makes `export_state_plots` work when the grids exist on the GPU (by converting the CuArray to an ordinary array).
I have
> Make plot helpers GPU-friendly

- experiments/AtmosGCM/GCMDriver/baroclinicwave_problem.jl
- experiments/AtmosGCM/GCMDriver/gcm_base_states.jl
- experiments/AtmosGCM/GCMDriver/gcm_moisture_profiles.jl
- experiments/AtmosGCM/GCMDriver/gcm_perturbations.jl
- experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl
Properly set defaults for each GCMDriver experiment when the user does not specify perturbation, base state or moisture profile.
I have
> Set defaults properly for GCMDriver experiments

- Project.toml
- docs/list_of_apis.jl
- docs/list_of_theory_docs.jl
- docs/src/APIs/Atmos/AtmosModel.md
- docs/src/APIs/Atmos/Microphysics_0M.md
- docs/src/Theory/Atmos/Microphysics_0M.md
- experiments/AtmosGCM/baroclinic-wave.jl
- src/Atmos/Model/source.jl
- src/Atmos/Parameterizations/CloudPhysics/Microphysics_0M.jl
- src/ClimateMachine.jl
- test/Atmos/Parameterizations/Microphysics/runtests.jl
This is a draft of precipitation removal scheme for the GCM (aka the 0-moment microphysics scheme).
I have
> Precipitation removal scheme for GCM

- src/Ocean/ShallowWater/bc_velocity.jl
This really should have been in #1456, since it is the last type of velocity boundary condition. Required for running the ocean gyre set up in #1482. Currently just implemented for GPU compilation, a later PR will actually make these useful for applying wall drag in a shallow water simulation.
I have
> Add kinematic stress BC for SWModel

- src/InputOutput/VTK/writemesh.jl
Fixing a bug in the 2D VTK files introduced in PR #1352.
The previous PR inadvertently changed an instance of `vtk_point_data` to `vtk_cell_data`, e.g., format for nodal data to format for cell data.
I have
> Fix 2D vtk bug

- docs/list_of_dev_docs.jl
- docs/src/DevDocs/SystemImage.md
I have been asked about this a few times in the past couple days, so thought it should be in the docs.
I have
> Add documentation for system image

- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Utilities/VariableTemplates/complex_models.jl
- test/Utilities/VariableTemplates/test_complex_models.jl
- test/Utilities/VariableTemplates/test_complex_models_gpu.jl
This PR modifies `varsindex` so that it works with `ntuple` models. For example, with this PR, we can now do
```julia
m = NTupleContainingModel(N, Nv)
st = state(m, FT)
for i in 1:N
i_x = varsindex(st, :ntuple_model, Val(i), :scalar_model, :x)
end
```
I added a `vector_model` to the `NTupleModel` to test for slightly more complicated offsets.
I have
> Make `varsindex` work for ntuple models

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
This PR adds
- `liquid_specific_humidity`
- `ice_specific_humidity`
to Thermodynamics. This may allow us to nicely extend some pieces in the EDMF model (subdomain statistics).
I have
> Add `liquid_specific_humidity` and `ice_specific_humidity` to Thermodynamics

- src/Common/TurbulenceClosures/TurbulenceClosures.jl
Add a separate hyperdiffusion timescale for q_tot, address #1463 
I have
> add hyperdiffusion timescale for q_tot

- docs/src/APIs/Utilities/SingleStackUtils.md
- experiments/AtmosLES/bomex_model.jl
- src/Driver/driver_configs.jl
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- test/Utilities/SingleStackUtils/ssu_tests.jl
This PR
- Adds `horizontally_average!` for single stack utils. This is needed to avoid issues with horizontally-non uniform initial profiles, resulting from `rand()`.
- Adds `hmax` to `SingleStackConfiguration` becuase the Smagorinsky model is scale-aware and causes problems at small (`hmax ~ 1m`) and large (`hmax ~ 50km`) horizontal domains. To avoid holding up the EDMF development, we'll make `hmax` adjustable per driver for now.
- Adds `turbconv` as a kwarg to `bomex_model`.
I have
> Add `horizontally_average!`, `hmax` for single stack, and prep for edmf

- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/Ocean.jl
- src/Ocean/OceanProblems/SimpleBoxProblem.jl
- src/Ocean/ShallowWater/ShallowWaterModel.jl
- test/Ocean/ShallowWater/GyreDriver.jl
Testing #1482 requires running tests with and without temperature advection to test the stability of the averaging scheme (and determine that is specifically temperature advection that is failing and not something else related to temperature). I also went ahead and implemented the same thing for momentum advection because why not. 
There's probably a better version of this where we have a struct for the advection-diffusion equation that is used to turn manipulate both parts (and contains the viscosities/diffusivities). Not sure if it's worth it to go ahead and add that complexity now though.
Also, there is no test for the `::Nothing` case of tracer advection and for the `::NonLinear` case of momentum advection. The former will come in #1482 and the latter will come once we experiment with …
> Add traits to turn on and off advection for tests

- experiments/AtmosLES/stable_bl_kosovic.jl
- experiments/AtmosLES/unstable_bl_kitamura.jl
1) Stable BL (Kosovic and Curry, 2000)
2) Unstable BL (Kitamura and Ito, 2016)
new file:   experiments/AtmosLES/stable_bl_kitamura.jl
new file:   experiments/AtmosLES/unstable_bl_kitamura.jl
This PR adds two experiments, with emphasis on surface fluxes and surface layer dynamics. 
I have
> Additional boundary-layer experiments 

- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- test/Utilities/SingleStackUtils/ssu_tests.jl
Fixes a bug in `horizontally_average!`. That syntax didn't do what I thought.
I have
> Fix horizontal average

- .buildkite/pipeline.yml
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/OceanProblems/SimpleBoxProblem.jl
- src/Ocean/SplitExplicit/HydrostaticBoussinesqCoupling.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
- test/Ocean/SplitExplicit/test_coriolis.jl
Another spinoff from #1482. Depends on #1509. Adds a `rotation` field to the `SimpleBox` problem to turn on and off the Coriolis force in the hydrostatic spindown tests. Need to add state check values after the pretty-tables output is fixed.
I have
> Add rotating spindown test to handling of Coriolis force

- src/Utilities/VariableTemplates/VariableTemplates.jl
After #1458 I noticed a slowdown. This PR proposes a fix.
Running ```julia --project=. experiments/AtmosLES/bomex_les.jl --monitor-timestep-duration 100steps``` I get
Before:
```
┌ Info: Wall-clock time per time-step (statistics across MPI ranks)
│    maximum (s) =    1.5273617989999998e-02
│    minimum (s) =    1.5273617989999998e-02
│    median  (s) =    1.5273617989999998e-02
└    std     (s) =                       NaN
```
After:
```
Info: Wall-clock time per time-step (statistics across MPI ranks)
│    maximum (s) =    1.1554147779999999e-02
│    minimum (s) =    1.1554147779999999e-02
│    median  (s) =    1.1554147779999999e-02
└    std     (s) =                       NaN
```
The fix relies on unexported `StaticArrays` API but https://github.com/JuliaArrays/StaticArrays.jl/pull/474 …
> Use static range in Grad setproperty!

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Atmos/Parameterizations/Microphysics/runtests.jl
- test/Common/Thermodynamics/runtests.jl
This is a wrapper for q_vap_saturation_generic that will be needed in the NonEquilMoist model.
@charleskawczynski
I have
> add q_vap_saturation wrapper for NonEquilMoist model

- docs/src/APIs/Atmos/AtmosModel.md
- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- experiments/AtmosGCM/GCMDriver/gcm_sources.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/stable_bl_kosovic.jl
- experiments/AtmosLES/unstable_bl_kitamura.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/thermodynamics.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_les_core.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/thermo.jl
- test/Driver/mms3.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
Closes #1534
Credit to @kmdeck for finding a more general need for what is now `new_thermo_state`.
I have
> Rename `thermo_state` to `recover_thermo_state`, add `new_thermo_state`

- src/Atmos/Model/boundaryconditions.jl
A proposed fix to the boundary state issue discussed in #1528. Moisture auxiliary variables are updated
in `boundary_state!` to make them consistent with the boundary conditions.
I didn't see any significant performance issues.
I have
> Update moisture auxiliary state in boundary_state!

- docs/src/APIs/Atmos/AtmosModel.md
- experiments/AtmosLES/bomex_les.jl
- experiments/AtmosLES/bomex_model.jl
- src/Atmos/Model/filters.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/ref_state.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/thermodynamics.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/thermo.jl
- src/Diagnostics/variables.jl
This adds a non-equilibrium model of moisture in Atmos by:
- adding two more variables to state (rho_q_liq, rho_q_ice)
- replacing saturation adjustment with relaxation to equilibrium source terms.
@akshaysridhar , @charleskawczynski - could you take a look and check if I'm missing something?
@kpamnany - I included here a draft of possible changes in the diagnostics. It's not the most elegant. Could you also take a look there?
I have
> add NonEquilMoist model to Atmos

- src/Atmos/Parameterizations/CloudPhysics/Microphysics.jl
- src/Common/Thermodynamics/Thermodynamics.jl
- src/Common/Thermodynamics/relations.jl
- src/Common/Thermodynamics/states.jl
I'm splitting the old ice microphysics integration test [PR](https://github.com/CliMA/ClimateMachine.jl/pull/1330) into two separate PRs. This is the first of them and it brings in the additional safeguards against negative microphysics variables `q_vap`, `q_liq` and `q_ice`. 
For `q_liq` and `q_ice` it would happen in `PhasePartition` constructor. For `q_vap` it would happen in its function in `Thermodynamics/relations.jl`.
None of those overwrite the actual state variables. Instead they make sure that the later used thermodynamics and microphysics functions behave as if they get zero as input argument. 
@tapios , @charleskawczynski - Would that be an ok middle step?
I have
> safeguards against negative microphysics values

- docs/src/APIs/Numerics/DGMethods/NumericalFluxes.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Numerics/DGMethods/NumericalFluxes.jl
- test/Atmos/Model/discrete-hydrostatic-balance.jl
- test/Numerics/DGMethods/Euler/isentropicvortex.jl
Co-authored-by: Thomas Gibson <thomas.gibson@nps.edu>
Adds HLLC numerical flux.
I have
> Add HLLC numerical flux

- docs/src/Contributing.md
> Doc skipping tutorials during doc build

- src/Diagnostics/atmos_les_default.jl
Fix a bug in `atmos_les_default.jl` that causes problems when using `DryModel`.
I have
> fix bug in atmos_les_default.jl

- .buildkite/pipeline.yml
Move to an to an explicit per build depot (depot per agent config) as a workaround for permissions issues with loading a precompiled shared depot.
> move to per build init / depot

- src/Atmos/Model/ref_state.jl
This PR makes the local thermo state in `src/Atmos/Model/ref_state.jl` a dry thermo state if we have a dry model, so that we don't run into sat adjust issues when we shouldn't need to.
I have
> Use dry ref state for dry moisture model

- .dev/systemimage/climate_machine_image.jl
Switches to using `Pkg.dependencies` instead of 'Pkg.installed` for creating the system image.
I have
> Remove deprecated call to `Pkg.installed()`

- src/Driver/Driver.jl
Previously would result in error if for instance one did for instance
CLIMATEMACHINE_SETTINGS_VTK="100steps" julia -J.git/ClimateMachine.sys --project test/Atmos/Model/discrete-hydrostatic-balance.jl
since `tryparse(String, "100steps")` gives the error
```
ERROR: MethodError: no method matching tryparse(::Type{String}, ::String)
Closest candidates are:
tryparse(::Type{T}, ::AbstractString; base) where T<:Integer at parse.jl:234
tryparse(::Type{Float64}, ::String) at parse.jl:245
tryparse(::Type{Float32}, ::String) at parse.jl:265
...
Stacktrace:
[1] top-level scope at REPL[2]:1
```
I have
> Fix environment variable parsing for String types

- .buildkite/pipeline.yml
- test/Land/Model/haverkamp_implicit_test.jl
Set up an example for using implicit solver for the soil model, this example is in test/Land/Model/haverkamp_test_implicit.jl, add it to CI test.
I have
> Add soil implicit test haverkamp_implicit_test.jl to pipeline.yml

- src/Driver/SolverTypes/SplitExplicitSolverType.jl
Addressing this comment: https://github.com/CliMA/ClimateMachine.jl/pull/1554#discussion_r493193331
Pretty straightforward typo fix.
I have
> bugfix for #1554

- src/Driver/Driver.jl
`ClimateMachine.init()` would update the `disable_gpu` setting, but not the `array_type` setting when reinitializing with `disable_gpu = true` after having previously initialized with `disable_gpu = false`. This PR fixes it so you can switch between GPU and CPU backend within a single session of the Julia REPL.
I have
> Update Array type when switching from GPU to CPU

- .github/workflows/Documenter.yaml
- docs/list_of_how_to_guides.jl
- docs/src/HowToGuides/Atmos/MoistureModelChoices.md
Update to the documentation on the moisture model choices and add explanation for `new_thermo_state` and `recover_thermo_state` functions.
I have
> Add moisture model docs

- test/Atmos/EDMF/bomex_edmf.jl
- test/Ocean/ShallowWater/test_2D_spindown.jl
- test/Ocean/SplitExplicit/simple_box_ivd.jl
- test/Ocean/SplitExplicit/split_explicit.jl
Prevents race conditions on the cluster when multiple test files are being executed at the same time using different `output_dir` settings.
I have
> fix tests to ensure they respect ClimateMachine.Setting output_dir path prefix

- docs/list_of_tutorials.jl
- docs/src/Contributing.md
I move the contributing tutorials file to the Contributing.md section - now all contributing info is in one spot.
I have
> moved contributing tutorial code to the Contributing section

- docs/list_of_tutorials.jl
- tutorials/Atmos/densitycurrent.jl
- tutorials/Atmos/risingbubble.jl
This PR fixes the density current tutorial in the docs, and adds it to the list of docs.
I have
> Fix density current tutorial

- docs/list_of_tutorials.jl
- tutorials/Atmos/agnesi_hs_lin.jl
- tutorials/Atmos/agnesi_nh_lin.jl
- tutorials/Land/Soil/Coupled/equilibrium_test.jl
- tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
- tutorials/Land/Soil/Water/equilibrium_test.jl
- tutorials/Land/Soil/Water/hydraulic_functions.jl
There's a duplicate density current link in the tutorials. This PR
- Removes the duplicate.
- Removes some trailing whitespace in some tutorials
- Adds formatting to some tutorial code
I have
> Remove dup tutorial link, add fmt, rm trailing spaces

- test/Numerics/Mesh/Metrics.jl
The first component of the geometric conservation law was tested multiple times by mistake (instead of testing all components).
I have
> Fix constant preservation metrics tests

- test/Atmos/EDMF/edmf_kernels.jl
In line 623 in edmf_kernels.jl the massflux contribution of total energy in the grid mean is computed. It is missing the area fraction 'a'. This PR fixes that bag.
I have
> fix edmf e massflux

- src/Numerics/Mesh/BrickMesh.jl
Does what the title says
I have
> Fix depreciated constructor call to `BigFloat`

- experiments/OceanSplitExplicit/simple_box.jl
- src/Numerics/ODESolvers/SplitExplicitMethod.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/Ocean.jl
- src/Ocean/OceanBC.jl
- src/Ocean/OceanProblems/SimpleBoxProblem.jl
- src/Ocean/ShallowWater/ShallowWaterModel.jl
- src/Ocean/ShallowWater/bc_velocity.jl
- src/Ocean/SplitExplicit01/BarotropicModel.jl
- src/Ocean/SplitExplicit01/Continuity3dModel.jl
- src/Ocean/SplitExplicit01/OceanBoundaryConditions.jl
- src/Ocean/SplitExplicit01/OceanModel.jl
- src/Ocean/SplitExplicit01/SplitExplicitLSRK2nMethod.jl
- src/Ocean/SplitExplicit01/SplitExplicitModel.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
- test/Ocean/SplitExplicit/simple_box_ivd.jl
- test/Ocean/SplitExplicit/split_explicit.jl
- test/Ocean/SplitExplicit/test_restart.jl
- test/Ocean/SplitExplicit/test_simple_box.jl
- test/Ocean/SplitExplicit/test_spindown_long.jl
- test/Ocean/SplitExplicit/test_spindown_short.jl
Makes it so the SplitExplicit01 code has shares the same problems as the rest of the Ocean code and provides defaults for each case. Also does some integration of the boundary condition handling across the different ocean models.
I have
> Integrate SplitExplicit01 code with OceanProblems code

- src/Diagnostics/Debug/StateCheck.jl
This reverts commit 122cddcbbebef0be23a02666ca23fe841c4ff923 "switch to PrettyTables for scprintref and scdocheck".
#1331 formatted the output that we needed in plain text to paste in as reference values. If anyone is interested, they port the changes from #1331 to work on callback instead of `scprintref`
I have
> Revert #1331

- src/Ocean/OceanProblems/ShallowWaterInitialStates.jl
Fixes small type typo that stopped current Ocean barotropic gyre code compiling when Munk
style problem was selected.
> Fix Munk setup type typo, so code now compiles

- experiments/OceanBoxGCM/simple_box.jl
- src/Ocean/SplitExplicit01/Continuity3dModel.jl
- test/Ocean/SplitExplicit/hydrostatic_spindown.jl
- test/Ocean/SplitExplicit/split_explicit.jl
- test/Ocean/SplitExplicit/test_coriolis.jl
- test/Ocean/SplitExplicit/test_spindown_short.jl
See title. Allows comparing spindown and coriolis tests across multiple solvers.
I have
> Add SplitExplicitLSRK2nSolver to mini-driver setup

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/states.jl
- test/Common/Thermodynamics/runtests.jl
Adds a dry thermo state constructor (`PhaseDry_given_pθ`), which accepts pressure and `θ_dry`.
I have
> Add dry thermo constructor

- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Numerics/Mesh/BrickMesh.jl
- src/Numerics/Mesh/Grids.jl
- test/Numerics/Mesh/BrickMesh.jl
Before this PR there were two very similar `mappings` functions with identical arguments, one in `Mesh.Grids`, the other in `Mesh.Grids.BrickMesh`. From what I could tell `BrickMesh.mappings` had unit tests but it was `Grids.mappings` that was used to construct the DG grid. This PR removes `BrickMesh.mappings` and changes the tests to use `Grids.mappings`. Additionally, `BrickMesh.commmapping` is moved to `Grids` for consistency, and to have `BrickMesh` only contain functions that don't depend on the polynomial order.
I have
> Remove BrickMesh.mappings function

- src/Ocean/ShallowWater/bc_velocity.jl
Fix small vector size typo in Barotropic (2d) ocean no-slip boundary code. 
Previously code errored at runtime. 
```
ERROR: LoadError: TaskFailedException:
DimensionMismatch("array could not be broadcast to match destination")
Stacktrace:
[1] materialize! at ./broadcast.jl:0 [inlined]
[2] macro expansion at /Users/chrishill/projects/clim-z2/src/Utilities/VariableTemplates/VariableTemplates.jl:244 [inlined]
[3] setproperty! at /Users/chrishill/projects/clim-z2/src/Utilities/VariableTemplates/VariableTemplates.jl:218 [inlined]
[4] ocean_boundary_state! at /Users/chrishill/projects/clim-z2/src/Ocean/ShallowWater/bc_velocity.jl:140 [inlined]
[5] ocean_boundary_state! at /Users/chrishill/projects/clim-z2/src/Ocean/ShallowWater/ShallowWaterModel.jl:319 [inlined]
```
Now the code runs and …
> Fixes dormant 2d vector not 3d vector typo in barotropic ocean noslip bc

- src/Diagnostics/Debug/StateCheck.jl
one of the `row pass count` should be `row failure counts`
> Typo in StateCheck output

- docs/src/APIs/Common/Thermodynamics.md
- docs/src/Theory/Atmos/Microphysics.md
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/stable_bl_kosovic.jl
- experiments/AtmosLES/surfacebubble.jl
- experiments/AtmosLES/unstable_bl_kitamura.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/ref_state.jl
- src/Atmos/Model/source.jl
- src/Common/Thermodynamics/states.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
- test/Atmos/Parameterizations/Microphysics/KM_ice.jl
- test/Atmos/Parameterizations/Microphysics/KM_warm_rain.jl
- test/Atmos/Parameterizations/Microphysics/KinematicModel.jl
- test/Common/Thermodynamics/runtests.jl
- test/Diagnostics/diagnostic_fields_test.jl
- test/Diagnostics/sin_test.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/driver_test.jl
- test/Driver/gcm_driver_test.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGMethods/Euler/acousticwave_mrigark.jl
- test/Numerics/DGMethods/Euler/isentropicvortex.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
I know that verbosity is good, but the names of thermo state constructors have gotten a bit out of hand. Thoughts on these changes? The proposed convention is: `PhaseName_{inputvariables}`. Without the suffix implies that you're calling the default constructor. We could write wrappers for these, too, but the ultimate solution here is to use kwargs, once this proves to be performant. And then we'll only have 3 names: `PhaseDry`, `PhaseEquil`, `PhaseNonEquil` with kwargs specifying the inputs. The other nice side effect of this is that users can easily locally check that the order of the input variables are correct.
Old names:
```
PhaseDry
PhaseDry_given_pT
PhaseDry_given_pθ
PhaseDry_given_ρT
PhaseEquil
PhaseNonEquil
TemperatureSHumEquil
TemperatureSHumNonEquil …
```
> Improve thermo names

- src/Common/Thermodynamics/Thermodynamics.jl
- test/Common/Thermodynamics/runtests.jl
This PR applies a broadcast rule for thermodynamic's `param_set`. This cleans up some code in Thermo's `runtests.jl` that was a bit hammered by the formatter.
I have
> Add broadcast rule to param_set in thermo

- src/Numerics/Mesh/Geometry.jl
Test impact of small change that adds index information I have been finding useful for 
- kernel debugging/verification and 
- precise inner numerical term budgets 
with aux variables e.g.
```
function ocean_init_aux!(::SWModel, ::AbstractSimpleBoxProblem, A, geom)
@inbounds A.y = geom.coord[2]
A.Gᵁ = @SVector [-0, -0]
A.Δu = @SVector [-0, -0]
@mydebug A.n  = geom.n
@mydebug A.e  = geom.e
return nothing
end
```
```
@inline function compute_gradient_flux!(
m::SWModel,
T::ConstantViscosity,
σ::Vars,
δ::Grad,
q::Vars,
α::Vars,
t::Real,
)
ν = Diagonal(@SVector [T.ν, T.ν, -0])
∇U = δ.∇U
σ.ν∇U = -ν * ∇U
@mydebug my_save_grad_u(m, q.U, ∇U, ν, -ν * ∇U, α.n, α.e )
return nothing
end
```
Change to LocalGeom may also be useful to others who are interested in knowing inner term
values for both …
> Testing three-line change hacky approach for index coords in aux that I am finding useful in inner code debug, and that may be useful for others?

- docs/src/APIs/Common/Thermodynamics.md
- docs/src/HowToGuides/Atmos/TemperatureProfiles.md
- src/Atmos/Model/ref_state.jl
- src/Common/Thermodynamics/isentropic.jl
- src/Common/Thermodynamics/relations.jl
- src/Common/Thermodynamics/states.jl
- test/Atmos/Model/ref_state.jl
- test/Common/Thermodynamics/runtests.jl
This PR
- Removes several methods from being exported in Thermodynamics.jl (highlighted in red in `Thermodynamics.md`).
- Shortens some thermodynamics-internal method names, and argument orders, to follow the style used in #1631.
- Fixes a `p` vs `ρ` bug 👊🏻! Thanks @trontrytel!
Closes #1612.
> Limit exported thermodynamic methods

- docs/src/HowToGuides/Atmos/MoistureModelChoices.md
- src/Atmos/Model/thermo_states.jl
See #1648.
This PR should make thermodynamics consistent on the boundaries.
> Make `recover_thermo_state` call `new_thermo_state`

- src/Common/Thermodynamics/Thermodynamics.jl
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
This PR adds a `supersaturation(ts::ThermodynamicState, phase::Phase)` method.
> Add supersaturation interface method

- docs/src/GettingStarted/Installation.md
My very first and very quick PR! 
This just adds the code snippet for the "change directory" instruction, that was previously expressed in words. I found myself doing just quick copy&paste of the code parts, and if someone doesn't note the written part, this wouldn't work. So it's just to allow easy reproducibility of the instructions.
> Add cd in the instructions - just for quick copy/paste

- docs/plothelpers.jl
- docs/src/HowToGuides/Atmos/AtmosReferenceState.md
- src/Numerics/Mesh/Grids.jl
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/bomex_edmf_regression_test.jl
- test/Atmos/Model/ref_state.jl
- tutorials/Atmos/burgers_single_stack.jl
- tutorials/Atmos/burgers_single_stack_bjfnk.jl
- tutorials/Land/Heat/heat_equation.jl
- tutorials/Numerics/DGMethods/Box1D.jl
This PR
- Adds a kwarg `rm_dupes` to `get_z`, to remove duplicate lgl points at the element faces.
- Adds a kwarg `interp` to `get_vars_from_nodal_stack` to vertically average variables at the duplicate lgl points at the element faces.
- Swaps some positional args and kwargs in `dict_of_nodal_states`
- Adds `@inbounds` to `get_vars_from_nodal_stack` loops
This PR will help with two issues at the moment
- Exported plots currently included duplicate points at the element faces, which visually appear as jagged oscillations.
- We cannot create contour plots with duplicate points in space
This new feature is exercised in the heat tutorial.
Closes #1556
> Interpolate duplicate lgl points in `get_vars_from_nodal_stack`

- experiments/AtmosLES/bomex_les.jl
- experiments/AtmosLES/bomex_model.jl
To avoid uncertainties with `Float32` precision, this PR changes the BOMEX LES experiment to use `Float64`.
Partially addresses #1589.
> Use Float64 in BOMEX LES

- docs/plothelpers.jl
- tutorials/Land/Heat/heat_equation.jl
It's currently difficult to interpret EDMF results with line plots. This PR adds contour plots to `docs/plothelpers.jl`, which should help with interpreting/debugging. cc @yairchn
> Add contour plot to plothelpers

- src/Atmos/Model/source.jl
- src/Land/Model/source.jl
- test/Atmos/Model/discrete_hydrostatic_balance.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/gcm_driver_test.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGMethods/Euler/acousticwave_mrigark.jl
- test/Numerics/DGMethods/Euler/isentropicvortex.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_imex.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_mrigark.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_mrigark_implicit.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_multirate.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/density_current_model.jl
- test/Numerics/DGMethods/courant.jl
- test/Numerics/DGMethods/remainder_model.jl
- test/Numerics/Mesh/interpolation.jl
#1634 requires sources to be specified via Tuples, and supporting mixed tuple types seems a bit more complicated than what it is worth. This PR removes the use of and reliance on `source = nothing` and `source = (nothing,....)`.
> Remove support for `nothing` source

- src/Numerics/Mesh/Grids.jl
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
`get_z` with `rm_dupes = true` is breaking when the grid uses device data. Same with `get_vars_from_nodal_stack` with `interp=true`. This PR just converts these incoming CuArrays to ordinary arrays, since these pieces are mostly relevant to the single stack utils and aren't performant critical at the moment.
> Make `get_z` and `get_vars_from_nodal_stack` interp work with cu-arrays

- experiments/AtmosGCM/GCMDriver/gcm_sources.jl
- experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl
- experiments/AtmosGCM/heldsuarez.jl
- src/Atmos/Model/source.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Driver/mms3.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- tutorials/Atmos/heldsuarez.jl
Similar to #1666, #1634 requires sources to be specified via Tuples. This PR removes the use of and reliance on supporting functions inside the `atmos.source` tuple, for example, `source = held_suarez_forcing!` and `source = (held_suarez_forcing!,....)`. Instead a new subtype of `Source` is made and we overload `atmos_source!` for the given subtype. Will wait for #1666 to avoid merge conflicts.
This PR also reuses what was `held_suarez_forcing!`, which seemed to be defined in multiple places. I left the `held_suarez_forcing!` defined in the tutorial to keep it stand-alone.
> Remove source function support

- docs/plothelpers.jl
- tutorials/Atmos/burgers_single_stack.jl
- tutorials/Atmos/burgers_single_stack_bjfnk.jl
- tutorials/Land/Heat/heat_equation.jl
- tutorials/Numerics/DGMethods/Box1D.jl
The recently added `plothelpers.jl` hack is already causing issues with some upstream branches 🙄.
This PR
- Removes the plothelpers hack and just add `xlims` as a kwarg, which should default to Plots.jl default (`:auto`). 
- Makes `time_data` a positional arg, to unify the interface with the other plotting functions.
- Fix condition for when `single_var` should sometimes be `true`.
- Adds a kwarg for `time_units`
- Propagates `ylabel` in `export_state_plots`
> Remove plot helpers hack

- .buildkite/pipeline.yml
- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
This PR adds a modularized Stable Boundary Layer experiment, separating the existing `stable_bl_kosovic.jl` into a model file and an LES configuration script. This follows the convention of the change that was made for the Bomex LES case, and it is a necessary step towards creating a Single Column Model configuration for the stable boundary layer experiment.
I have checked that it yields the same results as `stable_bl_kosovic.jl`, and I have added an additional conservation check.
> Added modularized stable BL LES case (model+driver).

- src/Numerics/Mesh/Geometry.jl
There was a missing `@inbounds` in #1629
> Missing @inbounds in LocalGeometry getproperty

- experiments/AtmosLES/bomex_model.jl
- src/Atmos/Model/source.jl
- test/Atmos/EDMF/bomex_edmf_regression_test.jl
Right now in `source.jl` the water mass source from subsidence is not included. This PR adds this term.
> add water mass source from subsidence

- src/Driver/driver_configs.jl
- src/Driver/solver_configs.jl
- test/Driver/mms3.jl
- test/Land/Model/haverkamp_implicit_test.jl
- tutorials/Atmos/burgers_single_stack_bjfnk.jl
This PR adds a `DGModel` outer constructor that accepts a `DriverConfiguration`.
> Add DGModel outer constructor

- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/closures/surface_functions.jl
- test/Atmos/EDMF/edmf_kernels.jl
This PR preps support for running with a dry `turbconv` model. More is coming, but we don't want to add too much untested code at a time (the DryModel branches, in this case).
> Prep support for dry turbconv

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/states.jl
- test/Common/Thermodynamics/runtests.jl
Add new PhaseDry thermodynamic state constructor, `PhaseDry_ρθ`. This constructor allows to obtain the thermodynamic state from the density and the potential temperature.
> Add new PhaseDry thermodynamic state constructor

- .buildkite/pipeline.yml
- experiments/AtmosLES/convective_bl_les.jl
- experiments/AtmosLES/convective_bl_model.jl
This PR modularize the Convective Boundary Layer experiment, separating the previous unstable_bl_kitamura.jl into a model file and an LES configuration script. This follows the convention of the change that was made for the Bomex LES and stable BL cases, and it is a necessary step towards creating a Single Column Model configuration for the stable boundary layer experiment.
I have checked that it yields the same results as unstable_bl_kitamura.jl, and I have added an additional conservation check.
> Added modularized convective BL LES case (model+driver)

- test/Land/Model/haverkamp_implicit_test.jl
Rename `Artifacts.toml` to `Artifacts_implicit.toml` in `test/Land/Model/haverkamp_implicit_test.jl`, since the same exact Artifact is also generated in `test/Land/Model/haverkamp_test.jl`.
Closes #1678.
> Fix race condition with Haverkamp artifact file

- src/Common/Thermodynamics/relations.jl
This PR adds `relative_humidity` for `PhaseDry` thermo states. Docs are already there for the generic `::ThermodynamicState`, and this will automatically be picked up in the test suite in the "Thermodynamics - dry limit" tests.
> Add `relative_humidity` for `PhaseDry`

- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
This PR makes `recover_thermo_state` call `new_thermo_state` in the turbconv model (which was not done in #1647). It looks like this is PR passes the regression test 🎉
> Make `recover_thermo_state` call `new_thermo_state` in turbconv

- .github/workflows/DocCleanup.yml
- docs/make.jl
Use `forcepush` option in Documenter to avoid keeping `gh-pages` history.
Adds a new workflow to delete previews and squash history when the PR is closed.
These two should fix #1665.
> Enable forcepush for Documenter, delete stale previews

- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
- src/Numerics/Mesh/Topologies.jl
- src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl
- src/Ocean/SplitExplicit/Communication.jl
- src/Ocean/SplitExplicit/HydrostaticBoussinesqCoupling.jl
- src/Ocean/SplitExplicit01/Communication.jl
- src/Ocean/SplitExplicit01/OceanModel.jl
This PR documents the core DG kernels used in the numerics (volume/interface kernels for the prognostic and auxiliary equations in the LDG formulation). Hyperdiffusion kernels will be documented in a later PR. All DG kernels have been split in the main tendency evaluation function into separate horizontal and vertical calls.
> Decompose discretization kernels into horizontal and vertical calls

- test/Land/Model/heat_analytic_unit_test.jl
- test/Numerics/SystemSolvers/poisson.jl
- test/Ocean/HydrostaticBoussinesq/test_3D_spindown.jl
- test/Ocean/ShallowWater/GyreDriver.jl
- test/Ocean/SplitExplicit/simple_box_2dt.jl
- test/Ocean/SplitExplicit/simple_box_ivd.jl
- test/Ocean/SplitExplicit/test_vertical_integral_model.jl
- tutorials/Atmos/agnesi_hs_lin.jl
- tutorials/Atmos/agnesi_nh_lin.jl
- tutorials/Atmos/burgers_single_stack.jl
- tutorials/Atmos/burgers_single_stack_bjfnk.jl
- tutorials/Atmos/densitycurrent.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
- tutorials/Atmos/heldsuarez.jl
- tutorials/Atmos/risingbubble.jl
- tutorials/Land/Heat/heat_equation.jl
- tutorials/Land/Soil/Coupled/equilibrium_test.jl
- tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
- tutorials/Land/Soil/Water/hydraulic_functions.jl
- tutorials/Numerics/DGMethods/Box1D.jl
- tutorials/Numerics/DGMethods/showcase_filters.jl
The docs build recently started timing out, cc @thomasgibson. This PR is an attempted quick-fix by enforcing that `FT` is in the type domain for the tutorials. I accidentally started doing this in some of the tests, too. Perhaps this will speed some things up.
> Add const to `FT` and enforce to be in type domain

- experiments/AtmosGCM/GCMDriver/gcm_sources.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/convective_bl_model.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/source.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Driver/mms3.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- tutorials/Atmos/heldsuarez.jl
This PR renames `Source` to `AbstractSource`, as it's an abstract type. These changes were peeled off from #1634 because they touch a bunch more files than #1634 needs to.
> Rename Atmos.Source to Atmos.AbstractSource

- .buildkite/pipeline.yml
- docs/src/APIs/Numerics/DGMethods/DGMethods.md
- src/Numerics/DGMethods/DGMethods.jl
- src/Numerics/DGMethods/custom_filter.jl
- test/Numerics/DGMethods/custom_filter.jl
- test/Numerics/DGMethods/runtests.jl
The EDMF team has demonstrated significantly more stable simulations using custom filters. cc: @yairchn @ilopezgp 
The current implementation of the custom filter is a Q&D hack that takes many passes over the entire MPIStateArray:
```julia
cbtmarfilter = GenericCallbacks.EveryXSimulationSteps(1) do
bl = solver_config.dg.balance_law
st = vars_state(bl, Prognostic(), eltype(Q))
aux = vars_state(bl, Auxiliary(), eltype(Q))
a_min = bl.turbconv.subdomains.a_min
a_max = bl.turbconv.subdomains.a_max
i_ρ = varsindex(st, :ρ)
i_ρq_tot_gm = varsindex(st, :moisture, :ρq_tot)
ρ_gm = solver_config.Q[:,i_ρ,:]
i_ρaθ_liq_en = varsindex(aux, :turbconv, :environment,:ρaθ_liq)
ρaθ_liq_en  = solver_config.dg.state_auxiliary[:,i_ρaθ_liq_en,:]
ρaθ_liq_ups = FT(0)
ρaq_tot_ups = FT(0)
ρa_ups      = FT(0)
ρaw_ups …
```
> Add custom filter

- experiments/AtmosGCM/GCMDriver/gcm_bcs.jl
- experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/convective_bl_model.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/bc_energy.jl
This PR adds a BalanceLaw as an argument to the closures used for the energy fluxes in BulkFormulaEnergy. This argument is necessary for simulation that may have different energy closures depending on whether they are dry or moist.
> Pass BalanceLaw to BulkFormulaEnergy

- .buildkite/pipeline.yml
- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
- test/Atmos/EDMF/helper_funcs/save_subdomain_temperature.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
This PR adds an EDMF driver for the simulation of the stable boundary layer. This is a dry simulation with zero/negligible area fraction. The PR also includes improvements of the EDMF helper functions to allow for simulations using a `DryModel`.
Co-authored by @charleskawczynski.
> Add EDMF driver for stable_bl_model.

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
This adds definitions for internal energies of dry air, water vapor, liquid water and ice. I will need it for microphysics source terms to total energy in precipitation interface PR.
> Add internal energies of dry air, vapor, liquid and ice

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
The AtmosLinearModel must use a contiguous subset of the AtmosModel,
since `turbconv` was not in the `AtmosLinearModel` it needs to be
moved later in the state list.
closes #1494 
co-authored-by: Charles Kawczynski <kawczynski.charles@gmail.com>
> Fix the ordering of the state in the AtmosModel

- src/Numerics/ODESolvers/BackwardEulerSolvers.jl
- src/Numerics/SystemSolvers/SystemSolvers.jl
The vertical discretization might depend on the time and parameters(which is the case for EDMF test), but the parameter and time are set to be nothing and NaN when we construct the preconditioner
> Fix bugs in the preconditioner construction step in the fully implicit solver

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/declare_prognostic_vars.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/BalanceLaws/BalanceLaws.jl
- src/BalanceLaws/show_tendencies.jl
- src/BalanceLaws/sum_tendencies.jl
- src/BalanceLaws/tendency_types.jl
- src/Driver/driver_configs.jl
- test/BalanceLaws/runtests.jl
- test/runtests.jl
This is a first step towards fixing #395, #1527, #1036, and #1633.
It seems that all sources could be written this way. I think this has a few advantages:
- Users can overload `eq_tends` and add / remove terms in a hierarchical fashion, while not affecting the other flux terms
- `flux` and `source` can be used by diagnostics to export/monitor the budget.
- This could also be used for specifying time-explicit/implicit source terms more easily via types
- We can remove the generated functions in `Atmos/Model/source.jl`
This is just a prototype for now. I figured I'd open this PR to get feedback. This seems to work fine for `experiments/AtmosLES/bomex_single_stack.jl` (both on CPU and GPU)
One potential concern is, can we continue to unroll the tendencies if the number of sources gets large. …
> Add source type hierarchy

- experiments/TestCase/solid_body_rotation.jl
This PR makes the following changes in the solid body rotation test in `TestCase`:
- adding a test assert to make sure state variables stays identical to the initial condition;
- reducing simulation time to 2 hours (it was 12 hours before).
> add a test assert making sure the solid-body-rotation do not generate flow

- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/tendencies_momentum.jl
This PR moves `Gravity` to the new tendency specification. I can confirm that, in `experiments/AtmosGCM/heldsuarez.jl`, the tendency table is properly updated:
> Move Gravity to new tendency specification

- .buildkite/docs-pipeline.yml
- .github/workflows/Documenter.yaml
- bors.toml
- docs/make.jl
* update github workflow to not build tutorials only on pull request
* update bors to use status of buildkite docs pipeline
This reduces the overall time to roughly 45-50 minutes, with each tutorial is running in parallel with 8 workers (can be increased given overall memory budget).
Pipeline: https://buildkite.com/clima/climatemachine-docs
> build docs on a slurm cluster node with buildkite

- docs/src/GettingStarted/Installation.md
This is to avoid the following warning:
```
Warning: CLIMATEMACHINE_GPU will be deprecated; use CLIMATEMACHINE_SETTINGS_DISABLE_GPU
```
> Update installation guide: use CLIMATEMACHINE_SETTINGS_DISABLE_GPU

- docs/src/GettingStarted/Atmos.md
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/tendencies_momentum.jl
This PR moves the Coriolis and Geostrophic forcing terms to the new tendency specification.
> Move Coriolis and GeoForcing to new tendency specification

- Manifest.toml
- Project.toml
- docs/src/HowToGuides/Common/Thermodynamics.md
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
This PR removes `@unpack_fields` and replaces it with `@unpack` from [UnPack.jl](https://github.com/mauro3/UnPack.jl) (which has been added).
> Remove unpack_fields, use UnPack package

- src/Driver/Driver.jl
- src/Driver/solver_configs.jl
This PR adds a `--sim-time` command line argument which allows overriding the experiment-specified `timeend`. The `--fixed-number-of-steps` command line argument overrides this one.
> Add `--sim-time` command line argument

- src/Numerics/Mesh/Grids.jl
- test/Numerics/Mesh/Grids.jl
- test/Numerics/Mesh/runtests.jl
Fixes ordering of mass matrix elements for multiple polynomial orders and adds a test.
CC: @thomasgibson
> Fix ordering of mass matrix elements for multiple polynomial orders

- .buildkite/pipeline.yml
- src/Numerics/SystemSolvers/SystemSolvers.jl
- test/Atmos/EDMF/stable_bl_edmf_implicit.jl
Co-authored-by: Charles Kawczynski <kawczynski.charles@gmail.com>
Results-checked-by: Ignacio Lopez-Gomez <ilopezgo@caltech.edu>
Add an example which uses fully implicit solver to solve EDMF(stable boundary layer) for 6h within 15 mins.
This example demonstrates that we can use fully implicit solver here, and the results match the that delivered by the explicit solver.
Mute fully implicit solver (no info for linear/nonlinear iterations)
> add test/Atmos/EDMF/stable_bl_edmf_implicit.jl and mute newton solver

- .buildkite/pipeline.yml
- experiments/TestCase/isothermal_zonal_flow.jl
This PR updates the isothermal zonal flow in:
1. replacing the default Rusanov flux by Roe flux;
2. adding a test assert to ensure the flow stay identical to its initial state;
3. moving the test driver into `TestCase`
> modify the isothermal zonal flow test case and move it to TestCase folder

- src/Common/Thermodynamics/relations.jl
This PR fixes some of the thermo print statements, which are missing commas and are improperly formatted.
> Fix thermo print statements

- .buildkite/pipeline.yml
- experiments/AtmosLES/bomex_single_stack.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/tendencies_moisture.jl
This PR
- moves the first order moisture flux to the new tendency specification. I can confirm that the tendency table is updated, for `experiments/AtmosLES/bomex_model.jl` with `moisture_model == "nonequilibrium"`, but I haven't checked the results.
- Renames `flux_moisture!` to `flux_first_order!` in efforts to standardize some of the AtmosModel method calls
- Adds `Moisture <: PrognosticVariable` to combine specification for the moisture variables.
> Move first order moisture flux to new tendency specification

- docs/bibliography.bib
I went to fix the bib entries whose hyperlinks point to the reference page and realized that these correspond to bib entries with missing DOI/URL/eprint attributes. This PR adds some missing DOIs. Also, in case these links are checked by Documenter, it makes sense to rely on DOIs over other URLs, so this PR also removes some of the URLs so long the DOIs exist.
> Add DOIs to .bib, remove urls

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/BalanceLaws/show_tendencies.jl
This PR adds some of the second-order fluxes to the new tendency specification.
@simonbyrne one thing I had thought about was, rather than splatting in `args = (atmos, state, aux, t, ts, diffusive, hyperdiffusive)` to the `flux` and `source` functions, we could pass in a `NamedTuple`:
```julia
nt = (atmos=atmos, state=state, aux=aux, t=t, ts=ts, diffusive=diffusive, hyperdiff=hyperdiffusive)
```
and then have:
```julia
function flux(::ViscousProduction{Energy}, nt)
@unpack diffusive, aux, atmos, t = nt
ν, D_t, τ = turbulence_tensors(atmos, state, diffusive, aux, t)
ν, D_t, τ = sponge_viscosity_modifier(m, m.viscoussponge, ν, D_t, τ, aux)
return τ * state.ρu
end
```
Pros of using `NamedTuple`s:
- Compactify signature
- Makes changing the effective arg list much easier
Cons of using …
> Add some second order fluxes to new tend spec

- src/InputOutput/VTK/writemesh.jl
- src/InputOutput/VTK/writevtk.jl
- test/InputOutput/VTK/runtests.jl
- test/Numerics/SystemSolvers/bandedsystem.jl
To support multiple polynomial orders this PR adds back in some of the
functionality from #1352. If subsampling is not asked for, the data is dumped at
the raw DG nodal values with the mesh defined from the degree of freedom boxes.
If subsampling is asked for, then the data is interpolated to an equally spaced
mesh in all directions and high-order lagrange elements are used.
> VTK support for multiple polynomial orders

- docs/src/APIs/Atmos/AtmosModel.md
- docs/src/HowToGuides/Atmos/PrecipitationModelChoices.md
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/declare_prognostic_vars.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/radiation.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Atmos/Model/tendencies_precipitation.jl
- src/Atmos/Model/tracers.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- src/Diagnostics/atmos_les_default.jl
- test/Atmos/EDMF/edmf_kernels.jl
This PR:
- Adds a `source` validation assert: `@assert !any(isa.(source, Tuple))` to the `AtmosModel` to break early if we've incorrectly specified sources (e.g., not splatting them). This addresses #1779 but only for the AtmosModel.
- Renames `Rain` to `RainModel`, and adds `Rain <: PrognosticVariable` and `Snow <: PrognosticVariable`.
- Moves the `RemovePrecipitation` to the new tendency specification
- Moves the `Rain_1M` to the new tendency specification
Here's the new table with `Dycoms` using non-equilibrium model with `RainModel`:
```
PDE: ∂_t Y_i + (∇•F_1(Y))_i + (∇•F_2(Y,G)))_i = (S(Y,G))_i
┌────────────────┬────────────────────────────┬─────────────────────────────────────────┬───────────┐
│       Equation │           Flux{FirstOrder} │                       Flux{SecondOrder} │ …
```
> Move rain sources to new tend spec

- docs/src/APIs/Atmos/AtmosModel.md
- docs/src/HowToGuides/Atmos/PrecipitationModelChoices.md
- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/radiation.jl
- src/Atmos/Model/source.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Atmos/Model/tracers.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- src/Diagnostics/atmos_les_default.jl
- test/Atmos/EDMF/edmf_kernels.jl
This PR:
- Changes some method names (e.g., `flux_moisture!`) to `flux_first_order!`
- Changes `Rain` to `RainModel`
- Adds `ts::ThermodynamicState` and `direction` to `flux_first_order!`
- Moves some things outside of `src/Atmos/Model/source.jl`
- Adds a `source` validation assert: `@assert !any(isa.(source, Tuple))` to the `AtmosModel` to break early if we've incorrectly specified sources (e.g., not splatting them). This addresses #1779 but only for the AtmosModel.
This basically strips a bunch of things out from #1782.
> Prep for new tendency spec

- src/Driver/Callbacks/Callbacks.jl
This PR fixes the reported `remaining runtime (estimated)`, it is actually the estimated total (end) wall clock time.
> Rename estimated remaining to est. wallclock end

- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
- experiments/AtmosGCM/nonhydrostatic_gravity_wave.jl
- experiments/TestCase/baroclinic_wave.jl
- experiments/TestCase/solid_body_rotation.jl
This PR changes the polynomial order from 3 to 5 in GCM test case drivers:
- solid body rotation
- baroclinic wave
Horizontal and vertical element numbers are changed accordingly so that the default resolution remains roughly the same. 
Tests have been performed to make sure that with the above changes, the solid body rotation test still holds the initial condition; and the baroclinic wave test can survive 30 days and generate reasonable outputs.
> GCM test case: polynomial order set to 5

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/precipitation.jl
This PR
- Adds a missing call to `source!` for the precipitation model.
- Re-orders the arguments so that we can pass them through in the same order as `source`
@trontrytel This should fix the dycoms with rain QA run.
> Add missing call to rain source

- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/radiation.jl
This PR
- Renames `DYCOMSRadiation` -> `DYCOMSRadiationModel`
- Adds `DYCOMSRadiation` for the first order flux type
- Moves the first order radiative flux to the new tendency specification
- Deletes some unnecessary code (defined for `RadiationModel` in `dycoms.jl`)
> Move radiation to new tendency spec

- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse.jl
This branch adds the first order flux for environment covariances of then EDMF equations.
The values of mse for ρu[1] and turbconv.environment.ρaθ_liq_cv where updated to allow then Bomex test to pass.
> Add flux_first_order for environment covariances and update the mse report values so that Bomex test is passing

- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/precipitation.jl
Move first order rain fluxes to new tendency specification.
I think that this is looking forward a bit, but, I put `eq_tends` for `Rain` in `precipitation.jl` instead of in `AtmosModel.jl`, since all we really need to do is "forward" `eq_tends` into the submodel components. That way we don't clutter `AtmosModel.jl` with all of the submodel tendencies.
> Move first order rain flux to new tend spec

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
It seems that `turbulence_tensors` is often, but not always, followed by a call to `sponge_viscosity_modifier`--should it be? This PR moves `sponge_viscosity_modifier` inside `turbulence_tensors`. I'm not sure if this is correct. Looping in @akshaysridhar.
This effectively adds calls to `sponge_viscosity_modifier` in a few places:
- https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/bc_energy.jl#L69 - I don't think this will impact anything, since the sponge is above a certain altitude and the bc is (I assume) at the surface
- https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Atmos/Model/courant.jl#L68 - may improve the correctness of the reported the diffusive courant
- https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Diagnostics/atmos_les_default.jl …
> Call modifier after turbulence_tensors

- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/declare_prognostic_vars.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/tracers.jl
- src/BalanceLaws/show_tendencies.jl
This PR moves tracers first order flux to the new tendency specification.
> Move tracers first order flux to new tendency specification

- src/Atmos/Model/get_prognostic_vars.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- test/Atmos/EDMF/edmf_kernels.jl
This PR moves the `atmos.turbconv` first order fluxes to the new tendency specification.
> Move first order flux turbconv tendencies to new spec

- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/tendencies_energy.jl
- src/BalanceLaws/tendency_types.jl
This PR
- Changes `ViscousProduction` -> `ViscousFlux`
- Changes `EnthalpyProduction` -> `DiffEnthalpyFlux`
- Updates the balance law docs in `tendency_types.jl`
> Improve balance law comments / docs, update some names

- docs/src/APIs/Driver/index.md
- docs/src/GettingStarted/RunningClimateMachine.md
- src/Driver/Callbacks/Callbacks.jl
- src/Driver/Driver.jl
- src/Driver/SolverTypes/SolverTypes.jl
- src/Driver/solver_configs.jl
A simple callback to adapt the timestep to stay consistent with the user-specified initial Courant number. 
Useful for accelerating flows.
> Adaptive timestepping callback

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- src/Common/Thermodynamics/states.jl
- test/Common/Thermodynamics/runtests.jl
This PR adds density-pressure thermo constructors
- `PhaseDry_ρp`
- `PhaseEquil_ρpq`
- `PhaseNonEquil_ρpq`
These constructors are tested along with all of the others, and they're also tested against a newly added method `total_energy_given_ρp`, which is used in the constructors to compute total energy by first computing temperature from the ideal gas law. I believe that this is needed so that we can translate between conservative and primitive variables. This allows users to, instead of calling `total_energy_given_ρp` directly:
```julia
ts = PhaseDry_ρp.(param_set, ρ, p)
ts = PhaseEquil_ρpq.(param_set, ρ, p, q_tot)
ts = PhaseNonEquil_ρpq.(param_set, ρ, p, q_pt)
e_tot = total_energy.(e_kin, e_pot, ts)
```
At the moment, these constructors are failing the consistency tests (for pressure) in …
> Add density-pressure thermo constructors

- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/closures/turbulence_functions.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Atmos/EDMF/report_mse.jl
This code adds missing TKE buoyancy source in the edmf_kernels.jl, and makes use of Prantl number to compute Eddy diffusivities for tracers and momentum. I also added an if condition to the computation Prantl number that avoid zero division neutral and unstable conditions.
> Add missing TKE buoyancy source and use prantl number for K-m and K_h ratio

- docs/list_of_theory_docs.jl
- docs/src/Theory/Atmos/EDMF_plots.md
This PR adds a plot for the turbulent Prantl number as function of gradient Richardson number  for a range of values to verify its behavior offline.
> add EDMF plots with a first plot for turbulent Prantl number as function of gradient Richardson number 

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/tendencies_precipitation.jl
This PR
- Adds 2nd order rain fluxes to the new tendency specification
Not sure if `Diffusion` is a good name here.
> Move second order rain flux to new tend spec

- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_precipitation.jl
I unified the returned items in the named tuple. Now all the microphysics multiphysics functions return only the source terms to state variables
> cleanup in multiphysics sources

- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
Working on #1830, I realized that it would be really helpful to iterate, pointwise, through the set of thermo profiles. This way we can test the primitive-prognostic conversion across the same set of profiles that thermodynamics is tested. This PR adds and tests this iterator.
> Add thermo ProfileSet Iterator

- experiments/TestCase/solid_body_rotation.jl
- src/Diagnostics/diagnostic_fields.jl
- test/Diagnostics/diagnostic_fields_test.jl
1).This PR fixes a bug effecting velocity gradient computation, in thediagnostics code, when different polynomial orders are used for
horizontal and vertical directions.
2). Different polynomial orders are prescibed for horizontal and
vertical directions for diagnostic_fields_test and solid_body_rotation
test.
> diagnostic fields + bug fix + vardeg

- experiments/AtmosLES/squall_line.jl
This PR should hopefully fix the race condition we're seeing with the squal line experiment in #1678. I'm not sure if this is the best way to grab the job ID.
> Fix race condition in Squal line artifact

- .buildkite/pipeline.yml
- docs/src/DevDocs/DiagnosticVariableList.md
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/variables.jl
- src/Diagnostics/vorticity_balancelaw.jl
Co-authored by @kpamnany and based on a branch by @thomasgibson .   
Allows plugging a mini balance law into the atmos_gcm_default diagnostics to compute diagnostics (e.g. gradients) using DGModel compute kernels at every diagnostic timestep.   
So far implemented for vorticity, which was previously calculated without surface numerical fluxes.
To do:
- Add a how to guide (separate PR)
- Add smoothing (e.g. discrete stiffness summation, DSS) for smoother plots (separate PR, low priority)
> Vorticity from Atmos DGModel output by Diagnostics

- experiments/AtmosGCM/GCMDriver/gcm_sources.jl
- experiments/AtmosGCM/heldsuarez.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
- experiments/AtmosLES/convective_bl_model.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Atmos/Model/tendencies_precipitation.jl
- test/Driver/mms3.jl
- test/Numerics/DGMethods/compressible_Navier_Stokes/mms_bc_atmos.jl
- tutorials/Atmos/heldsuarez.jl
This is a tracer bullet for my [proposed solution](https://github.com/CliMA/ClimateMachine.jl/issues/1832#issuecomment-742168958) to #1832 specifically for `source` in the AtmosModel--but we can extend this to `flux` as well. The basic idea is that the argument list is:
```julia
source(::S, ::BalanceLaw, args::NamedTuple, precomputed::NamedTuple) where {S <: TendencyDef{Source, PrognosticVariable}}
```
`precomputed` is computed in `source!` as
```julia
precompute(atmos::AtmosModel, args, ::Source) =
(ts = recover_thermo_state(atmos, args.state, args.aux),)
function source!(m::AtmosModel, ...)
tend = Source()
args = (
state = state,
aux = aux,
t = t,
direction = direction,
diffusive = diffusive,
)
precomputed = precompute(m, args, tend)
source.ρ = Σsources(eq_tends(Mass(), m, tend), m, …
```
> Reformulate source arguments, add precomputed NamedTuple

- src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl
Whereas code previously used `Nq[1]^(dim - 1)` and `Nq[1]`, now it uses `Nq[1] * Nq[2]` and `Nq[3]`.
> Fix batched GMRES so that it works with non-uniform polynomial orders.

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/prog_prim_conversion.jl
- src/BalanceLaws/BalanceLaws.jl
- src/BalanceLaws/prog_prim_conversion.jl
- src/BalanceLaws/state_types.jl
- test/Atmos/prog_prim_conversion/runtests.jl
- test/Atmos/runtests.jl
- test/BalanceLaws/runtests.jl
This adds `primitive_to_prognostic!` and `prognostic_to_primitive!` methods to `BalanceLaws`, as well as an `AtmosModel` implementation for all moisture models.
> Add prim<->prog conversion

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/tendencies_tracers.jl
- src/Atmos/Model/tracers.jl
This PR
- Moves the second order tracer fluxes to the new tendency specification
- Adds `tendencies_tracer.jl` to `src/Atmos/Model/`
- Moves the first order flux definition to `tendencies_tracer.jl` (I think I missed following this pattern in the first order tracer flux PR)
I'm not 100% sure about the name `Diffusion` here. cc @akshaysridhar?
> Move second order tracer flux to new tend spec

- experiments/TestCase/baroclinic_wave.jl
This PR changes the polynomial order in experiments/TestCase/baroclinic_wave.jl to (5, 6) for QA purposes.
> change poly order in baroclinic_wave.jl for QA purposes

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
This PR
- moves second order moisture fluxes (`MoistureDiffusion`) to the new tendency specification.
- Changes the argument order in `flux_second_order!(::MoistureModel, args...)` so that arguments can be easily passed through
> Move second order moisture flux to new tend spec

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/Atmos/Model/AtmosModel.jl
- src/BalanceLaws/BalanceLaws.jl
- src/BalanceLaws/tendency_types.jl
This should have been incorporated in #1850, we want `precompute` to be a `BalanceLaw` method, so that we can inherit/modularize its use across different models.
> Move precompute method to balance law

- experiments/AtmosLES/squall_line.jl
Two fixes to squall line setup:
- increase the maxiter for equilibrium runs with removed precipitation
- add forgotten AuxState output for QA plots
> fixes to squall line experiment for QA-Microphysics

- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/tendencies_precipitation.jl
This PR:
- Fixes the second order rain flux, part of which was missed in #1840
- Moves the first order flux definitions to `tendencies_precipitation.jl`, where they all reside.
> Fix second order rain flux

- src/Atmos/Model/AtmosModel.jl
- test/Atmos/prog_prim_conversion/runtests.jl
This PR `import`s `prognostic_to_primitive!, primitive_to_prognostic!` into the `Atmos` module, so that it's called with `AtmosModel`s. This was missed in #1830.
> Import prim-prog in AtmosModel

- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse.jl
This PR fixes the state ('+' or '-') used in the BC implementation for the EDMF. 
Results improved in the TKE and use errors in the table have been updated
> fix BC state used in the edmf_kernels BC implementation

- .buildkite/pipeline.yml
- Manifest.toml
- Project.toml
- src/Common/Thermodynamics/Thermodynamics.jl
- src/Common/Thermodynamics/config_numerical_method.jl
- src/Common/Thermodynamics/relations.jl
- src/Common/Thermodynamics/states.jl
- test/Common/Thermodynamics/profiles.jl
- test/Common/Thermodynamics/runtests.jl
- test/Common/Thermodynamics/runtests_gpu.jl
This PR is a step towards fixing #1831 by using the numerical method type, rather than a function, as an input to `saturation_adjustment`. This should help us more rigorously test/compare the performance and robustness of numerical methods in saturation adjustment for `ρ, e_int, q_tot` and `ρ, p, q_tot` thermo variables, which are the only two cases that are potentially used beyond initialization.
I've also battled the formatter a bit in the `@print` statements, and added a test section for performance with BenchmarkTools.
This also:
- adds a convenience method, `PhaseEquil_dev_only`, _for development only_ so that we can more easily toggle one option at a time while maintaining synchronization with all other arguments.
- Adds GPU tests
> Make swapping sat adjust numerical methods easier, add GPU tests

- docs/src/APIs/Common/TurbulenceClosures.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Atmos/Model/tendencies_precipitation.jl
- src/Atmos/Model/tendencies_tracers.jl
- src/Atmos/Model/tracers.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- test/Atmos/EDMF/edmf_kernels.jl
This is the second-order flux counter-part to #1850.
I think we'll be able to remove the call to `thermo_state` in second-order fluxes, but it will be more clear that we can once we've moved all second-order fluxes to the new specification.
I also removed a few unused pieces in `TurbulenceClosures.jl`
> Reformulate second order flux arguments, add precomputed NamedTuple

- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse.jl
This PR fixes the turbulent production sources for all second order moments in the environment, the stability function used in the mixing length l_w, and the mass flux components of the sgs fluxes.
> Fix sources and fluxes in edmf_kernels.

- docs/list_of_how_to_guides.jl
- docs/src/HowToGuides/Atmos/MoistureAndPrecip.md
This adds a tutorial on different Atmos model choices related to representing cloud condensate (aka moisture) and precipitation.
> Add moisture and precipitation tutorial

- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
This PR adds TKE budget variables to the GradientFlux() variables of the EDMF scheme. Adding these variables to a state is necessary if we want to output them with the current version of the model.
> Add TKE budget variables to GradientFlux().

- src/Atmos/Model/tendencies_momentum.jl
This PR changes `pad` in some fluxes to avoid unwanted behavior. For example `NaN * 0 = NaN`.
> Better pad to avoid `NaN * 0 = NaN`

- docs/src/APIs/Common/TurbulenceClosures.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
The PR moves hyperdiffusion to the new tendency specification.
> Move hyperdiffusion fluxes to new tend spec

- .buildkite/pipeline.yml
- docs/list_of_apis.jl
- docs/src/APIs/Numerics/DGMethods/DGMethods.md
- docs/src/APIs/Numerics/DGMethods/FVReconstructions.md
- src/BalanceLaws/interface.jl
- src/InputOutput/VTK/writevtk.jl
- src/Numerics/DGMethods/DGFVModel_kernels.jl
- src/Numerics/DGMethods/DGMethods.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
- src/Numerics/DGMethods/FVReconstructions.jl
- src/Numerics/DGMethods/NumericalFluxes.jl
- src/Numerics/Mesh/Topologies.jl
- test/Numerics/DGMethods/Euler/fvm_isentropicvortex.jl
- test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model.jl
- test/Numerics/DGMethods/advection_diffusion/advection_diffusion_model_1dimex_bgmres.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion_periodic.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection_sphere.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_swirl.jl
Creates a `DGFVModel` for the using spectral element DG in the horizontal and finite volume in the vertical.
The dimensional splitting used implies that the method will be at most (formally) 2nd order accurate.
The finite volume reconstructions are handled with the newly introduced `FVReconstructions` module. Currently the following reconstruction types are supported:
- Constant reconstructions
- Linear reconstructions with limiters
- Linear reconstructions with limiters with a wider stencil (to test the interface for WENO without actually having weno implemented)
WENO should be supported and work once the WENO types are added to the `FVReconstructions` module.
Some things left to do after this PR:
- Add back in hyperdiffusion on with DG
- Hydrostatic balance
- WENO schemes …
> Add `DGFVModel` interface

- experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
- experiments/AtmosLES/squall_line.jl
- test/Atmos/EDMF/compute_mse.jl
- test/Atmos/Model/ref_state.jl
- test/Common/Thermodynamics/data_tests.jl
- test/Land/Model/haverkamp_implicit_test.jl
- test/Land/Model/haverkamp_test.jl
- tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
Prevents race conditions with multiple tests using the same Artifact
name through ArtifactWrappers running in parallel.
> Detect CI environments and download Artifacts to unique path prefixes

- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Atmos/EDMF/report_mse.jl
- test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
This PR:
- Fixes the definition of `L_W`. The former definition in terms of a scalar coefficient does not work for obukhov lengths that are equal or larger than 0. This is because the modifier expression returns a complex value, and should not be evaluated even when multiplied by zero.
- Moves the `turbulence` model definition to the experiment files, allowing a flexible definition of turbulence models both in LES and SCM modes. It also sets a no turbulence model as default.
- Computes correctly the SGS momentum fluxes on the grid-mean, preparing EDMF for coupling with the grid-mean equations.
> Fix L_w, move turb closure to experiment, prepare for grid-mean coupling.

- docs/src/Theory/Atmos/EDMF_plots.md
- src/Atmos/Model/AtmosModel.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/closures/entr_detr.jl
- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/closures/pressure.jl
- test/Atmos/EDMF/closures/turbulence_functions.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
- test/Atmos/EDMF/helper_funcs/subdomain_statistics.jl
- test/Atmos/EDMF/report_mse_bomex.jl
This PR adds some computations to the cache in `turbconv`, in preparation to adding the tendency specification layer.
We get hit a bit hard with the formatter here, I may try to see if we can alleviate this.
> Cache some computations in turbconv

- docs/plothelpers.jl
This PR provides access to the Julia Plots function keyword arguments, that are otherwise inaccessible when wrapped inside the `plothelpers.jl` functions. It also removes the keyword argument `xlims`, since its default is the same as the one provided by Plots.jl.
> Add kwarg flexibility to plothelpers.jl

- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/tendencies_energy.jl
- src/Atmos/Model/tendencies_mass.jl
- src/Atmos/Model/tendencies_moisture.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Atmos/Model/tendencies_precipitation.jl
- src/Atmos/Model/tendencies_tracers.jl
This PR is an attempt to speed up Dycoms a bit via:
- Using `::Type{FT}` constraint in the driver, to ensure we avoid dynamic closures
- Lower the diagnostics output frequency
- Cache some of the 2nd order fluxes (both `turbulence_tensors` and some precipitation sources)
> Attempt to speed up Dycoms: Use `Type{FT}`, lower diagnostics freq, cache O2 fluxes

- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/multiphysics_types.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
This PR adds the tendency specification layer to the turbconv 2nd order fluxes and sources. For now, I've just grouped entrainment-detrainment into single sources, but we can break this up in a subsequent PR.
This closes out the table for the `AtmosModel`, so the table should be accurate after this PR.
It turns out that we cannot dump all of the sources through `AtmosModel(; source = all_sources)`, because the tuple gets too big and `map` calls `collect`.
> Add turbconv fluxes and sources tendency specification layer

- experiments/AtmosLES/stable_bl_model.jl
This PR simplifies the `surface_temperature_variation` function in the `stable_bl_model`, making it consistent with the description of these conditions in the original publication (Beare et al, 2006). Although analytically theta_liq, theta and T should be equivalent for a DryModel at the surface, I found that the T resulting from setting the BC for theta_liq is not what it is supposed to be. Its value oscillates around the value set by theta_liq. Since the variable of interest is T, the BC should be in this variable.
> Fix temp BCs for SBL.

- src/Utilities/SingleStackUtils/SingleStackUtils.jl
Not sure if/what effect this has on the single stack utils, but it looked like the +/- states were flipped for `J`.
> Fix +- bug in single stack utils

- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/Mesh/Grids.jl
This PR updates the kernel_min_neighbor_distance! for FV 
The neighbor_distance in the vertical direction for FV is approximated as the cell vertical size, 2vgeo[ijk, _JcV, e]
This enables CFL computation for FV vertical direction
> FV kernel_min_neighbor_distance! update to support  vertical CFL based dt computation

- .buildkite/pipeline.yml
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/SystemSolvers/SystemSolvers.jl
- src/Numerics/SystemSolvers/batched_generalized_minimal_residual_solver.jl
- src/Numerics/SystemSolvers/columnwise_lu_solver.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection_diffusion_model_1dimex_bjfnks.jl
- test/Numerics/SystemSolvers/bandedsystem.jl
- test/Numerics/SystemSolvers/columnwiselu.jl
This PR update the LU solver to support both DG and DGFV system
- DG: lower_bandwidth is Nq_v*nstate * eband - 1, (does not include itself) 
- eband = 1 for inviscid, since nodal point at the face communicates to the overlaping point to its neighbor
and other points only communicates to points in the same element
- eband = 2 for visous
- FV: lower_bandwidth is nstate * (stencil_width + 1 + 1) - 1,  
- since the reconstruction states depend on stencil_width points on each side, 
and the flux depends on stencil_width + 1 points on each side
- eband = (stencil_width + 2) for inviscid
- eband = max{ (stencil_width + 2), 3} for viscid, 
- since the viscous flux is computed by applying first order FD twice
Tests are added:
- The fully implicit solver with Jacobian free Newton Krylov method and …
> Fix and test the LU solver for FV

- docs/src/APIs/Utilities/SingleStackUtils.md
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- test/Utilities/SingleStackUtils/ssu_tests.jl
This PR adds `NodalStack` with `iterate(::NodalStack)`. `iterate(::NodalStack)` traverses the nodal stack and returns a `NamedTuple` of prognostic, auxiliary, diffusive, and hyperdiffusive `Vars`, so that we can write a simple callback that calls each of the physics kernels (and `precompute` caches). For example:
```julia
nodal_stack = NodalStack(solver_config; interp = true) # Allows for on-the-fly interpolating
ρ = [local_states.prog.ρ for local_states in nodal_stack] # `local_states.prog` is a `Vars{vars_state()}()` instance.
```
Next, a cache diagnostics (to be included in a later PR) will be:
```julia
function cache_diagnostics(solver_config)
bl = solver_config.dg.balance_law
t = gettime(solver_config.solver)
direction = solver_config.diffdir
return [
begin
@unpack prog, aux, ∇flux, …
```
> Add NodalStack utils and iterator

- experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
- experiments/AtmosLES/squall_line.jl
- src/InputOutput/ArtifactWrappers/ArtifactWrappers.jl
- test/Atmos/EDMF/compute_mse.jl
- test/Atmos/Model/ref_state.jl
- test/Common/Thermodynamics/data_tests.jl
- test/Land/Model/haverkamp_implicit_test.jl
- test/Land/Model/haverkamp_test.jl
- tutorials/Land/Soil/Heat/bonan_heat_tutorial.jl
This PR adds a field `local_run` to the `ArtifactsWrapper`, and if `false` (meaning running CI), then data files are only downloaded to the given directory--hashes / toml files are not created. My hope is that this closes #1678.
> Fix artifacts race condition

- src/Atmos/Model/AtmosModel.jl
- test/Atmos/EDMF/closures/entr_detr.jl
- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/closures/pressure.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
- test/Atmos/EDMF/helper_funcs/utility_funcs.jl
- test/Atmos/EDMF/report_mse_bomex.jl
This PR makes the EDMF model capable of simulating conditions of zero updraft area fraction.
Co-authored by: @charleskawczynski .
> Allow updraft zero area fraction

- .buildkite/pipeline.yml
- docs/src/APIs/Numerics/Meshes/Mesh.md
- experiments/TestCase/solid_body_rotation_mountain.jl
- src/Numerics/Mesh/Topologies.jl
co-authored with @akshaysridhar 
This PR enables enables users to define topography on the cubed sphere. It adds the following functionalities in `Topologies.jl`:
- `compute_lat_long` function to compute lat/long given cubed sphere coordinates and face id;
- `AnalyticalTopography` abstract type to hold topography function;
- `cubedshelltopowarp` function to compute the warp grid given topography function.
A `solid_body_rotation_mountain.jl` test case into the `TestCase` suite, to test the hydrostatic balance with topography. It follows the DCMIP2012 2-0-0 mountain set-up.
CI test on this case only makes sure the simulation can run but it does not check on the relative error. It will be later on added to the weekly test for visualization.
> add solid body rotation test with topography (DCMIP 2-0-0)

- docs/src/APIs/Utilities/SingleStackUtils.md
- docs/src/APIs/Utilities/VariableTemplates.md
- src/Driver/driver_configs.jl
- src/Driver/solver_config_wrappers.jl
- src/Driver/solver_configs.jl
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- src/Utilities/SingleStackUtils/single_stack_diagnostics.jl
- src/Utilities/VariableTemplates/VariableTemplates.jl
- src/Utilities/VariableTemplates/flattened_tup_chain.jl
- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
- test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
- test/Utilities/VariableTemplates/test_complex_models.jl
This PR adds `single_stack_diagnostics`, which returns an array of entries. Unlike `dict_of_nodal_states`, which returns a dictionary of arrays, `single_stack_diagnostics` returns an array of (basically) dictionaries. This may not be super-performant, but allows us to contain all of the `Vars` instances in each entry, so that we can compute and also include all quantities returned from, for example, `precompute()`--which we hope to be helpful for debugging. The other advantage of adding this is that we'll be able to (in the single stack configurations, at least) stop using aux for diagnostics, which results in global memory reads, and performs unnecessary computations at each RHS evaluation.
A next step might be splitting `precompute` (in `BalanceLaws`) into `precompute` and …
> Add single stack diagnostics, replace dons in some experiments

- test/Atmos/EDMF/report_mse_bomex.jl
Relaxes the MSE condition for Bomex. The requirement is now that the percentage change in MSE from best to computed is lower than +sqrt(eps).
> Relax acceptable MSE condition

- src/Numerics/Mesh/Interpolation.jl
@synchronize added to interpolate_local_kernel! to fix a possible race condition bug.
> Interpolation bug fix: 

- experiments/AtmosLES/bomex_les.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
- test/Atmos/EDMF/report_mse_bomex.jl
The random perturbations needed to break symmetry are moved to the LES experiment files, the only case when they are needed. Furthermore, the random perturbations are now centered around zero.
> Move random perturbations to LES experiment files

- test/Atmos/EDMF/closures/entr_detr.jl
- test/Atmos/EDMF/closures/pressure.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/helper_funcs/diagnose_environment.jl
- test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
This PR removes some turbconv aux fields, and instead computes them in (arbitrarily) the first order flux, so that it will be available in `single_stack_diagnostics`.
> Move turbconv fields from aux to cache

- src/Atmos/Model/ref_state.jl
Use `PhaseEquil_ρp[q]` instead of `air_temperature_from_ideal_gas_law`, as this is already done in `PhaseEquil_ρp[q]`, which uses the relevant available variables.
> Use better thermo constructor call

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
Add thermo method `shum_to_mixing_ratio` for computing mixing ratios (needed for radiation). I've also added a convenience method, `mixing_ratios`, which accepts a `PhasePartition`, and returns a `PhasePartition` of mixing ratios.
> Add thermo mixing ratio functions

- .buildkite/pipeline.yml
- experiments/OceanSplitExplicit/simple_box.jl
- experiments/TestCase/baroclinic_wave_fvm.jl
- experiments/TestCase/risingbubble_fvm.jl
- experiments/TestCase/solid_body_rotation_fvm.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/ref_state.jl
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/diagnostic_fields.jl
- src/Driver/Driver.jl
- src/Driver/driver_configs.jl
- src/Driver/solver_configs.jl
- src/Numerics/DGMethods/DGFVModel_kernels.jl
- src/Numerics/DGMethods/DGMethods.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/FVReconstructions.jl
- src/Numerics/Mesh/Filters.jl
- src/Ocean/SuperModels.jl
- test/Driver/mms3.jl
This PR updates the driver of the DG-FV method and tests the diagnostics of DG-FV method
So far, DG-FV can not maintain hydrostatics balance (#1881), and does not support implicit solver(#1814), and this PR should wait for #1881 and #1814
The example is in the experiments/TestCase/baroclinic_wave_fvm.jl
Some plots at a very short simulation time indicate the basic diagnostics is correct
> Update DG-FV driver and test diagnostics

- experiments/TestCase/solid_body_rotation_fvm.jl
- src/Driver/driver_configs.jl
Adds keyword support for grid stretching functions in GCM / LES configurations 
- [N/A] Unit tests are included OR N/A. [Existing feature is tested. Adds keyword argument support in `driver_configs.jl`]
- [N/A] Code is exercised in an integration test OR N/A. [See above]
- [N/A] Documentation has been added/updated OR N/A.
> Add keyword support for grid-stretching in GCM/LES Configurations.

- docs/src/APIs/Driver/index.md
- src/Driver/SolverTypes/HEVISolverType.jl
- src/Driver/SolverTypes/SolverTypes.jl
- src/Numerics/ODESolvers/BackwardEulerSolvers.jl
- src/Numerics/SystemSolvers/jacobian_free_newton_krylov_solver.jl
Improve Fully Implicit Solver
- Step size modification: When we compute gradient in the Newton dF dQ = (F(Q + epsdQ) - F(Q))/eps , but in the preconditioner reconstruction we use dF e = (F(Q + epse) - F(Q))/eps, in these two cases, dQ and e are quite different, therefore the eps need to be treated carefully.
-  Add HEVISolverType for fully implicit solver
Co-authored-by: Charles Kawczynski <kawczynski.charles@gmail.com>
> update HEVI fully implicit solver

- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- experiments/TestCase/baroclinic_wave.jl
- experiments/TestCase/solid_body_rotation_fvm.jl
- src/Driver/diagnostics_configs.jl
- src/Numerics/Mesh/Interpolation.jl
Setting up a cubed sphere interpolated grid can fail when the DG grid is stretched beyond a certain point. Allowing control of the tolerance is a temporary fix until @skandalaCLIMA implements a proper one.
Also cleaned up the interface to `InterpolationConfiguration` a little.
> Add option to set Newton-Raphson tolerance for interpolation

- src/Utilities/SingleStackUtils/single_stack_diagnostics.jl
- src/Utilities/VariableTemplates/VariableTemplates.jl
- src/Utilities/VariableTemplates/flattened_tup_chain.jl
- test/Utilities/VariableTemplates/test_complex_models.jl
After #1929, there is some mismatch with the keys and values returned from `flattened_named_tuple` and thus `single_stack_diagnostics` (e.g., IIRC, mixing length). cc @yairchn @ilopezgp. This PR should fix this mismatch. Specifically, adding
```julia
length(keys_) == length(vals) || error("key-value mismatch")
```
to `flattened_named_tuple` errors on master due to improper handling of `SHermitianCompact` and `Diagonal` arrays. This required some changes / additions to `flattened_nt_vals`.
> Fix NamedTuple keys, add error handling

- .github/workflows/OS-UnitTests.yml
Due to bugs in the julia 1.5.(2,3) runtime, the CI sysimg build is currently broken.  Disable until Julia v1.5.4 with included bugfixes is released https://github.com/JuliaLang/julia/pull/39351.
> build sysimg but don't fail on error, disable running tests with sysimg until 1.5.4 bugfix

- test/InputOutput/ArtifactWrappers/runtests.jl
- test/InputOutput/runtests.jl
Checking off a box in #1541!
I went to use [SafeTestsets.jl](https://github.com/YingboMa/SafeTestsets.jl), but I couldn't figure out how to use it without indenting all of the tests or breaking our recursive test structure call. (we can test Numerics/ or Numerics/ODESolvers).
> Add tests for ArtifactWrappers

- .buildkite/pipeline.yml
- experiments/AtmosLES/bomex_les.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/bomex_single_stack.jl
- src/Driver/driver_configs.jl
- test/Atmos/EDMF/bomex_edmf.jl
Separate diagnostics configuration for the 3 BOMEX experiments (LES, single stack, and EDMF). Single stack and EDMF modified to use the `DumpState` diagnostics group (instead of the `AtmosLESDefault` and `AtmosLESCore` used for LES).
> Adjust diagnostics output for BOMEX single stack and BOMEX EDMF

- .buildkite/pipeline.yml
- docs/bibliography.bib
- docs/src/APIs/Numerics/DGMethods/NumericalFluxes.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Numerics/DGMethods/NumericalFluxes.jl
- test/Numerics/DGMethods/Euler/isentropicvortex_lmars.jl
Adds additional option, LMARS to the available list of interface numerical fluxes. 
1) Tested against Riemann problem [1D]
2) Tested against Rising Thermal Bubble [2D]
3) Tested against Rising Thermal Bubble [3D]
I have
> Low Mach-number Approximate Riemann Solver option (LMARS) 

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
Peeled off from #1847. This PR adds a wrapper for `linearized_pressure` and uses Julia's `(;)` NamedTuple constructor syntax.
> Add linearized_pressure wrapper, more compact namedtuples

- src/Driver/Driver.jl
- src/Driver/driver_configs.jl
This is a quick patch of PR #1946 to add the `--nelems` CL option also for the Ocean configuration. 
While at it, I also printed the same `@info` that is printed in the other configs and added a missing config to the doc summary at the top of the file. 
I tested this with 
```
$ julia --project test/Ocean/HydrostaticBoussinesq/test_3D_spindown.jl --nelems 4,4,7
```
and the relevant output is:
```
┌ Info: Establishing Ocean configuration for hydrostatic_spindown
│     precision               = Float64
│     horiz polynomial order  = 4
│     vert polynomial order   = 4
│     Nˣ # elems              = 4
│     Nʸ # elems              = 4
│     Nᶻ # elems              = 7
│     domain depth            = -4.00e+02 m
└     MPI ranks               = 1
```
> Add --nelems for Ocean config

- src/Common/SurfaceFluxes/SurfaceFluxes.jl
- test/Common/SurfaceFluxes/runtests.jl
Remove unused parameter in SurfaceFluxes
> Remove unused parameter in SurfaceFluxes

- test/Atmos/TemperatureProfiles/runtests.jl
Add test for `IsothermalProfile(param_set, FT)` constructor.
> Add test to Atmos TemperatureProfiles

- docs/src/APIs/Common/TurbulenceClosures.md
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/declare_prognostic_vars.jl
- src/BalanceLaws/tendency_types.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
This PR renames `hyperdiff_momentum_flux` and `hyperdiff_enthalpy_and_momentum_flux` to `eq_tends`, because that's basically what they are--they return a tuple of tendency definition types. To make this work, we need to move some Atmos abstract prognostic variable types to the balance law, so that Atmos submodel's can use these types to distinguish between some variables. Thanks to @kpamnany for this suggestion!
> Improve TurbulenceClosures names, mv some abstract types to balance law

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/thermo_states.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
To avoid confusion, I'm removing the `recover_thermo_state` implementations, since they're unused (and already slightly stale). I've copied the implementations to the issue that needs to be fixed for the implementations to be added back in (#1648).
Glad I decided to remove this. It turns out that `bc_energy.jl` was sneakily calling the lower-level implementation. Fortunately, this is called on the first interior, so this PR should still be non-behavior changing (regarding #1648).
> Remove unused recover_thermo_state methods

- src/BalanceLaws/vars_wrappers.jl
- src/Numerics/DGMethods/DGMethods.jl
- src/Numerics/DGMethods/DGModel_kernels.jl
I missed one last wrapper in #1979 for `transform_post_gradient_laplacian!`. It's amazing that these wrappers are actually _trimming_ lines 😄
> Add Vars wrapper for `transform_post_gradient_laplacian!`

- test/Atmos/EDMF/compute_mse.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
This branch makes sure that if we use a dry model the EDMF q_tot for all subdomains is zero. 
It mainly changes things in edmf_kernels.jl 
I added here modification for the compute MSE that uses OrderedDict and compute the MSE o only for variables of interest so that dry model will not have q_tot error computed at all.
> add if for dry model

- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
This PR makes the following changes, necessary for a first proof of concept of CalibrateEmulateSample-CLIMAParameters-ClimateMachine joint use:
- Adds a new ArgParse argument option to `stable_bl_les.jl` that allows ClimateMachine to read a certain set of parameters, identified by the path to the parameter definition file.
- Takes two turbulent parameters, `C_smag` and `C_drag`, from CLIMAParameters. Before, they were hardcoded in the example.
> Expose parameters for SBL calibration.

- test/Utilities/VariableTemplates/test_complex_models.jl
Closes #1789. @yairchn. We can run with `--check-bounds={yes|no}   Emit bounds checks always or never (ignoring declarations)` to make sure we're not doing this anywhere.
> Add bounds error test to VariableTemplates

- docs/src/GettingStarted/RunningClimateMachine.md
- src/Diagnostics/Diagnostics.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_gcm_spectra.jl
- src/Diagnostics/atmos_les_core.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/atmos_les_default_perturbations.jl
- src/Diagnostics/atmos_les_spectra.jl
- src/Diagnostics/atmos_mass_energy_loss.jl
- src/Diagnostics/atmos_refstate_perturbations.jl
- src/Diagnostics/atmos_turbulence_stats.jl
- src/Diagnostics/dump_init.jl
- src/Diagnostics/dump_tendencies.jl
- src/Driver/Driver.jl
- src/InputOutput/Writers/Writers.jl
- src/InputOutput/Writers/netcdf_writer.jl
- test/Diagnostics/sin_test.jl
- test/InputOutput/Writers/runtests.jl
Now, any previously existing output files will be overwritten. Use `--output-dir` (or the environment variable or the keyword argument to `init`) to change the output directory if you don't want files overwritten.
Closes #1765.
> Remove timestamps from diagnostics output filenames

- docs/bibliography.bib
- docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
- src/Numerics/ODESolvers/MultirateInfinitesimalGARKExplicit.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalStepMethod.jl
- src/Numerics/ODESolvers/SplitExplicitMethod.jl
This PR adds some MIS Time Stepping method docstrings that were missing, so that they can show up in our API docs.
> MIS method docstrings

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- test/Atmos/EDMF/edmf_kernels.jl
I wasn't really thorough with the pads the first time around. This PR cleans up the flux pads so that we can use empty `eq_tends` for (all 🤞🏻 ) fluxes. We could alternatively handle this inside `Σfluxes`/`Σsources`, but we'd need to pass the prognostic variable to it, and I'd rather make that transition in #1921 if that materializes.
Thanks @dennisYatunin for pointing this out.
> Fix flux pads so that empty fluxes work

- docs/src/APIs/InputOutput/index.md
- src/InputOutput/VTK/VTK.jl
- src/InputOutput/VTK/fieldwriter.jl
- src/InputOutput/VTK/writevtk.jl
Allows writing of computed fields into VTK.
For example:
```julia
using ClimateMachine.VTK
function pres_fun(atmos::AtmosModel, prognostic::Vars, auxiliary::Vars)
ts = recover_thermo_state(atmos, prognostic, auxiliary)
air_pressure(ts)
end
fwriter = VTKFieldWriter(solver_config.name, [("pressure", pres_fun)])
cbfw = GenericCallbacks.EveryXSimulationTime(60) do
fwriter(solver_config.dg, solver_config.Q)
end
```
Then pass `cbfw` into `invoke!` (or `solve!`) as a callback. You can use a similar pattern to add other computed fields; just add tuples to the vector passed in to the `VTKFieldWriter` constructor.
> Add `VTKFieldWriter`

- src/Numerics/Mesh/Interpolation.jl
Interpolation KA kernel bug fix in response to issue #2014.
np, off converted to localmem.
>  Interpolation Bug fix, issue ref# 2014

- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
- src/Numerics/Mesh/Geometry.jl
- test/Numerics/Mesh/Geometry.jl
Co-authored-by: @akshaysridhar 
This PR :
- Adds a function to calculate the horizontal effective resolution in Geometry.jl
- Changes the length scale in hyperdiffusion(`DryBiharmonic` and `EquilMoistBiharmonic`) to the horizontal effective resolution. 
The parameters in the hyperdiffusion are e.g. `(ν₄, aux.hyperdiffusion.Δ, τ_timescale) = (3.359104202786882e15, 235880.1990528821, 28800.0)`, which are reasonable.
Thank @jkozdon for his help on the calculation of horizontal nodal distance!
> Change the length scale in hyperdiffusion to horizontal nodal distance

- src/Numerics/Mesh/Filters.jl
Fix race conditions due to event dependency  in the `Filter.apply!` when `EveryDirection` is used.
> Move around events in `Filters.apply!`

- experiments/TestCase/solid_body_rotation_fvm.jl
- src/Driver/diagnostics_configs.jl
- src/Driver/driver_configs.jl
Quick fix to use the DG grid's vertical range in `InterpolationConfiguration`.
> Fix `InterpolationConfiguration` for grid stretching

- docs/list_of_tutorials.jl
- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/BalanceLaws/show_tendencies.jl
- src/BalanceLaws/tendency_types.jl
- src/Driver/driver_configs.jl
- test/BalanceLaws/runtests.jl
- tutorials/BalanceLaws/tendency_specification_layer.jl
This PR:
- Adds a BalanceLaw tendency specification tutorial
- Adds some options to `show_tendencies` (`include_module ` and `table_complete`)
- Removes the warning in `show_tendencies` for the AtmosModel 🎉
> Add tend spec layer docs

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/config_numerical_method.jl
- src/Common/Thermodynamics/relations.jl
- src/Common/Thermodynamics/states.jl
- test/Common/Thermodynamics/runtests.jl
Needed for #2021, this PR adds a new thermo constructor that accepts pressure, internal energy[, and moisture].
> Add new thermo constructor

- src/Common/SurfaceFluxes/SurfaceFluxes.jl
- test/Common/SurfaceFluxes/test_universal_functions.jl
This PR:
- Fixes bug (`C_exchange` was accidentally passed into `K_exchange` in `surface_conditions`) (supersedes #2025)
- Makes `K_exchange` `similar` to the proper input for GPU compatibility
- Exposes the universal function to the `surface_conditions` interface.
- Adds universal function tests to improve coverage
> Add surf flux tests, expose uf to interface

- src/Numerics/DGMethods/DGModel_kernels.jl
- src/Numerics/DGMethods/NumericalFluxes.jl
This PR removes the `Vars` wrap around `numerical_flux_gradient!`, which does not seem to require a `Vars` method definition.
> Remove vars from numerical flux gradient

- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
- test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
The boundary conditions are now consistent with the original GABLS experiment. The default `energy_bc` is now set to `PrescribedTemperature`, although the bulk formula is still available through command line arguments.
> Fix SBL energy boundary conditions

- src/Atmos/Model/ref_state.jl
- src/Numerics/DGMethods/DGFVModel_kernels.jl
This PR change the way a balanced reference state is computed for FVM in the vertical. Currently we compute
density from the discrete balance relation assuming a pressure profile. In this PR the approach is to integrate
the discrete balance relation for pressure and density assuming a virtual temperature profile. Seems to behave better
for stretched grids.
@jiahe23 Could you test ?
Closes #2018
> Alternative balanced ref state initialization for FVM

- docs/bibliography.bib
- docs/src/APIs/Numerics/ODESolvers/ODESolvers.md
- experiments/TestCase/isothermal_zonal_flow.jl
- src/Numerics/ODESolvers/AdditiveRungeKuttaMethod.jl
- src/Numerics/ODESolvers/BackwardEulerSolvers.jl
- src/Numerics/ODESolvers/MultirateInfinitesimalStepMethod.jl
- src/Numerics/ODESolvers/ODESolvers.jl
- test/Numerics/ODESolvers/ode_tests_basic.jl
- test/Numerics/ODESolvers/ode_tests_common.jl
- test/Numerics/ODESolvers/ode_tests_convergence.jl
A HUGE thank you goes to @thomasgibson, who helped enormously in this PR. 
This PR adds another time integrator to our family of time stepping schemes. This new time integrator `Trap2LockWoodWeller` is described in the reference [paper](https://rmets.onlinelibrary.wiley.com/doi/abs/10.1002/qj.2246) as `Trap2(2,3,2)` with `δ_s = 1, δ_f = 0`. It is tested in unit tests and, if people want to try a more physically relevant experiment, they can run the `experiments/TestCase/isothermal_zonal_flow.jl`
> Trap2 time stepper

- .buildkite/pipeline.yml
- docs/list_of_tutorials.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/prog_prim_conversion.jl
- src/BalanceLaws/prog_prim_conversion.jl
- src/Common/TurbulenceConvection/TurbulenceConvection.jl
- src/Numerics/DGMethods/DGFVModel_kernels.jl
- src/Numerics/Mesh/Grids.jl
- src/Utilities/SingleStackUtils/SingleStackUtils.jl
- test/Atmos/EDMF/Artifacts.toml
- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/compute_mse.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/report_mse_sbl_fv.jl
- test/Atmos/EDMF/stable_bl_edmf_fvm.jl
- tutorials/Atmos/burgers_single_stack_fvm.jl
This branch adds a Finite Volume driver for the stable boundary layer EDMF experiment. 
This new driver has a MSE test file to track its progress compared with LES data. 
In a future PR the stable BL drivers of DG and FV will be unified to a single driver with a flag.
> Add FV option for EDMF stable BL

- experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
- experiments/TestCase/baroclinic_wave.jl
This PR adds the `RemovePrecipitation(true)` to the source terms in the moist baroclinic wave driver, and enables the removal of condensates thru the 0M microphysics scheme. 
It has been tested that the two experiment drivers can run successfully with the changes, and the `RemovePrecipitation` keyword is added to the Mass, Energy, and TotalMoisture in the tendency table.
> Enable the removal of condensate in the moist BW driver

- .buildkite/pipeline.yml
- docs/src/APIs/Atmos/AtmosModel.md
- docs/src/APIs/BalanceLaws/BalanceLaws.md
- experiments/AtmosGCM/GCMDriver/gcm_bcs.jl
- experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
- experiments/AtmosLES/stable_bl_les.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/projections.jl
- src/Atmos/Model/thermo_states.jl
- src/Atmos/Model/thermo_states_anelastic.jl
- src/BalanceLaws/sum_tendencies.jl
- src/BalanceLaws/tendency_types.jl
- test/Atmos/EDMF/report_mse_sbl_anelastic.jl
- test/Atmos/EDMF/stable_bl_anelastic1d.jl
This PR:
- Adds a `compressibility` submodel to the AtmosModel
- Adds some thermo wrappers which use the (anelastic) reference state for density
- Modify equation tendencies for the `Anelastic1D` submodel
- Adds a `projection` hook to the balance law
It seems like we can take timesteps of at least 15 seconds 🎉 
It would be nice to more elegantly (i.e., by default) handle `g = compressibility isa Compressible ? (Gravity(),) : ()`. I think that using `g = compressibility isa Compressible ? (Gravity(),) : ()` is the simplest existing solution based on how sources are currently passed to the atmos model. We can decide later if the sources should be handled differently, but this would touch many experiments and should be addressed in a separate PR.
> Add incompressible single stack model and driver configuration

- docs/src/APIs/Atmos/AtmosModel.md
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/boundaryconditions.jl
- src/Common/SurfaceFluxes/SurfaceFluxes.jl
- test/Common/SurfaceFluxes/runtests.jl
This PR makes two main changes:
- Cleans up SurfaceFluxes and makes use of more standard notation for some of its arguments.
- Corrects the description of the height at which the SurfaceFluxes functions are evaluated, which is different for DG and FV simulations.
- Enables the use of the output of `surface_conditions` (`SurfaceFluxes` module) in a new type of boundary condition set that can be specified in an experiment setup script. 
The boundary condition specification takes as input functional forms for the temperature and moisture at the ground (similar to `BulkFormulaEnergy`) and for the roughness lengths (Float or Array of floats). The output is the energy flux (for this EnergyBC).
**Disclaimer:** This PR does not add BC based on SurfaceFluxes for momentum and moisture yet. This is …
> Enable call to SurfaceFluxes from boundary conditions, clean up SurfaceFluxes

- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/report_mse_sbl_fv.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
- test/Atmos/EDMF/stable_bl_edmf_fvm.jl
- test/Atmos/EDMF/stable_bl_single_stack_implicit.jl
The current master branch does not allow access to the custom arguments in the ArgParser, in all EDMF experiments. The only way to change those settings right now are to hardcode the default. 
This change makes it possible to set the custom arguments from the command line, similarly to the master version of `stable_bl_les.jl`. This also allows exposition of parameters for tuning in the future.
> Fix access to ArgParser from command line in EDMF experiments

- .buildkite/docs-pipeline.yml
- .github/workflows/PR-Comment.yml
Lets us trigger docs builds by `@climabot build docs` comments
> Create docs build trigger

- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Numerics/Mesh/BrickMesh.jl
- src/Numerics/Mesh/Topologies.jl
- test/Numerics/Mesh/BrickMesh.jl
- test/Numerics/Mesh/mpi_connectfull.jl
Add connectmeshfull to generate vertex-level mesh connectivity for use with direct stiffness summation for continuous Galerkin solver.
> Add connectmeshfull for vertex-level connectivity

- .buildkite/pipeline.yml
- docs/src/APIs/Common/SurfaceFluxes.md
- src/Common/SurfaceFluxes/SurfaceFluxes.jl
- test/Common/SurfaceFluxes/runtests.jl
This PR adds _recovery_ unit tests to the `SurfaceFluxes` module. With this motivation:
- I add a `recover_profile` function that generates u(z), θ(z) following Monin-Obukhov Similarity Theory.
- I generate profiles u(z), θ(z) from an initial set of Monin-Obukhov parameters, and test their recovery through `surface_conditions`.
In the development of the tests,
- I found and corrected a problem in the `monin_obukhov_length` function, which allowed division by zero in a physically relevant scenario (no surface fluxes).
- I found the SurfaceFluxes module to **lack robustness in conditions of surface heating** (θ*<0). There exist logarithms of functions that can take negative values in this regime (This can easily be reproduced through the unit tests).
> Unit tests and corrections, SurfaceFluxes module

- src/Atmos/Model/thermo_states_anelastic.jl
Define pressure and use correct function call signature.
> Fix creation of Anelastic1D thermo states with NonEquilMoist

- src/Common/SurfaceFluxes/UniversalFunctions.jl
This PR fixes a small bug regarding the universal function `Psi_h`. `f_h` is only needed in conditions of `ζ<0`, and can be ill-defined otherwise. This PR moves the call to that function to the appropriate conditional block.
> Fix call to f_h

- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/closures/surface_functions.jl
- test/Atmos/EDMF/edmf_kernels.jl
This PR adds a wrapper for `subdomain_surface_values`, which now returns a NamedTuple instead of a Tuple
> Add wrapper for subdomain_surface_values

- src/Atmos/Model/bc_energy.jl
- src/Atmos/Model/bc_moisture.jl
- src/Atmos/Model/bc_momentum.jl
- src/Atmos/Model/bc_precipitation.jl
- src/Atmos/Model/bc_tracer.jl
- src/Atmos/Model/boundaryconditions.jl
- src/Atmos/Model/linear.jl
- src/Common/TurbulenceConvection/boundary_conditions.jl
- test/Atmos/EDMF/edmf_kernels.jl
In this PR, a NamedTuple is constructed with most arguments in `boundary_state!` and `normal_boundary_flux_second_order!`, and only parameters needed are `@unpack`ed in the bc implementation functions.
> Pass bc arguments with NamedTuple

- docs/src/APIs/Common/Thermodynamics.md
- src/Common/Thermodynamics/relations.jl
- test/Common/Thermodynamics/runtests.jl
This PR adds volume mixing ratio thermodynamic functions.
> Add volume mixing ratios

- test/Atmos/EDMF/bomex_edmf.jl
- test/Atmos/EDMF/helper_funcs/diagnostics_configuration.jl
- test/Atmos/EDMF/stable_bl_edmf.jl
This PR adds diagnostics_configuration in edmf helper_function and enables netcdf diagnostics in bomex and sbl edmf driver.
> improve diagnostic configuration interface for edmf

- .github/workflows/JuliaFormatter.yml
- docs/make.jl
Add analytics to published doc build to track engagement with project documentation. 
cc @valeriabarra
> Add analytics to CI doc build

- src/Driver/Driver.jl
Will this close #2047  ? 
cc: @jkozdon , @simonbyrne
> Better docstring for --cutoff-degree CL option

- docs/bibliography.bib
- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Driver/driver_configs.jl
- src/Numerics/Mesh/Interpolation.jl
- src/Numerics/Mesh/Topologies.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGMethods/Euler/acousticwave_mrigark.jl
- test/Numerics/DGMethods/Euler/acousticwave_variable_degree.jl
- test/Numerics/DGMethods/Euler/fvm_balance.jl
- test/Numerics/DGMethods/advection_diffusion/advection_sphere.jl
- test/Numerics/DGMethods/advection_diffusion/diffusion_hyperdiffusion_sphere.jl
- test/Numerics/DGMethods/advection_diffusion/direction_splitting_advection_diffusion.jl
- test/Numerics/DGMethods/advection_diffusion/fvm_advection_sphere.jl
- test/Numerics/DGMethods/compressible_navier_stokes_equations/three_dimensional/config_sphere.jl
- test/Numerics/DGMethods/conservation/sphere.jl
- test/Numerics/DGMethods/grad_test_sphere.jl
- test/Numerics/DGMethods/horizontal_integral_test.jl
- test/Numerics/DGMethods/integral_test_sphere.jl
- test/Numerics/DGMethods/remainder_model.jl
- test/Numerics/Mesh/interpolation.jl
- test/Numerics/Mesh/mpi_connect_sphere.jl
- test/Numerics/Mesh/topology.jl
This PR adds support for an equidistant cubed-sphere (as defined in [Rancic at al](https://doi.org/10.1002/qj.49712253209) and [Nair et al](https://doi.org/10.1175/MWR2890.1) ). 
Things done in this PR so far: 
This will close #1778. 
Things to think about/do: 
~~- [ ] Confirm that using the equidistant cubed-sphere in an experiment should improve the CFL condition.~~ <-- Edit: This is actually not the case with the equidistant cubed sphere, my bad for misinterpreting Rancic's paper.
> Equidistant cubed-sphere

- docs/src/GettingStarted/Atmos.md
- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- src/Atmos/Model/AtmosModel.jl
- test/Driver/cr_unit_tests.jl
- test/Driver/gcm_driver_test.jl
- test/Numerics/DGMethods/Euler/acousticwave_1d_imex.jl
- test/Numerics/DGMethods/Euler/acousticwave_variable_degree.jl
- test/Numerics/DGMethods/Euler/fvm_balance.jl
- tutorials/Numerics/TimeStepping/tutorial_acousticwave_config.jl
This PR
- Unifies the GCM / SingleStack / LES constructors, since the only difference is the orientation
- Removes the type parameters from the constructors, since there are no restrictions on the types anyway.
- Changes `turbulence::T = SmagorinskyLilly{FT}(0.21),` to `turbulence = SmagorinskyLilly{FT}(C_smag(param_set))` for `::Union{Type{AtmosLESConfigType}, Type{SingleStackConfigType}}` constructors, since [this is the default in CLIMAParameters.jl](https://github.com/CliMA/CLIMAParameters.jl/blob/master/src/Atmos/atmos_parameters.jl#L4) anyway.
> Clean up AtmosModel constructor

- src/Atmos/Model/bc_momentum.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/report_mse_sbl_anelastic.jl
- test/Atmos/EDMF/report_mse_sbl_fv.jl
This small PR remove the contribution from momentum to surface energy flux in the bulk formula, this should not appear there - see footnote in the Energy Flux section (6.2.4) in the Design Docs
> remove momentum contribution to energy bulk formula

- docs/src/APIs/Arrays/Arrays.md
- docs/src/GettingStarted/RunningClimateMachine.md
- src/Arrays/MPIStateArrays.jl
- src/Driver/Driver.jl
- src/Driver/SolverTypes/ExplicitSolverType.jl
- src/Driver/SolverTypes/HEVISolverType.jl
- src/Driver/SolverTypes/IMEXSolverType.jl
- src/Driver/SolverTypes/ImplicitSolverType.jl
- src/Driver/SolverTypes/MISSolverType.jl
- src/Driver/SolverTypes/MultirateSolverType.jl
- src/Driver/SolverTypes/SolverTypes.jl
- src/Driver/SolverTypes/SplitExplicitSolverType.jl
- src/Driver/solver_configs.jl
- src/Numerics/DGMethods/DGModel.jl
- src/Numerics/DGMethods/remainder.jl
If specified, `--checkpoint-on-crash` adds exception checking to the `wait` call in `MPIStateArrays` which is where most such crashes will be detected. An `Allreduce` call is added here which notifies all MPI ranks of the crash; a checkpoint is then written.
I've tested this using the baroclinic wave experiment (with the [filter](https://github.com/CliMA/ClimateMachine.jl/blob/master/experiments/TestCase/baroclinic_wave.jl#L288) removed to force a crash) on CPU and GPU with 1, 2 and 32 MPI ranks and it seems to work fine.
Closes #1468 and #1510.
> Add `--checkpoint-on-crash`

- docs/list_of_tutorials.jl
- docs/make.jl
- tutorials/Atmos/agnesi_hs_lin.jl
- tutorials/Ocean/geostrophic_adjustment.jl
- tutorials/Ocean/internal_wave.jl
- tutorials/Ocean/shear_instability.jl
We were running tutorials in parallel via `Literate.notebook()`, and running them all again in serial in `makedocs`. This PR removes the `@example` blocks from the tutorial markdown so that they're only executed in parallel in `Literate.notebook()`. One side-effect of this is that suppressing output is more important because truncation seems to work differently when executing markdown in Literate compared to `makedocs`, so some output in the tutorials have also been suppressed (which we probably should have done anyway). In addition, the resolution on some of the animations have been reduced.
> Do not create example blocks on executed code

- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/prog_prim_conversion.jl
- test/Atmos/prog_prim_conversion/runtests.jl
This PR updates `prognostic_to_primitive!` and `primitive_to_prognostic!` to be consistent with the Anelastic1D and Compressible formulations. Inner thermo state constructors are now handled through dispatchers when possible. Recovery tests are added for the Anelastic1D() `prognostic_to_primitive!` and `primitive_to_prognostic!` constructors.
> Update FV reconstruction with anelastic1D capabilities

- src/Common/TurbulenceClosures/TurbulenceClosures.jl
This PR makes some changes in TurbulenceClosures.jl:
- Fixes several doc strings
- Removes `hyperviscosity_tensors`, which is not used anywhere
- Removes comments that I believe are already in `TurbulenceClosures.md`
> Fix TurbulenceClosures docs, remove dead code

- .buildkite/pipeline.yml
- experiments/AtmosLES/ekman_layer_model.jl
- test/Atmos/EDMF/ekman_layer.jl
This PR adds a new neutrally stratified Ekman layer experiment to the LES/SCM library, and an anelastic driver to run it. The anelastic driver can be switched from DG to FV with a single boolean.
This configuration removes the effect of density stratification from the dynamics (in theory...), helping debug the source code in the DG and FV configurations.
> Add neutrally stratified Ekman layer experiment and anelastic driver

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/declare_prognostic_vars.jl
- src/Atmos/Model/energy.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/linear_atmos_tendencies.jl
- src/Atmos/Model/moisture.jl
- src/Atmos/Model/precipitation.jl
- src/Atmos/Model/prog_prim_conversion.jl
- src/Atmos/Model/thermo_states.jl
- src/Atmos/Model/thermo_states_anelastic.jl
- src/BalanceLaws/sum_tendencies.jl
- src/BalanceLaws/tendency_types.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
- src/Diagnostics/DiagnosticsMachine/atmos_diagnostic_funs.jl
- src/Diagnostics/StdDiagnostics/atmos_gcm_diagnostic_vars.jl
- src/Diagnostics/StdDiagnostics/atmos_les_diagnostic_vars.jl
- src/Diagnostics/atmos_gcm_default.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/atmos_les_default_perturbations.jl
- src/Diagnostics/atmos_mass_energy_loss.jl
- src/Diagnostics/thermo.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/BalanceLaws/runtests.jl
- tutorials/BalanceLaws/tendency_specification_layer.jl
- Renames EnergyModel to TotalEnergyModel (as it's more concrete)
- Renames MoistureModel to AbstractMoistureModel (since it's abstract, and we defined `Moisture <: PrognosticVariable`)
- Renames Moisture to AbstractMoisture (since it's abstract)
- Renames Precipitation to AbstractPrecipitation (since it's abstract)
A note about bikeshedding names: we cannot generally change, for example, `EnergyModel` to `AbstractEnergy`, because we're already using `AbstractEnergy <: PrognosticVariable`.
> Improve some names

- experiments/TestCase/risingbubble.jl
- experiments/TestCase/risingbubble_fvm.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/ref_state.jl
- src/Atmos/Model/tendencies_momentum.jl
- src/Diagnostics/atmos_refstate_perturbations.jl
- tutorials/Atmos/densitycurrent.jl
- tutorials/Atmos/risingbubble.jl
- tutorials/Numerics/TimeStepping/tutorial_risingbubble_config.jl
This PR moves the atmos ref state submodel into the `atmos.physics` component.
This will probably need rebase after #2128.
> Move `atmos.ref_state` to `atmos.physics.ref_state`

- experiments/AtmosLES/ekman_layer_model.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/projections.jl
- src/Atmos/Model/thermo_states.jl
- test/Atmos/prog_prim_conversion/runtests.jl
This PR moves compressibility to the `atmos.physics` struct.
> Move compressibility to atmos.physics

- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/convective_bl_model.jl
- experiments/AtmosLES/ekman_layer_model.jl
- experiments/AtmosLES/stable_bl_model.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/prog_prim_conversion.jl
- test/Atmos/EDMF/closures/entr_detr.jl
- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/closures/pressure.jl
- test/Atmos/EDMF/closures/surface_functions.jl
- test/Atmos/EDMF/closures/turbulence_functions.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/helper_funcs/nondimensional_exchange_functions.jl
- test/Atmos/EDMF/helper_funcs/save_subdomain_temperature.jl
- test/Atmos/EDMF/helper_funcs/subdomain_statistics.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
This PR moves `atmos.turbulence` and `atmos.turbconv` to `atmos.physics` and adds a getter methods.
> Move turbulence and turbconv to atmos.physics

- test/Atmos/EDMF/edmf_kernels.jl
This PR replaces the SGS flux of total energy from EDMF to grid mean with an SGS flux of total specific enthalpy consistently with the way it is done in other parts of the code.
> switch from energy to total specific enthalpy in the EDMF SGS flux 

- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/squall_line.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/linear.jl
- src/Common/TurbulenceClosures/TurbulenceClosures.jl
- src/Diagnostics/atmos_les_default.jl
This PR moves `hyperdiffusion`, `viscoussponge`, and `precipitation` from `atmos` to `atmos.physics`
> Move atmos components to atmos.physics

- docs/src/APIs/Land/LandModel.md
- docs/src/APIs/Land/RadiativeEnergyFlux.md
- src/Land/Model/LandModel.jl
- src/Land/Model/RadiativeEnergyFlux.jl
- src/Land/Model/land_bc.jl
- src/Land/Model/soil_bc.jl
- test/Land/Model/test_radiative_energy_flux_functions.jl
This module includes structures to store albedo and short wave flux values, and functions for the user to set these values. The user can either prescribe short wave flux and albedo, or net short wave flux directly. There is no spectral dependence for the first iteration of this module. This flux is then applied at the top boundary, as a SurfaceDrivenHeatBoundaryConditions bc type. 
- [x ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [N/A ] Unit tests are included OR N/A.
- [x ] Code is exercised in an integration test OR N/A.
- [x ] Documentation has been added/updated OR N/A.
> Add a radiative energy flux module to the soil model

- experiments/AtmosLES/dycoms.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/get_prognostic_vars.jl
This PR moves `radiation`, `tracers`, and `lsforcing` from `atmos` to `atmos.physics`.
> Move more atmos components to `atmos.physics`

- docs/src/APIs/Driver/index.md
- src/Driver/Driver.jl
- src/Driver/driver_configs.jl
- src/Numerics/ODESolvers/ODESolvers.jl
Needed for radiation (when Insolation.jl is added). Defaults to [`J2000`](https://en.wikipedia.org/wiki/Epoch_(astronomy)#Julian_dates_and_J2000).
> Add `--start-datetime` and `ClimateMachine.datetime()`

- test/Atmos/EDMF/closures/surface_functions.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Atmos/EDMF/ekman_layer.jl
- test/Atmos/EDMF/helper_funcs/subdomain_thermo_states.jl
This PR handles several issues needed for the EDMF to work as an ED only with zero updraft area everywhere. 
1) Allows zero area fraction at the surface to use the EMDF as ED only model 
It also renames the 'surface_scalar_coeff' to a clear name 'upd_surface_std' that reflects better on what it is used for.
2) adds fix_void_upd where the thermodynamic is using 
3) Sets the area fraction to zero in the ekman_layer EDMF driver
> Allow zero surface area fraction in EDMF 

- test/Atmos/EDMF/closures/mixing_length.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
This PR moves the computation of Shear² out of compute_gradient_flux to the precompute function. 
Further PR's should continue migrating other computations (that are diagnostic in nature) out of compute_gradient_flux.
> move shear out of compute_gradient_flux

- test/Atmos/EDMF/closures/surface_functions.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Atmos/EDMF/ekman_layer.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/report_mse_sbl_fv.jl
This PR simplifies the Ekman BCs, so that the BC of TKE equates the initial TKE, preventing sharp initial gradients. The new EDMF BCs are given by a new SurfaceModel type, as suggested by @charleskawczynski .
I also set `a_min=0` for all EDMF simulations since this has already been tested to work, and this is the physical limit. We might want to remove `a_min` soon when we transition to convective cases.
> Simplify Ekman BCs, set a_min=0

- .buildkite/pipeline.yml
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/edmf_model.jl
- test/Atmos/EDMF/report_mse_sbl_coupled_edmf_an1d.jl
- test/Atmos/EDMF/stable_bl_coupled_edmf_an1d.jl
The EDMF is finally getting to the stage where coupled (as well as decoupled) simulations are functional. This will require to test the EDMF model in coupled and decoupled modes for different settings (e.g., coupled Ekman, decoupled Bomex) and the current code structure does not allow this. To this purpose, I add the coupling type to the EDMF model, which allows dispatching simulations with or without coupling of the EDMF tendencies to the grid-mean.
Along with this, this PR adds a coupled SBL simulation test with MSE tracking.
> Dispatch on coupling mode

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/atmos_tendencies.jl
- src/Atmos/Model/get_prognostic_vars.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/prog_prim_conversion.jl
- src/Atmos/Model/thermo_states.jl
- src/Atmos/Model/thermo_states_anelastic.jl
- src/BalanceLaws/interface.jl
- src/Diagnostics/DiagnosticsMachine/group_gen.jl
- src/Diagnostics/atmos_les_default.jl
- src/Diagnostics/atmos_mass_energy_loss.jl
This PR moves the atmos energy submodel into the `atmos.physics` component. I'm open for bikeshedding names here, any thoughts @glwagner? Keep in mind that this is the second PR of many (we need getters for most atmos properties).
> Move energy submodel into atmos.physics

- docs/list_of_tutorials.jl
Looking at the generation of https://github.com/CliMA/ClimateMachine.jl/pull/2157 we are actually (still) executing the tutorials multiple times because the default for notebook generation is to execute the notebook and we already do that for the markdown output.
> do not render notebook output as the default is to execute it

- src/Land/Model/LandModel.jl
- src/Land/Model/land_tendencies.jl
- src/Land/Model/prog_types.jl
- src/Land/Model/prognostic_vars.jl
- src/Land/Model/soil_heat.jl
- src/Land/Model/soil_model.jl
- src/Land/Model/soil_water.jl
- src/Land/Model/source.jl
This PR adds the tendency specification layer to the land model. This is basically how the atmosphere does it.
> Add tendency specification layer to land model

- src/Numerics/Mesh/Filters.jl
- test/Numerics/Mesh/filter.jl
This PR adds a cutoff filter that preserves the cell average for curved elements. The current filters in CLIMA do not have this property
> add mass preserving filter

- docs/src/APIs/Numerics/Meshes/Mesh.md
- experiments/TestCase/solid_body_rotation_mountain.jl
- src/Numerics/Mesh/Topologies.jl
This quick PR is to complete the renaming I had done in PR #2060  so that these functions on the cubed-sphere have all a consistent style convention (`snake_case` for accessibility)
> Rename cubedshelltopowarp -> cubed_sphere_topo_warp

- docs/src/GettingStarted/Atmos.md
- experiments/AtmosGCM/GCMDriver/GCMDriver.jl
- experiments/AtmosGCM/GCMDriver/baroclinicwave_problem.jl
- experiments/AtmosGCM/GCMDriver/gcm_bcs.jl
- experiments/AtmosGCM/GCMDriver/heldsuarez_problem.jl
- experiments/AtmosGCM/moist_baroclinic_wave_bulksfcflux.jl
- experiments/AtmosLES/bomex_model.jl
- experiments/AtmosLES/cfsite_hadgem2-a_07_amip.jl
- experiments/AtmosLES/convective_bl_model.jl
- experiments/AtmosLES/dycoms.jl
- experiments/AtmosLES/ekman_layer_model.jl
- experiments/AtmosLES/rising_bubble_theta_formulation.jl
- experiments/AtmosLES/squall_line.jl
- experiments/AtmosLES/stable_bl_model.jl
- experiments/AtmosLES/surfacebubble.jl
- src/Atmos/Model/AtmosModel.jl
- src/Atmos/Model/boundaryconditions.jl
- src/Atmos/Model/linear.jl
- src/Atmos/Model/problem.jl
- test/Numerics/DGMethods/Euler/fvm_balance.jl
- test/Numerics/DGMethods/fv_reconstruction_test.jl
- tutorials/Atmos/dry_rayleigh_benard.jl
In preparation for #2122, this PR adds `physics` to the `AtmosBC` constructor, so that we can loop over the prognostic variables and slowly remove all other `AtmosBC` (e.g., `momentum`, `energy`, etc.).
> Add physics to AtmosBC constructor

- docs/list_of_apis.jl
- docs/src/APIs/Common/CartesianDomains.md
- docs/src/APIs/Common/CartesianFields.md
- docs/src/APIs/Ocean/Ocean.md
- src/ClimateMachine.jl
- src/Common/CartesianDomains/CartesianDomains.jl
- src/Common/CartesianDomains/rectangular_domain.jl
- src/Common/CartesianFields/CartesianFields.jl
- src/Common/CartesianFields/rectangular_element.jl
- src/Common/CartesianFields/rectangular_spectral_element_fields.jl
- src/Ocean/JLD2Writer.jl
- src/Ocean/Ocean.jl
- src/Ocean/SuperModels.jl
- test/Common/CartesianDomains/runtests.jl
- test/Common/CartesianFields/runtests.jl
- test/Common/runtests.jl
- test/Ocean/HydrostaticBoussinesqModel/test_hydrostatic_boussinesq_model.jl
- test/Ocean/runtests.jl
- tutorials/Ocean/geostrophic_adjustment.jl
- tutorials/Ocean/internal_wave.jl
- tutorials/Ocean/shear_instability.jl
This PR moves/renames the ocean
- Domains to `Utilities/CartesianDomains` and 
- Fields to `Utilities/CartesianFields`
In hopes that we can share more of this functionality across more physics components.
> Move ocean domains & fields to utilities

- docs/src/APIs/BalanceLaws/BalanceLaws.md
- src/Atmos/Model/AtmosModel.jl
- src/BalanceLaws/BalanceLaws.jl
- src/BalanceLaws/kernels.jl
- src/Land/Model/LandModel.jl
This PR adds
- `flux_first_order!`
- `flux_second_order!`
- and `source!`
fallbacks in `BalanceLaws/`, and removes the implementation in `AtmosModel.jl`. We can also remove the implementations in the land model once #2136 lands.
I guess one benefit of keeping these implementations would be for simpler debugging when we start coupling models, so I'd like to hear feedback about this idea.
> Add mutating flux-source knl fallbacks in BL

- .github/workflows/doc_build_common_error_messages.md
@charleskawczynski  here are some additional useful tips that I found myself discovering when debugging doc strings for potential warnings/errors in `Documenter.jl`. Hopefully, they can help others, too.
> Improve tips for doc string debbugging

- .gitignore
- docs/list_of_tutorials.jl
- docs/make.jl
This PR adds a hack in the tutorials so that we can flip a switch (`run_single_tutorial`) to run single tutorials without executing all of the other tutorials / documentation. This is quite a bit of a hack, but it does significantly reduce the single tutorial generation time:
```julia
include("docs/make.jl") # compile first, takes ~ 70 seconds
...
@time include("docs/make.jl")
....
1.310631 seconds (2.47 M allocations: 139.898 MiB, 2.17% gc time)
```
This may help alleviate tutorial development pain until Documenter.jl offers a way to build a single doc page--I don't see an open issue, but I also don't see this feature anywhere in the docs.
> Add single tutorial mode

- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Numerics/Mesh/GeomData.jl
- src/Numerics/Mesh/GeometricFactors.jl
- src/Numerics/Mesh/Grids.jl
- src/Numerics/Mesh/Mesh.jl
- src/Numerics/Mesh/Metrics.jl
- test/Numerics/Mesh/Metrics.jl
This ~~WIP~~ PR provides a clean-up of the interface to store and access geometric factors data at quadrature points. It adds two structures `VolumeGeometry` and `SurfaceGeometry` for easy access of the metric terms data in different modules. These structures are defined in an independent module, called `GeomData.jl` to avoid the issue of circular dependency between the `Metrics.jl` and the `Grids.jl` modules. 
Things left TODO:
> Geometric factors data structures

- src/Utilities/VariableTemplates/VariableTemplates.jl
- test/Utilities/VariableTemplates/test_complex_models.jl
This PR defines `Base.show` for `Vars`/`Grad`. Demo in the test suite:
```julia
v = Vars object:
ntuple_model_1_scalar_model_x = 1.0
ntuple_model_1_vector_model_x = Float32[2.0, 3.0, 4.0]
ntuple_model_2_scalar_model_x = 5.0
ntuple_model_2_vector_model_x = Float32[6.0, 7.0, 8.0]
ntuple_model_3_scalar_model_x = 9.0
ntuple_model_3_vector_model_x = Float32[10.0, 11.0, 12.0]
ntuple_model_4_scalar_model_x = 13.0
ntuple_model_4_vector_model_x = Float32[14.0, 15.0, 16.0]
ntuple_model_5_scalar_model_x = 17.0
ntuple_model_5_vector_model_x = Float32[18.0, 19.0, 20.0]
vector_model_x = Float32[21.0, 22.0, 23.0]
scalar_model_x = 24.0
vg = Grad object:
a_1_x = [1, 1, 1]
a_2_x = [2, 2, 2]
```
> Add show method for Vars and Grad

- src/Land/Model/RadiativeEnergyFlux.jl
- src/Land/Model/Runoff.jl
- src/Land/Model/land_bc.jl
- src/Land/Model/soil_bc.jl
- test/Land/Model/runtests.jl
- test/Land/Model/test_radiative_energy_flux_functions.jl
- tutorials/Land/Soil/PhaseChange/freezing_front.jl
When we started the soil model, we were only considering flat single column domains. We specified Neumann fluxes by giving a scalar (magnitude of flux) at the top and bottom of the domain, and internally multiplying that by the normal vector (at the top) or minus the normal vector (at the bottom), so that, in effect, the user was specifying F = fz^ and giving f. Because we did not have any mesh warping or topography, n^ = z^ at the top, and -z^ at the bottom.
We're now dealing with topography, so we have to change the language/convention. Following atmos, Precribed fluxes are given as a scalar and then internally multiplied by -n^, so the user is specifying an inward normal flux magnitude. 
For precipitation, we assume it is aligned with the z axis, so we need to project onto the normal …
> Update prescribed flux BC for general n^

- src/Atmos/Model/bc_energy.jl
- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/report_mse_sbl_coupled_edmf_an1d.jl
This PR adds to the prescribed temperature BC the sum of RHS second order fluxes to fluxᵀn, located at the state⁺ level, to match the fluxes at the state⁻ level so that the flux divergence will be zero. This addition was done before only for turbulence model.
> fix edmf bc issue

- test/Atmos/EDMF/edmf_kernels.jl
- test/Atmos/EDMF/report_mse_bomex.jl
- test/Atmos/EDMF/report_mse_sbl_coupled_edmf_an1d.jl
- test/Atmos/EDMF/report_mse_sbl_edmf.jl
This PR adds a matching TKE flux at state⁺ to that in state⁻ for the TKE so that the TKE BC will have zero flux divergence and thus will prescribed a value of surface TKE as given by the EDMF model.
> Add a 2nd order bc for TKE in EDMF

- Manifest.toml
- docs/src/APIs/Numerics/Meshes/Mesh.md
- src/Numerics/Mesh/Topologies.jl
- test/Numerics/Mesh/topology.jl
This PR finally completes work started in PR #2205  for support of conformal cubed spheres. It adds the unwarp function that was needed for visualization purposes. Many thanks to @christophernhill for adding the [inverse bits](https://github.com/CliMA/CubedSphere.jl/blob/main/src/conformal_cubed_sphere.jl#L85) in the [CubedSphere.jl](https://github.com/CliMA/CubedSphere.jl/pull/11) package. 
All tests pass.
> Conformal cubed sphere unwarp

- src/Numerics/Mesh/Topologies.jl
Just a docstring improvement that was missed in PR #2246 2246
> src/Numerics/Mesh/Topologies.jl: Fix docstring
